// packages/angular-table/src/context/flex-render.ts
import { Directive, effect, inject, input } from '@angular/core'
import {
  Cell,
  CellData,
  Header,
  RowData,
  TableFeatures,
} from '@tanstack/table-core'
import { FlexRenderDirective } from '../flex-render'

/**
 * Simplified directive wrapper of `*flexRender`.
 *
 * Use this utility component to render headers, cells, or footers with custom markup.
 *
 * Only one prop (`cell`, `header`, or `footer`) may be passed based on the used selector.
 *
 * @example
 * ```html
 * <td *flexRenderCell="cell; let cell">{{cell}}</td>
 * <th *flexRenderHeader="header; let header">{{header}}</th>
 * <th *flexRenderFooter="footer; let footer">{{footer}}</th>
 * ```
 *
 * This replaces calling `*flexRender` directly like this:
 * ```html
 * <td *flexRender="cell.column.columnDef.cell; props: cell.getContext(); let cell">{{cell}}</td>
 * <td *flexRender="header.column.columnDef.header; props: header.getContext(); let header">{{header}}</td>
 * <td *flexRender="footer.column.columnDef.footer; props: footer.getContext(); let footer">{{footer}}</td>
 * ```
 *
 * @see {FlexRender}
 */
@Directive({
  selector:
    'ng-template[flexRenderCell], ng-template[flexRenderFooter], ng-template[flexRenderHeader]',
  hostDirectives: [{ directive: FlexRenderDirective }],
})
export class FlexRenderCell<
  TFeatures extends TableFeatures,
  TData extends RowData,
  TValue extends CellData,
> {
  readonly #flexRender = inject(
    FlexRenderDirective<TFeatures, TData, TValue, any>,
  )

  readonly cell = input<Cell<TFeatures, TData, TValue>>(undefined, {
    alias: 'flexRenderCell',
  })

  readonly header = input<Header<TFeatures, TData, TValue>>(undefined, {
    alias: 'flexRenderHeader',
  })

  readonly footer = input<Header<TFeatures, TData, TValue>>(undefined, {
    alias: 'flexRenderFooter',
  })

  constructor() {
    effect(() => {
      const cell = this.cell()
      const header = this.header()
      const footer = this.footer()
      const { content, props } = this.#flexRender

      if (cell) {
        content.set(cell.column.columnDef.cell)
        props.set(cell.getContext())
      }

      if (header) {
        content.set(header.column.columnDef.header)
        props.set(header.getContext())
      }

      if (footer) {
        content.set(footer.column.columnDef.footer)
        props.set(footer.getContext())
      }
    })
  }
}

// packages/lit-table/src/flexRender.ts
import type {
  Cell,
  CellData,
  Header,
  RowData,
  TableFeatures,
} from '@tanstack/table-core'
import type { TemplateResult } from 'lit'

export function flexRender<TProps>(
  Comp:
    | ((props: TProps) => TemplateResult | string)
    | string
    | TemplateResult
    | undefined,
  props: TProps,
): TemplateResult | string | null {
  if (!Comp) return null

  if (typeof Comp === 'function') {
    return Comp(props)
  }

  return Comp
}

/**
 * Simplified component wrapper of `flexRender`. Use this utility function to render headers, cells, or footers with custom markup.
 * Only one prop (`cell`, `header`, or `footer`) may be passed.
 * @example
 * ```ts
 * ${FlexRender({ cell })}
 * ${FlexRender({ header })}
 * ${FlexRender({ footer: header })}
 * ```
 *
 * This replaces calling `flexRender` directly like this:
 * ```ts
 * flexRender(cell.column.columnDef.cell, cell.getContext())
 * flexRender(header.column.columnDef.header, header.getContext())
 * flexRender(footer.column.columnDef.footer, footer.getContext())
 * ```
 */
export type FlexRenderProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
  TValue extends CellData = CellData,
> =
  | { cell: Cell<TFeatures, TData, TValue>; header?: never; footer?: never }
  | {
      header: Header<TFeatures, TData, TValue>
      cell?: never
      footer?: never
    }
  | {
      footer: Header<TFeatures, TData, TValue>
      cell?: never
      header?: never
    }

/**
 * Simplified component wrapper of `flexRender`. Use this utility function to render headers, cells, or footers with custom markup.
 * Only one prop (`cell`, `header`, or `footer`) may be passed.
 * @example
 * ```ts
 * ${FlexRender({ cell })}
 * ${FlexRender({ header })}
 * ${FlexRender({ footer: header })}
 * ```
 *
 * This replaces calling `flexRender` directly like this:
 * ```ts
 * flexRender(cell.column.columnDef.cell, cell.getContext())
 * flexRender(header.column.columnDef.header, header.getContext())
 * flexRender(footer.column.columnDef.footer, footer.getContext())
 * ```
 */
export function FlexRender<
  TFeatures extends TableFeatures,
  TData extends RowData,
  TValue extends CellData = CellData,
>(
  props: FlexRenderProps<TFeatures, TData, TValue>,
): TemplateResult | string | null {
  if ('cell' in props && props.cell) {
    return flexRender(props.cell.column.columnDef.cell, props.cell.getContext())
  }

  if ('header' in props && props.header) {
    return flexRender(
      props.header.column.columnDef.header,
      props.header.getContext(),
    )
  }

  if ('footer' in props && props.footer) {
    return flexRender(
      props.footer.column.columnDef.footer,
      props.footer.getContext(),
    )
  }

  return null
}
