// examples/lit/realtime-trading/src/shell/Configurator.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { repeat } from 'lit/directives/repeat.js'
import { feedSampleRateAt, feedSampleRateIndex, feedSampleRateOptions } from '../feed/feed-sample-rates'
import { FORCED_VIRTUALIZATION_ROW_COUNT, resolveVirtualScrollMode } from '../table/trading-row-virtualizer'
import { configuratorOptions } from './configurator-options'
import { ControllerElement } from './controller-element'
import './Diagnostics'
import './SelectedInstrument'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
const value = (event: Event) => (event.target as HTMLInputElement | HTMLSelectElement).value
const number = (event: Event) => Number(value(event))
const checked = (event: Event) => (event.target as HTMLInputElement).checked
const options = (items: ReadonlyArray<{ readonly label: string; readonly value: number | string }>) => repeat(items, (item) => item.value, (item) => html`<option value=${item.value}>${item.label}</option>`)

@customElement('trading-configurator')
export class Configurator extends ControllerElement {
  @property({ attribute: false }) controller!: TradingBenchmarkController
  @property({ attribute: false }) feed!: MarketFeedController
  protected firstUpdated() { this.observe(this.controller.store); this.observe(this.controller.renderAtoms.rendererMode); this.observe(this.feed.store) }
  protected render() {
    const feedState = this.feed.store.get(); const benchmark = this.controller.store.get()
    const forced = feedState.instrumentCount >= FORCED_VIRTUALIZATION_ROW_COUNT
    const virtualMode = resolveVirtualScrollMode(benchmark.requestedVirtualScrollMode, feedState.instrumentCount)
    return html`<aside id="benchmark-configurator" class="configurator" aria-label="Benchmark configurator">
      <header><span>CONFIGURATOR</span><small>RUN PARAMETERS</small></header>
      <section class="config-section" aria-labelledby="feed-settings"><h2 id="feed-settings">FEED</h2>
        <button class="primary-action" type="button" data-testid="feed-toggle" @click=${this.feed.actions.toggle}>${feedState.running ? 'PAUSE FEED' : 'START FEED'}</button>
        <label class="field"><span>Instruments (rows)</span><select data-testid="instrument-count-select" .value=${String(feedState.instrumentCount)} @change=${(event: Event) => { this.controller.actions.resetViewState(); this.feed.actions.setInstrumentCount(number(event)) }}>${options(configuratorOptions.instrumentCounts)}</select></label>
        <label class="field rate-field"><span>Synthetic quote workload <strong data-testid="target-sample-rate">${rate.format(feedState.targetTicksPerSecond)} samples/s</strong></span><input data-testid="target-rate-slider" type="range" min="0" max=${feedSampleRateOptions.length - 1} step="1" .value=${String(feedSampleRateIndex(feedState.targetTicksPerSecond))} @change=${(event: Event) => this.feed.actions.setTargetRate(feedSampleRateAt(number(event)))} /><small>Fixed worker-side workload levels. Samples are coalesced; this is not the message delivery rate.</small></label>
        <label class="field"><span>Worker delivery interval</span><select data-testid="publish-interval-select" .value=${String(feedState.publishIntervalMs)} @change=${(event: Event) => this.feed.actions.setPublishInterval(number(event))}>${options(configuratorOptions.workerDeliveryIntervals)}</select><small>One coalesced worker message at this target cadence.</small></label>
      </section>
      <section class="config-section" aria-labelledby="render-settings"><h2 id="render-settings">RENDER PATH</h2>
        <label class="field" data-testid="virtual-scroll-mode"><span>Row rendering</span><select data-testid="virtual-scroll-select" .value=${virtualMode} ?disabled=${forced} @change=${(event: Event) => this.controller.actions.setVirtualScrollEnabled(value(event) === 'tanstack')}>${options(configuratorOptions.rowRenderingModes)}</select><small>${forced ? 'TanStack Virtual is required and locked at 250 or more rows.' : 'Full DOM mounts every row; TanStack Virtual mounts the visible window.'}</small></label>
        <label class="toggle-field"><input type="checkbox" .checked=${this.controller.renderAtoms.rendererMode.get() === 'swap'} @change=${(event: Event) => this.controller.actions.setRendererMode(checked(event) ? 'swap' : 'stable')} /><span>Swap Tick component A ↔ B<small>destroy and recreate when direction changes</small></span></label>
        <label class="toggle-field"><input type="checkbox" .checked=${feedState.updateSparklines} @change=${(event: Event) => this.feed.actions.setSparklineUpdates(checked(event))} /><span>Update intraday charts<small>sample rolling prices independently</small></span></label>
        <label class="field"><span>Intraday chart sampling</span><select data-testid="sparkline-sample-interval-select" .value=${String(feedState.sparklineSampleIntervalMs)} @change=${(event: Event) => this.feed.actions.setSparklineSampleInterval(number(event))}>${options(configuratorOptions.intradaySamplingIntervals)}</select></label>
      </section>
      <section class="config-section" aria-labelledby="stress-actions"><h2 id="stress-actions">STRESS ACTIONS</h2><div class="action-grid"><button type="button" @click=${this.feed.actions.runBurst}>RUN 25K BURST</button><button type="button" @click=${this.controller.actions.resetMarket}>RESET SESSION</button></div></section>
      <trading-diagnostics .controller=${this.controller}></trading-diagnostics><trading-selected-instrument .controller=${this.controller} .feed=${this.feed}></trading-selected-instrument>
    </aside>`
  }
}

// examples/svelte/realtime-trading/src/shell/Configurator.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { feedSampleRateAt, feedSampleRateIndex, feedSampleRateOptions } from '../feed/feed-sample-rates'
  import { FORCED_VIRTUALIZATION_ROW_COUNT, resolveVirtualScrollMode } from '../table/trading-row-virtualizer'
  import { configuratorOptions } from './configurator-options'
  import { useMarketFeedController, useTradingShellController } from './trading-shell-context'
  import Diagnostics from './Diagnostics.svelte'
  import SelectedInstrument from './SelectedInstrument.svelte'

  const controller = useTradingShellController()
  const feed = useMarketFeedController()
  const feedState = useSelector(feed.store)
  const benchmarkState = useSelector(controller.store)
  const rendererMode = useSelector(controller.renderAtoms.rendererMode)
  const virtualScrollForced = $derived(feedState.current.instrumentCount >= FORCED_VIRTUALIZATION_ROW_COUNT)
  const virtualScrollMode = $derived(resolveVirtualScrollMode(benchmarkState.current.requestedVirtualScrollMode, feedState.current.instrumentCount))
  const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
  const numberValue = (event: Event) => Number((event.target as HTMLInputElement | HTMLSelectElement).value)
  const stringValue = (event: Event) => (event.target as HTMLInputElement | HTMLSelectElement).value
  const checkedValue = (event: Event) => (event.target as HTMLInputElement).checked
</script>

<aside id="benchmark-configurator" class="configurator" aria-label="Benchmark configurator">
  <header><span>CONFIGURATOR</span><small>RUN PARAMETERS</small></header>
  <section class="config-section" aria-labelledby="feed-settings"><h2 id="feed-settings">FEED</h2>
    <button class="primary-action" type="button" data-testid="feed-toggle" onclick={feed.actions.toggle}>{feedState.current.running ? 'PAUSE FEED' : 'START FEED'}</button>
    <label class="field"><span>Instruments (rows)</span><select data-testid="instrument-count-select" value={feedState.current.instrumentCount} onchange={(event) => { controller.actions.resetViewState(); feed.actions.setInstrumentCount(numberValue(event)) }}>{#each configuratorOptions.instrumentCounts as option (option.value)}<option value={option.value}>{option.label}</option>{/each}</select></label>
    <label class="field rate-field"><span>Synthetic quote workload <strong data-testid="target-sample-rate">{rate.format(feedState.current.targetTicksPerSecond)} samples/s</strong></span><input data-testid="target-rate-slider" type="range" min="0" max={feedSampleRateOptions.length - 1} step="1" value={feedSampleRateIndex(feedState.current.targetTicksPerSecond)} onchange={(event) => feed.actions.setTargetRate(feedSampleRateAt(numberValue(event)))} /><small>Fixed worker-side workload levels. Samples are coalesced; this is not the message delivery rate.</small></label>
    <label class="field"><span>Worker delivery interval</span><select data-testid="publish-interval-select" value={feedState.current.publishIntervalMs} onchange={(event) => feed.actions.setPublishInterval(numberValue(event))}>{#each configuratorOptions.workerDeliveryIntervals as option (option.value)}<option value={option.value}>{option.label}</option>{/each}</select><small>One coalesced worker message at this target cadence.</small></label>
  </section>
  <section class="config-section" aria-labelledby="render-settings"><h2 id="render-settings">RENDER PATH</h2>
    <label class="field" data-testid="virtual-scroll-mode"><span>Row rendering</span><select data-testid="virtual-scroll-select" value={virtualScrollMode} disabled={virtualScrollForced} onchange={(event) => controller.actions.setVirtualScrollEnabled(stringValue(event) === 'tanstack')}>{#each configuratorOptions.rowRenderingModes as option (option.value)}<option value={option.value}>{option.label}</option>{/each}</select><small>{virtualScrollForced ? 'TanStack Virtual is required and locked at 250 or more rows.' : 'Full DOM mounts every row; TanStack Virtual mounts the visible window.'}</small></label>
    <label class="toggle-field"><input type="checkbox" checked={rendererMode.current === 'swap'} onchange={(event) => controller.actions.setRendererMode(checkedValue(event) ? 'swap' : 'stable')} /><span>Swap Tick component A ↔ B<small>destroy and recreate when direction changes</small></span></label>
    <label class="toggle-field"><input type="checkbox" checked={feedState.current.updateSparklines} onchange={(event) => feed.actions.setSparklineUpdates(checkedValue(event))} /><span>Update intraday charts<small>sample rolling prices independently</small></span></label>
    <label class="field"><span>Intraday chart sampling</span><select data-testid="sparkline-sample-interval-select" value={feedState.current.sparklineSampleIntervalMs} onchange={(event) => feed.actions.setSparklineSampleInterval(numberValue(event))}>{#each configuratorOptions.intradaySamplingIntervals as option (option.value)}<option value={option.value}>{option.label}</option>{/each}</select></label>
  </section>
  <section class="config-section" aria-labelledby="stress-actions"><h2 id="stress-actions">STRESS ACTIONS</h2>
    <div class="action-grid"><button type="button" onclick={feed.actions.runBurst}>RUN 25K BURST</button><button type="button" onclick={controller.actions.resetMarket}>RESET SESSION</button></div>
  </section>
  <Diagnostics /><SelectedInstrument />
</aside>
