// examples/angular/realtime-trading/src/app/shell/diagnostics.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { TradingBenchmarkController } from '../benchmark/trading-benchmark.controller'
import { formatInteger, formatRate } from './shell-formatters'

@Component({
  selector: 'app-diagnostics',
  template: `
    <section class="config-section diagnostics" aria-labelledby="diagnostics">
      <h2 id="diagnostics">DIAGNOSTICS</h2>
      <dl>
        <div>
          <dt>Rendered rows / source</dt>
          <dd data-testid="rendered-row-count">
            {{ formatInteger(controller.renderedRowCount()) }} /
            {{ formatInteger(controller.displayQuotes().length) }}
          </dd>
        </div>
        <div>
          <dt>Mounted cell hosts</dt>
          <dd>{{ formatInteger(controller.mountedCells()) }}</dd>
        </div>
        <div>
          <dt>Live components</dt>
          <dd>{{ formatInteger(controller.liveComponents()) }}</dd>
        </div>
        <div>
          <dt>Created / destroyed</dt>
          <dd>
            {{ formatInteger(controller.metrics().componentsCreated) }} /
            {{ formatInteger(controller.metrics().componentsDestroyed) }}
          </dd>
        </div>
        <div>
          <dt>Worker samples / s</dt>
          <dd data-testid="actual-rate">
            {{ formatRate(controller.metrics().actualTicksPerSecond) }}
          </dd>
        </div>
        <div>
          <dt>Worker messages / s</dt>
          <dd data-testid="message-rate">
            {{ controller.metrics().workerMessagesPerSecond.toFixed(1) }}
          </dd>
        </div>
        <div>
          <dt>Changed rows / s</dt>
          <dd data-testid="row-update-rate">
            {{ formatRate(controller.metrics().rowUpdatesPerSecond) }}
          </dd>
        </div>
        <div>
          <dt>State snapshots / s</dt>
          <dd data-testid="state-apply-rate">
            {{ controller.metrics().stateApplicationsPerSecond.toFixed(1) }}
          </dd>
        </div>
        <div>
          <dt>Table DOM commits / s</dt>
          <dd data-testid="table-render-rate">
            {{ controller.metrics().tableRendersPerSecond.toFixed(1) }}
          </dd>
        </div>
        <div>
          <dt>P95 / max commit latency (rolling 10 s)</dt>
          <dd>
            {{ controller.metrics().p95RenderMs.toFixed(2) }} ms /
            {{ controller.metrics().maxRenderMs.toFixed(2) }} ms
          </dd>
        </div>
        <div>
          <dt>Worker messages since reset</dt>
          <dd data-testid="worker-messages">
            {{ formatInteger(controller.metrics().workerMessages) }}
          </dd>
        </div>
        <div>
          <dt>Worker-coalesced updates / s</dt>
          <dd data-testid="superseded-update-rate">
            {{ formatRate(controller.metrics().supersededUpdatesPerSecond) }}
          </dd>
        </div>
        <div>
          <dt>Last message samples / updated rows</dt>
          <dd>
            {{ formatInteger(controller.metrics().lastBatchSize) }} /
            {{ formatInteger(controller.metrics().lastUpdateCount) }}
          </dd>
        </div>
        <div>
          <dt>Commits &gt; 16.7 ms since reset</dt>
          <dd>{{ controller.metrics().slowRenders }}</dd>
        </div>
        <div>
          <dt>Observed MutationRecords / s</dt>
          <dd data-testid="dom-mutation-rate">
            {{ formatRate(controller.metrics().domMutationsPerSecond) }}
          </dd>
        </div>
        <div>
          <dt>Long animation frames</dt>
          <dd>
            {{
              controller.longAnimationFramesSupported
                ? formatInteger(controller.metrics().longAnimationFrames)
                : 'Unsupported'
            }}
          </dd>
        </div>
        <div>
          <dt>JS heap (GC-sensitive)</dt>
          <dd>
            {{
              controller.metrics().heapMb === null
                ? 'N/A'
                : controller.metrics().heapMb!.toFixed(1) + ' MB'
            }}
          </dd>
        </div>
      </dl>
      <p class="diagnostic-note">
        MutationObserver counts delivered records, not individual DOM
        operations, and adds profiling overhead. Only class/style attributes,
        text, and child-list changes are observed. Heap is a Chromium-only
        point-in-time value and can move before garbage collection.
      </p>
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Diagnostics {
  readonly controller = inject(TradingBenchmarkController)
  readonly formatInteger = formatInteger
  readonly formatRate = formatRate
}

// examples/svelte/realtime-trading/src/shell/Diagnostics.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useTradingShellController } from './trading-shell-context'
  import type { NamedInvocationRate } from '../benchmark/benchmark-monitor'

  const state = useSelector(useTradingShellController().store)
  const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
  const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
  const ms = (value: number) => `${value.toFixed(2)} ms`
  const invocationRates = (values: ReadonlyArray<NamedInvocationRate>) => {
    const active = values.filter((entry) => entry.callsPerSecond > 0)
    return active.length === 0 ? '—' : active.map((entry) => `${entry.name} ${rate.format(entry.callsPerSecond)}`).join(' · ')
  }
  const metrics = $derived(state.current.metrics)
  const items = $derived([
    ['Worker samples / s', rate.format(metrics.actualTicksPerSecond), 'actual-rate'],
    ['Worker messages / s', metrics.workerMessagesPerSecond.toFixed(1), 'message-rate'],
    ['Changed rows / s', rate.format(metrics.rowUpdatesPerSecond), 'row-update-rate'],
    ['Snapshots applied / s', metrics.stateApplicationsPerSecond.toFixed(1), 'state-apply-rate'],
    ['DOM commits / s', metrics.tableCommitsPerSecond.toFixed(1), 'table-render-rate'],
    ['P95 / max commit latency', `${ms(metrics.p95CommitLatencyMs)} / ${ms(metrics.maxCommitLatencyMs)}`],
    ['Mounted cells', integer.format(state.current.mountedCells)],
    ['Live components', integer.format(state.current.liveComponents)],
    ['Created / destroyed', `${integer.format(metrics.componentsCreated)} / ${integer.format(metrics.componentsDestroyed)}`],
    ['Renderer callbacks / s', rate.format(metrics.cellRendererCallsPerSecond), 'cell-render-rate'],
    ['Component executions / s', rate.format(metrics.componentRenderCallsPerSecond), 'component-render-rate'],
    ['Executions by component / s', invocationRates(metrics.componentRenderRates), 'component-render-breakdown'],
    ['Callbacks by column / s', invocationRates(metrics.cellRendererRates), 'cell-render-breakdown'],
    ['Observed MutationRecords / s', rate.format(metrics.domMutationsPerSecond), 'dom-mutation-rate'],
    ['Core row model calls / s', metrics.rowModelCallsPerSecond.toFixed(1), 'row-model-call-rate'],
    ['Core row model avg / max', `${ms(metrics.rowModelAverageMs)} / ${ms(metrics.rowModelMaxMs)}`, 'row-model-duration'],
    ['Visible rows', integer.format(metrics.visibleRows), 'visible-row-count'],
    ['Worker messages', integer.format(metrics.workerMessages), 'worker-messages'],
    ['Worker-coalesced updates / s', rate.format(metrics.supersededUpdatesPerSecond), 'superseded-update-rate'],
    ['Last samples / updated rows', `${integer.format(metrics.lastBatchSize)} / ${integer.format(metrics.lastUpdateCount)}`],
    ['Commits > 16.7 ms', integer.format(metrics.slowCommits)],
    ['JS heap (GC-sensitive)', metrics.heapMb === null ? 'N/A' : `${metrics.heapMb.toFixed(1)} MB`],
  ] as const)
</script>

<section class="config-section diagnostics" aria-labelledby="diagnostics"><h2 id="diagnostics">DIAGNOSTICS</h2><dl>
  {#each items as item (item[0])}<div><dt>{item[0]}</dt><dd data-testid={item[2]}>{item[1]}</dd></div>{/each}
</dl></section>
