// examples/lit/realtime-trading/src/shell/MarketStatusbar.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { ControllerElement } from './controller-element'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
@customElement('trading-market-statusbar')
export class MarketStatusbar extends ControllerElement {
  @property({ attribute: false }) controller!: TradingBenchmarkController
  protected firstUpdated() {
    this.observe(this.controller.store)
  }
  protected render() {
    const state = this.controller.store.get()
    return html`<footer class="market-statusbar">
      <span
        >MESSAGE SAMPLES
        <strong>${integer.format(state.metrics.lastBatchSize)}</strong></span
      ><span
        >ROW UPDATES
        <strong>${integer.format(state.metrics.lastUpdateCount)}</strong></span
      ><span>HOSTS <strong>${integer.format(state.mountedCells)}</strong></span
      ><span
        >COMPONENTS
        <strong>${integer.format(state.liveComponents)}</strong></span
      >
    </footer>`
  }
}

// examples/svelte/realtime-trading/src/shell/MarketStatusbar.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useTradingShellController } from './trading-shell-context'
  const state = useSelector(useTradingShellController().store)
  const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
</script>

<footer class="market-statusbar">
  <span>MESSAGE SAMPLES <strong>{integer.format(state.current.metrics.lastBatchSize)}</strong></span>
  <span>ROW UPDATES <strong>{integer.format(state.current.metrics.lastUpdateCount)}</strong></span>
  <span>HOSTS <strong>{integer.format(state.current.mountedCells)}</strong></span>
  <span>COMPONENTS <strong>{integer.format(state.current.liveComponents)}</strong></span>
</footer>
