// examples/angular/realtime-trading/src/app/shell/market-statusbar.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { TradingBenchmarkController } from '../benchmark/trading-benchmark.controller'
import { formatInteger } from './shell-formatters'

@Component({
  selector: 'app-market-statusbar',
  template: `
    <footer class="market-statusbar">
      <span>
        MESSAGE SAMPLES
        <strong>
          {{ formatInteger(controller.metrics().lastBatchSize) }}
        </strong>
      </span>
      <span>
        ROW UPDATES
        <strong>
          {{ formatInteger(controller.metrics().lastUpdateCount) }}
        </strong>
      </span>
      <span>
        CELL HOSTS
        <strong>{{ formatInteger(controller.mountedCells()) }}</strong>
      </span>
      <span>
        COMPONENTS
        <strong>{{ formatInteger(controller.liveComponents()) }}</strong>
      </span>
    </footer>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MarketStatusbar {
  readonly controller = inject(TradingBenchmarkController)
  readonly formatInteger = formatInteger
}

// examples/svelte/realtime-trading/src/shell/MarketStatusbar.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useTradingShellController } from './trading-shell-context'
  const state = useSelector(useTradingShellController().store)
  const integer = new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 })
</script>

<footer class="market-statusbar">
  <span>MESSAGE SAMPLES <strong>{integer.format(state.current.metrics.lastBatchSize)}</strong></span>
  <span>ROW UPDATES <strong>{integer.format(state.current.metrics.lastUpdateCount)}</strong></span>
  <span>HOSTS <strong>{integer.format(state.current.mountedCells)}</strong></span>
  <span>COMPONENTS <strong>{integer.format(state.current.liveComponents)}</strong></span>
</footer>
