// examples/angular/realtime-trading/src/app/shell/metrics-strip.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core'
import { TradingBenchmarkController } from '../benchmark/trading-benchmark.controller'
import { formatMs, formatRate } from './shell-formatters'

@Component({
  selector: 'app-metrics-strip',
  template: `
    <section class="metrics-strip" aria-label="Live performance metrics">
      <article>
        <span>WORKER SAMPLES</span>
        <strong data-testid="actual-rate">
          {{ formatRate(controller.metrics().actualTicksPerSecond) }}
        </strong>
        <small>generated samples/s</small>
      </article>
      <article>
        <span>ROW UPDATES</span>
        <strong data-testid="row-update-rate">
          {{ formatRate(controller.metrics().rowUpdatesPerSecond) }}
        </strong>
        <small>unique rows applied/s</small>
      </article>
      <article>
        <span>MESSAGES</span>
        <strong data-testid="message-rate">
          {{ controller.metrics().workerMessagesPerSecond.toFixed(1) }}
        </strong>
        <small>worker messages/s</small>
      </article>
      <article>
        <span>STATE APPLIES</span>
        <strong data-testid="state-apply-rate">
          {{ controller.metrics().stateApplicationsPerSecond.toFixed(1) }}
        </strong>
        <small>quote snapshots/s</small>
      </article>
      <article>
        <span>TABLE COMMITS</span>
        <strong data-testid="table-render-rate">
          {{ controller.metrics().tableRendersPerSecond.toFixed(1) }}
        </strong>
        <small>completed renders/s</small>
      </article>
      <article>
        <span>AVG RENDER</span>
        <strong>{{ formatMs(controller.metrics().averageRenderMs) }}</strong>
        <small>mutation → render</small>
      </article>
      <article>
        <span>P95 RENDER</span>
        <strong>{{ formatMs(controller.metrics().p95RenderMs) }}</strong>
        <small>max {{ formatMs(controller.metrics().maxRenderMs) }}</small>
      </article>
      <article>
        <span>LONG FRAMES</span>
        @if (controller.longAnimationFramesSupported) {
          <strong
            data-testid="long-frame-count"
            [class.metric-alert]="controller.metrics().longAnimationFrames > 0"
          >
            {{ controller.metrics().longAnimationFrames }}
          </strong>
          <small>
            worst
            {{ formatMs(controller.metrics().worstLongAnimationFrameMs) }}
          </small>
        } @else {
          <strong data-testid="long-frame-count">N/A</strong>
          <small>unsupported</small>
        }
      </article>
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MetricsStrip {
  readonly controller = inject(TradingBenchmarkController)
  readonly formatMs = formatMs
  readonly formatRate = formatRate
}

// examples/svelte/realtime-trading/src/shell/MetricsStrip.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useTradingShellController } from './trading-shell-context'
  const state = useSelector(useTradingShellController().store, ({ metrics, longAnimationFramesSupported }) => ({ metrics, longAnimationFramesSupported }))
  const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
  const formatMs = (value: number) => `${value.toFixed(2)} ms`
  const metrics = $derived(state.current.metrics)
  const items = $derived([
    { label: 'WORKER SAMPLES', value: rate.format(metrics.actualTicksPerSecond), detail: 'generated samples/s', testId: 'actual-rate' },
    { label: 'ROW UPDATES', value: rate.format(metrics.rowUpdatesPerSecond), detail: 'unique rows applied/s', testId: 'row-update-rate' },
    { label: 'MESSAGES', value: metrics.workerMessagesPerSecond.toFixed(1), detail: 'worker messages/s', testId: 'message-rate' },
    { label: 'STATE APPLIES', value: metrics.stateApplicationsPerSecond.toFixed(1), detail: 'quote snapshots/s', testId: 'state-apply-rate' },
    { label: 'TABLE COMMITS', value: metrics.tableRendersPerSecond.toFixed(1), detail: 'completed renders/s', testId: 'table-render-rate' },
    { label: 'AVG RENDER', value: formatMs(metrics.averageRenderMs), detail: 'mutation → render' },
    { label: 'P95 RENDER', value: formatMs(metrics.p95RenderMs), detail: `max ${formatMs(metrics.maxRenderMs)}` },
    { label: 'LONG FRAMES', value: state.current.longAnimationFramesSupported ? String(metrics.longAnimationFrames) : 'N/A', detail: state.current.longAnimationFramesSupported ? `worst ${formatMs(metrics.worstLongAnimationFrameMs)}` : 'unsupported', testId: 'long-frame-count' },
  ])
</script>

<section class="metrics-strip" aria-label="Live performance metrics">
  {#each items as item (item.label)}<article><span>{item.label}</span><strong data-testid={item.testId}>{item.value}</strong><small>{item.detail}</small></article>{/each}
</section>
