// examples/solid/filters/src/ColumnFilter.tsx
import { createDebouncer } from '@tanstack/solid-pacer/debouncer'
import { Show } from 'solid-js'
import type { Person } from './makeData'
import type { _features } from './App'
import type { Column, Table } from '@tanstack/solid-table'

function ColumnFilter(props: {
  column: Column<typeof _features, Person, unknown>
  table: Table<typeof _features, Person>
}) {
  const firstValue = props.table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(props.column.id)

  const columnFilterValue = () => props.column.getFilterValue()
  const columnFilterDebouncer = createDebouncer(
    (value: unknown) => props.column.setFilterValue(value),
    { wait: 500 },
  )

  return (
    <Show
      when={typeof firstValue === 'number'}
      fallback={
        <div>
          <input
            type="text"
            value={(columnFilterValue() ?? '') as string}
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(e.currentTarget.value)
            }
            placeholder={`Search...`}
            class="filter-select"
            list={`${props.column.id}list`}
          />
        </div>
      }
    >
      <div>
        <div class="filter-row">
          <input
            type="number"
            min={0}
            max={100}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[0] ?? ''
            }
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(
                (old: [number, number] | undefined) => [
                  e.currentTarget.value,
                  old?.[1] ?? '',
                ],
              )
            }
            placeholder={`Min`}
            class="filter-input"
          />
          <input
            type="number"
            min={0}
            max={100}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[1] ?? ''
            }
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(
                (old: [number, number] | undefined) => [
                  old?.[0] ?? '',
                  e.currentTarget.value,
                ],
              )
            }
            placeholder={`Max`}
            class="filter-input"
          />
        </div>
      </div>
    </Show>
  )
}

export default ColumnFilter

// examples/svelte/with-tanstack-form/src/ColumnFilter.svelte
<script lang="ts">
  import { useHeaderContext, useTableContext } from './table'

  const header = useHeaderContext()
  const table = useTableContext()

  const firstValue = () =>
    table.getPreFilteredRowModel().flatRows[0]?.getValue(header.column.id)

  const filterValue = () => header.column.getFilterValue()
</script>

{#if header.column.getCanFilter()}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div onclick={(event) => event.stopPropagation()}>
    {#if typeof firstValue() === 'number'}
      <div class="filter-row">
        <input
          type="number"
          value={(filterValue() as [number, number] | undefined)?.[0] ?? ''}
          oninput={(event) =>
            header.column.setFilterValue(
              (old: [number, number] | undefined) => [
                event.currentTarget.value,
                old?.[1],
              ],
            )}
          placeholder="Min"
          class="filter-input"
        />
        <input
          type="number"
          value={(filterValue() as [number, number] | undefined)?.[1] ?? ''}
          oninput={(event) =>
            header.column.setFilterValue(
              (old: [number, number] | undefined) => [
                old?.[0],
                event.currentTarget.value,
              ],
            )}
          placeholder="Max"
          class="filter-input"
        />
      </div>
    {:else}
      <input
        type="text"
        value={(filterValue() ?? '') as string}
        oninput={(event) =>
          header.column.setFilterValue(event.currentTarget.value)}
        placeholder="Search..."
        class="filter-select"
      />
    {/if}
  </div>
{/if}
