// examples/vue/with-tanstack-form/src/RowSubmitTableRow.vue
<script setup lang="ts">
import { useForm } from '@tanstack/vue-form'
import { watch } from 'vue'
import NumberField from './NumberField.vue'
import SelectField from './SelectField.vue'
import TextField from './TextField.vue'
import { personSchema } from './schema'
import type { appFeatures } from './table'
import type { FormRow } from './schema'
import type { Row } from '@tanstack/vue-table'

const props = defineProps<{
  row: Row<typeof appFeatures, FormRow>
  save: (originalRow: FormRow, value: FormRow) => void
}>()

const form = useForm({
  defaultValues: props.row.original,
  onSubmit: ({ value }: { value: FormRow }) => {
    props.save(props.row.original, value)
    form.reset(value)
  },
  validators: {
    onChange: personSchema,
  },
})

const selector = (state: {
  canSubmit: boolean
  isDirty: boolean
  isSubmitting: boolean
}) => ({
  canSubmit: state.canSubmit,
  isDirty: state.isDirty,
  isSubmitting: state.isSubmitting,
})

watch(
  () => props.row.original,
  (row) => {
    form.reset(row)
  },
)
</script>

<template>
  <tr>
    <td v-for="cell in row.getAllCells()" :key="cell.id">
      <TextField
        v-if="cell.column.id === 'firstName'"
        :form="form"
        name="firstName"
      />
      <TextField
        v-else-if="cell.column.id === 'lastName'"
        :form="form"
        name="lastName"
      />
      <NumberField
        v-else-if="cell.column.id === 'age'"
        :form="form"
        name="age"
      />
      <NumberField
        v-else-if="cell.column.id === 'visits'"
        :form="form"
        name="visits"
      />
      <SelectField
        v-else-if="cell.column.id === 'status'"
        :form="form"
        name="status"
      />
      <NumberField
        v-else-if="cell.column.id === 'progress'"
        :form="form"
        name="progress"
      />
      <component
        :is="form.Subscribe"
        v-else-if="cell.column.id === 'save'"
        :selector="selector"
        v-slot="state"
      >
        <div class="row-action-cell">
          <button
            v-if="state.isDirty"
            type="button"
            :disabled="!state.canSubmit || state.isSubmitting"
            class="demo-button demo-button-sm primary-action"
            @click="form.handleSubmit()"
          >
            {{ state.isSubmitting ? 'Saving...' : 'Save' }}
          </button>
        </div>
      </component>
    </td>
  </tr>
</template>

// examples/svelte/with-tanstack-form/src/RowSubmitTableRow.svelte
<script lang="ts">
  import { createAppForm } from './form'
  import { untrack } from 'svelte'
  import { personSchema } from './schema'
  import type { appFeatures } from './table'
  import type { FormRow } from './schema'
  import type { Row } from '@tanstack/svelte-table'

  const { row, onSave }: {
    row: Row<typeof appFeatures, FormRow>
    onSave: (originalRow: FormRow, value: FormRow) => void
  } = $props()

  const form = createAppForm(() => ({
    defaultValues: row.original,
    onSubmit: ({ value }: { value: FormRow }) => {
      onSave(row.original, value)
      form.reset(value)
    },
    validators: {
      onChange: personSchema,
    },
  }))

  $effect(() => {
    const original = row.original
    untrack(() => form.reset(original))
  })
</script>

<tr>
  {#each row.getAllCells() as cell (cell.id)}
    <td>
      {#if cell.column.id === 'firstName'}
        <form.AppField name="firstName">
          {#snippet children(field: any)}
            <field.TextField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'lastName'}
        <form.AppField name="lastName">
          {#snippet children(field: any)}
            <field.TextField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'age'}
        <form.AppField name="age">
          {#snippet children(field: any)}
            <field.NumberField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'visits'}
        <form.AppField name="visits">
          {#snippet children(field: any)}
            <field.NumberField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'status'}
        <form.AppField name="status">
          {#snippet children(field: any)}
            <field.SelectField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'progress'}
        <form.AppField name="progress">
          {#snippet children(field: any)}
            <field.NumberField />
          {/snippet}
        </form.AppField>
      {:else if cell.column.id === 'save'}
        <form.Subscribe
          selector={(state) => ({
            canSubmit: state.canSubmit,
            isDirty: state.isDirty,
            isSubmitting: state.isSubmitting,
          })}
        >
          {#snippet children({ canSubmit, isDirty, isSubmitting })}
            <div class="row-action-cell">
              {#if isDirty}
                <button
                  type="button"
                  disabled={!canSubmit || isSubmitting}
                  onclick={() => form.handleSubmit()}
                  class="demo-button demo-button-sm primary-action"
                >
                  {isSubmitting ? 'Saving...' : 'Save'}
                </button>
              {/if}
            </div>
          {/snippet}
        </form.Subscribe>
      {/if}
    </td>
  {/each}
</tr>
