// examples/vue/with-tanstack-form/src/TextField.vue
<script setup lang="ts">
import { getErrorMessage, shouldShowErrors } from './field-utils'

defineProps<{
  form: any
  name: string
}>()
</script>

<template>
  <component :is="form.Field" :name="name" v-slot="{ field, state }">
    <div>
      <input
        class="text-input"
        :value="state.value"
        @input="field.handleChange(($event.target as HTMLInputElement).value)"
        @blur="field.handleBlur()"
      />
      <div v-if="shouldShowErrors(state.meta)" class="error-text">
        {{ state.meta.errors.map(getErrorMessage).join(', ') }}
      </div>
    </div>
  </component>
</template>

// examples/svelte/with-tanstack-form/src/TextField.svelte
<script lang="ts">
  import { useFieldContext } from './form-context.js'

  const field = useFieldContext<string>()
</script>

<div>
  <input
    class="text-input"
    value={field.state.value}
    oninput={(e: Event) =>
      field.handleChange((e.target as HTMLInputElement).value)}
    onblur={() => field.handleBlur()}
  />
  {#if field.state.meta.errors.length > 0}
    <div class="error-text">{field.state.meta.errors.join(', ')}</div>
  {/if}
</div>
