// examples/preact/realtime-trading/src/shell/TradingShell.tsx
import { shallow, useSelector } from '@tanstack/preact-store'
import { useState } from 'preact/hooks'
import {
  feedSampleRateAt,
  feedSampleRateIndex,
  feedSampleRateOptions,
} from '../feed/feed-sample-rates'
import {
  FORCED_VIRTUALIZATION_ROW_COUNT,
  resolveVirtualScrollMode,
} from '../table/trading-row-virtualizer'
import {
  useMarketFeedController,
  useTradingShellController,
  useTradingShellState,
} from './trading-shell-context'
import { configuratorOptions } from './configurator-options'
import type { ComponentChildren } from 'preact'
import type { FeedMetrics } from '../benchmark/benchmark-monitor'

const integerFormatter = new Intl.NumberFormat('en-US', {
  maximumFractionDigits: 0,
})
const rateFormatter = new Intl.NumberFormat('en-US', {
  notation: 'compact',
  maximumFractionDigits: 1,
})
export function TradingShell(props: { children: ComponentChildren }) {
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const toggleSidebar = () => setSidebarOpen((open) => !open)

  return (
    <main
      className={`trading-terminal ${sidebarOpen ? '' : 'is-sidebar-collapsed'}`}
    >
      <div className="shell-header">
        <AppHeader sidebarOpen={sidebarOpen} onSidebarToggle={toggleSidebar} />

        {import.meta.env.DEV && (
          <aside className="development-warning">
            DEV BUILD — use the production build before recording results.
          </aside>
        )}
      </div>

      <section className="market-panel" aria-label="Live synthetic quotes">
        <MetricsStrip />
        {props.children}
      </section>
      <MarketStatusbar />
      <div className="sidebar-slot">{sidebarOpen && <Configurator />}</div>
    </main>
  )
}

function AppHeader(props: {
  sidebarOpen: boolean
  onSidebarToggle: () => void
}) {
  const feed = useMarketFeedController()
  const workerReady = useSelector(feed.workerReady)
  const running = useSelector(feed.running)
  return (
    <header className="app-bar">
      <div className="brand">
        <strong>MARKET MONITOR</strong>
      </div>
      <div className="header-actions">
        <span
          className={`feed-status ${workerReady && running ? 'is-running' : ''}`}
          data-testid="feed-status"
        >
          <span className="status-dot" aria-hidden="true" />
          {!workerReady
            ? 'FEED CONNECTING'
            : running
              ? 'FEED LIVE'
              : 'FEED PAUSED'}
        </span>
        <button
          className="sidebar-toggle"
          type="button"
          aria-expanded={props.sidebarOpen}
          aria-controls="benchmark-configurator"
          aria-label={
            props.sidebarOpen ? 'Close configurator' : 'Open configurator'
          }
          title={props.sidebarOpen ? 'Close configurator' : 'Open configurator'}
          onClick={props.onSidebarToggle}
        >
          <svg viewBox="0 0 20 20" aria-hidden="true">
            <rect x="2.5" y="3" width="15" height="14" rx="1.5" />
            <path d="M12.5 3v14" />
          </svg>
        </button>
      </div>
    </header>
  )
}

function MarketStatusbar() {
  const { lastBatchSize, lastUpdateCount, mountedCells, liveComponents } =
    useTradingShellState(
      (state) => ({
        lastBatchSize: state.metrics.lastBatchSize,
        lastUpdateCount: state.metrics.lastUpdateCount,
        mountedCells: state.mountedCells,
        liveComponents: state.liveComponents,
      }),
      { compare: shallow },
    )
  return (
    <footer className="market-statusbar">
      <span>
        MESSAGE SAMPLES <strong>{formatInteger(lastBatchSize)}</strong>
      </span>
      <span>
        ROW UPDATES <strong>{formatInteger(lastUpdateCount)}</strong>
      </span>
      <span>
        HOSTS <strong>{formatInteger(mountedCells)}</strong>
      </span>
      <span>
        COMPONENTS <strong>{formatInteger(liveComponents)}</strong>
      </span>
    </footer>
  )
}

function Configurator() {
  const benchmarkState = useTradingShellState(
    (storeState) => ({
      requestedVirtualScrollMode: storeState.requestedVirtualScrollMode,
    }),
    { compare: shallow },
  )
  const controller = useTradingShellController()
  const feed = useMarketFeedController()
  const running = useSelector(feed.running)
  const instrumentCount = useSelector(feed.instrumentCount)
  const targetTicksPerSecond = useSelector(feed.targetTicksPerSecond)
  const publishIntervalMs = useSelector(feed.publishIntervalMs)
  const updateSparklines = useSelector(feed.updateSparklines)
  const sparklineSampleIntervalMs = useSelector(
    feed.sparklineSampleIntervalMs,
  )
  const rendererMode = useSelector(controller.renderAtoms.rendererMode)
  const { actions } = controller
  const feedActions = feed.actions
  const { requestedVirtualScrollMode } = benchmarkState
  const { setRendererMode, setVirtualScrollEnabled, resetMarket } = actions
  const {
    toggle,
    setInstrumentCount,
    setTargetRate,
    setPublishInterval,
    setSparklineUpdates,
    setSparklineSampleInterval,
    runBurst,
  } = feedActions
  const virtualScrollForced = instrumentCount >= FORCED_VIRTUALIZATION_ROW_COUNT
  const virtualScrollMode = resolveVirtualScrollMode(
    requestedVirtualScrollMode,
    instrumentCount,
  )

  return (
    <aside
      id="benchmark-configurator"
      className="configurator"
      aria-label="Benchmark configurator"
    >
      <header>
        <span>CONFIGURATOR</span>
        <small>RUN PARAMETERS</small>
      </header>

      <section className="config-section" aria-labelledby="feed-settings">
        <h2 id="feed-settings">FEED</h2>
        <button
          className="primary-action"
          type="button"
          data-testid="feed-toggle"
          onClick={toggle}
        >
          {running ? 'PAUSE FEED' : 'START FEED'}
        </button>

        <label className="field">
          <span>Instruments (rows)</span>
          <select
            data-testid="instrument-count-select"
            value={instrumentCount}
            onChange={(event) => {
              actions.resetViewState()
              setInstrumentCount(Number(event.currentTarget.value))
            }}
          >
            {configuratorOptions.instrumentCounts.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </label>

        <label className="field rate-field">
          <span>
            Synthetic quote workload
            <strong data-testid="target-sample-rate">
              {formatRate(targetTicksPerSecond)} samples/s
            </strong>
          </span>
          <input
            data-testid="target-rate-slider"
            type="range"
            min={0}
            max={feedSampleRateOptions.length - 1}
            step={1}
            list="worker-sample-rate-steps"
            value={feedSampleRateIndex(targetTicksPerSecond)}
            aria-valuetext={`${formatRate(
              targetTicksPerSecond,
            )} synthetic quote samples per second`}
            onChange={(event) =>
              setTargetRate(feedSampleRateAt(Number(event.currentTarget.value)))
            }
          />
          <datalist id="worker-sample-rate-steps">
            {feedSampleRateOptions.map((option, index) => (
              <option key={option.value} value={index} label={option.label} />
            ))}
          </datalist>
          <small>
            Fixed worker-side workload levels, from 100 to 100K samples/s.
            Samples are coalesced; this is not the message delivery rate.
          </small>
        </label>

        <label className="field">
          <span>Worker delivery interval</span>
          <select
            data-testid="publish-interval-select"
            value={publishIntervalMs}
            onChange={(event) =>
              setPublishInterval(Number(event.currentTarget.value))
            }
          >
            {configuratorOptions.workerDeliveryIntervals.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <small>
            The worker posts one coalesced update message at this target
            cadence.
          </small>
        </label>
      </section>

      <section className="config-section" aria-labelledby="render-settings">
        <h2 id="render-settings">RENDER PATH</h2>
        <label className="field" data-testid="virtual-scroll-mode">
          <span>Row rendering</span>
          <select
            data-testid="virtual-scroll-select"
            value={virtualScrollMode}
            disabled={virtualScrollForced}
            onChange={(event) =>
              setVirtualScrollEnabled(event.currentTarget.value === 'tanstack')
            }
          >
            {configuratorOptions.rowRenderingModes.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <small>
            {virtualScrollForced
              ? 'TanStack Virtual is required and locked at 1,500 or more rows.'
              : 'Full DOM is the default below 200 rows; TanStack Virtual is the default from 200 rows and remains selectable.'}
          </small>
        </label>

        <label className="toggle-field">
          <input
            type="checkbox"
            checked={rendererMode === 'swap'}
            onChange={(event) =>
              setRendererMode(event.currentTarget.checked ? 'swap' : 'stable')
            }
          />
          <span>
            Swap Tick component A ↔ B
            <small>destroy and recreate when direction changes</small>
          </span>
        </label>

        <label className="toggle-field">
          <input
            type="checkbox"
            checked={updateSparklines}
            onChange={(event) =>
              setSparklineUpdates(event.currentTarget.checked)
            }
          />
          <span>
            Update intraday charts
            <small>
              sample rolling prices independently for every instrument
            </small>
          </span>
        </label>

        <label className="field">
          <span>Intraday chart sampling</span>
          <select
            data-testid="sparkline-sample-interval-select"
            value={sparklineSampleIntervalMs}
            onChange={(event) =>
              setSparklineSampleInterval(Number(event.currentTarget.value))
            }
          >
            {configuratorOptions.intradaySamplingIntervals.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
          <small>
            How often each row adds a point to its sparkline. Quote generation
            and worker delivery are unaffected.
          </small>
        </label>
      </section>

      <section className="config-section" aria-labelledby="stress-actions">
        <h2 id="stress-actions">STRESS ACTIONS</h2>
        <div className="action-grid">
          <button type="button" onClick={runBurst}>
            RUN 25K BURST
          </button>
          <button type="button" onClick={resetMarket}>
            RESET SESSION
          </button>
        </div>
      </section>

      <Diagnostics />
      <SelectedInstrument />
    </aside>
  )
}

function MetricsStrip() {
  const { metrics, longAnimationFramesSupported } = useTradingShellState(
    (state) => ({
      metrics: state.metrics,
      longAnimationFramesSupported: state.longAnimationFramesSupported,
    }),
    { compare: shallow },
  )
  return (
    <section className="metrics-strip" aria-label="Live performance metrics">
      <article>
        <span>WORKER SAMPLES</span>
        <strong data-testid="actual-rate">
          {formatRate(metrics.actualTicksPerSecond)}
        </strong>
        <small>generated samples/s</small>
      </article>
      <article>
        <span>ROW UPDATES</span>
        <strong data-testid="row-update-rate">
          {formatRate(metrics.rowUpdatesPerSecond)}
        </strong>
        <small>unique rows applied/s</small>
      </article>
      <article>
        <span>MESSAGES</span>
        <strong data-testid="message-rate">
          {metrics.workerMessagesPerSecond.toFixed(1)}
        </strong>
        <small>worker messages/s</small>
      </article>
      <article>
        <span>STATE APPLIES</span>
        <strong data-testid="state-apply-rate">
          {metrics.stateApplicationsPerSecond.toFixed(1)}
        </strong>
        <small>quote snapshots/s</small>
      </article>
      <article>
        <span>TABLE COMMITS</span>
        <strong data-testid="table-render-rate">
          {metrics.tableRendersPerSecond.toFixed(1)}
        </strong>
        <small>completed renders/s</small>
      </article>
      <article>
        <span>AVG RENDER</span>
        <strong>{formatMs(metrics.averageRenderMs)}</strong>
        <small>mutation → render</small>
      </article>
      <article>
        <span>P95 RENDER</span>
        <strong>{formatMs(metrics.p95RenderMs)}</strong>
        <small>max {formatMs(metrics.maxRenderMs)}</small>
      </article>
      <article>
        <span>LONG FRAMES</span>
        {longAnimationFramesSupported ? (
          <>
            <strong
              data-testid="long-frame-count"
              className={metrics.longAnimationFrames > 0 ? 'metric-alert' : ''}
            >
              {metrics.longAnimationFrames}
            </strong>
            <small>worst {formatMs(metrics.worstLongAnimationFrameMs)}</small>
          </>
        ) : (
          <>
            <strong data-testid="long-frame-count">N/A</strong>
            <small>unsupported</small>
          </>
        )}
      </article>
    </section>
  )
}

function Diagnostics() {
  const {
    metrics,
    mountedCells,
    liveComponents,
    longAnimationFramesSupported,
  } = useTradingShellState(
    (state) => ({
      metrics: state.metrics,
      mountedCells: state.mountedCells,
      liveComponents: state.liveComponents,
      longAnimationFramesSupported: state.longAnimationFramesSupported,
    }),
    { compare: shallow },
  )
  return (
    <section
      className="config-section diagnostics"
      aria-labelledby="diagnostics"
    >
      <h2 id="diagnostics">DIAGNOSTICS</h2>
      <dl>
        <div>
          <dt>Mounted cells</dt>
          <dd>{formatInteger(mountedCells)}</dd>
        </div>
        <div>
          <dt>Live components</dt>
          <dd>{formatInteger(liveComponents)}</dd>
        </div>
        <div>
          <dt>Created / destroyed</dt>
          <dd>
            {formatInteger(metrics.componentsCreated)} /{' '}
            {formatInteger(metrics.componentsDestroyed)}
          </dd>
        </div>
        <div>
          <dt>Renderer callbacks / s</dt>
          <dd data-testid="cell-render-rate">
            {formatRate(metrics.cellRendererCallsPerSecond)}
          </dd>
        </div>
        <div>
          <dt>Component executions / s</dt>
          <dd data-testid="component-render-rate">
            {formatRate(metrics.componentRenderCallsPerSecond)}
          </dd>
        </div>
        <div>
          <dt>Executions by component / s</dt>
          <dd data-testid="component-render-breakdown">
            {formatInvocationRates(metrics.componentRenderRates)}
          </dd>
        </div>
        <div>
          <dt>Callbacks by column / s</dt>
          <dd data-testid="cell-render-breakdown">
            {formatInvocationRates(metrics.cellRendererRates)}
          </dd>
        </div>
        <div>
          <dt>DOM mutation records / s</dt>
          <dd data-testid="dom-mutation-rate">
            {formatRate(metrics.domMutationsPerSecond)}
          </dd>
        </div>
        <div>
          <dt>Core row model calls / s</dt>
          <dd data-testid="row-model-call-rate">
            {metrics.rowModelCallsPerSecond.toFixed(1)}
          </dd>
        </div>
        <div>
          <dt>Core row model avg / max</dt>
          <dd data-testid="row-model-duration">
            {formatMs(metrics.rowModelAverageMs)} /{' '}
            {formatMs(metrics.rowModelMaxMs)}
          </dd>
        </div>
        <div>
          <dt>Visible rows</dt>
          <dd data-testid="visible-row-count">
            {formatInteger(metrics.visibleRows)}
          </dd>
        </div>
        <div>
          <dt>Worker messages</dt>
          <dd data-testid="worker-messages">
            {formatInteger(metrics.workerMessages)}
          </dd>
        </div>
        <div>
          <dt>Worker-coalesced updates / s</dt>
          <dd data-testid="superseded-update-rate">
            {formatRate(metrics.supersededUpdatesPerSecond)}
          </dd>
        </div>
        <div>
          <dt>Last message samples / updated rows</dt>
          <dd>
            {formatInteger(metrics.lastBatchSize)} /{' '}
            {formatInteger(metrics.lastUpdateCount)}
          </dd>
        </div>
        <div>
          <dt>Renders &gt; 16.7 ms</dt>
          <dd>{metrics.slowRenders}</dd>
        </div>
        <div>
          <dt>Long animation frames</dt>
          <dd>
            {longAnimationFramesSupported
              ? formatInteger(metrics.longAnimationFrames)
              : 'Unsupported'}
          </dd>
        </div>
        <div>
          <dt>JS heap</dt>
          <dd>
            {metrics.heapMb === null
              ? 'N/A'
              : `${metrics.heapMb.toFixed(1)} MB`}
          </dd>
        </div>
      </dl>
    </section>
  )
}

function SelectedInstrument() {
  const controller = useTradingShellController()
  const feed = useMarketFeedController()
  const selectedSymbol = useSelector(controller.renderAtoms.selectedSymbol)
  const quotes = useSelector(feed.quotes)
  const selectedQuote = feed.getQuoteBySymbol(quotes, selectedSymbol)
  return (
    <section
      className="config-section selected-instrument"
      data-testid="selected-instrument"
    >
      <h2>SELECTED INSTRUMENT</h2>
      {selectedQuote ? (
        <>
          <div className="selection">
            <div>
              <strong>{selectedQuote.symbol}</strong>
              <span>{selectedQuote.company}</span>
            </div>
            <small>{selectedQuote.venue}</small>
          </div>
          <dl>
            <div>
              <dt>Last</dt>
              <dd>{selectedQuote.price.toFixed(2)}</dd>
            </div>
            <div>
              <dt>Bid / ask</dt>
              <dd>
                {selectedQuote.bid.toFixed(2)} / {selectedQuote.ask.toFixed(2)}
              </dd>
            </div>
          </dl>
        </>
      ) : (
        <p>
          Click or begin a cell selection in any row to inspect its instrument.
        </p>
      )}
    </section>
  )
}

function formatInteger(value: number): string {
  return integerFormatter.format(value)
}

function formatRate(value: number): string {
  return rateFormatter.format(value)
}

function formatMs(value: number): string {
  return `${value.toFixed(2)} ms`
}

function formatInvocationRates(
  rates: FeedMetrics['componentRenderRates'],
): string {
  const activeRates = rates
    .filter((rate) => rate.callsPerSecond > 0)
    .sort((left, right) => right.callsPerSecond - left.callsPerSecond)
  return activeRates.length === 0
    ? 'No calls in sample'
    : activeRates
        .map((rate) => `${rate.name} ${formatRate(rate.callsPerSecond)}`)
        .join(' · ')
}

// examples/vue/realtime-trading/src/shell/TradingShell.tsx
import { computed, defineComponent, ref } from 'vue'
import { useSelector } from '@tanstack/vue-store'
import {
  feedSampleRateAt,
  feedSampleRateIndex,
  feedSampleRateOptions,
} from '../feed/feed-sample-rates'
import {
  FORCED_VIRTUALIZATION_ROW_COUNT,
  resolveVirtualScrollMode,
} from '../table/trading-row-virtualizer'
import {
  useMarketFeedController,
  useTradingShellController,
  useTradingShellState,
} from './trading-shell-context'
import { configuratorOptions } from './configurator-options'
import type { FeedMetrics } from '../benchmark/benchmark-monitor'

const integerFormatter = new Intl.NumberFormat('en-US', {
  maximumFractionDigits: 0,
})
const rateFormatter = new Intl.NumberFormat('en-US', {
  notation: 'compact',
  maximumFractionDigits: 1,
})

export const TradingShell = defineComponent({
  name: 'TradingShell',
  setup(_, { slots }) {
    const sidebarOpen = ref(true)
    return () => (
      <main
        class={[
          'trading-terminal',
          !sidebarOpen.value && 'is-sidebar-collapsed',
        ]}
      >
        <div class="shell-header">
          <AppHeader
            sidebarOpen={sidebarOpen.value}
            onSidebarToggle={() => {
              sidebarOpen.value = !sidebarOpen.value
            }}
          />
          {import.meta.env.DEV && (
            <aside class="development-warning">
              DEV BUILD — use the production build before recording results.
            </aside>
          )}
        </div>
        <section class="market-panel" aria-label="Live synthetic quotes">
          <MetricsStrip />
          {slots.default?.()}
        </section>
        <MarketStatusbar />
        <div class="sidebar-slot">{sidebarOpen.value && <Configurator />}</div>
      </main>
    )
  },
})

const AppHeader = defineComponent({
  name: 'AppHeader',
  props: {
    sidebarOpen: { type: Boolean, required: true },
    onSidebarToggle: { type: Function, required: true },
  },
  setup(props) {
    const feed = useMarketFeedController()
    const workerReady = useSelector(feed.workerReady)
    const running = useSelector(feed.running)
    return () => (
      <header class="app-bar">
        <div class="brand">
          <strong>MARKET MONITOR</strong>
        </div>
        <div class="header-actions">
          <span
            class={[
              'feed-status',
              workerReady.value && running.value && 'is-running',
            ]}
            data-testid="feed-status"
          >
            <span class="status-dot" aria-hidden="true" />
            {!workerReady.value
              ? 'FEED CONNECTING'
              : running.value
                ? 'FEED LIVE'
                : 'FEED PAUSED'}
          </span>
          <button
            class="sidebar-toggle"
            type="button"
            aria-expanded={props.sidebarOpen}
            aria-controls="benchmark-configurator"
            aria-label={
              props.sidebarOpen ? 'Close configurator' : 'Open configurator'
            }
            onClick={() => (props.onSidebarToggle as () => void)()}
          >
            <svg viewBox="0 0 20 20" aria-hidden="true">
              <rect x="2.5" y="3" width="15" height="14" rx="1.5" />
              <path d="M12.5 3v14" />
            </svg>
          </button>
        </div>
      </header>
    )
  },
})

const MetricsStrip = defineComponent({
  name: 'MetricsStrip',
  setup() {
    const state = useTradingShellState((benchmark) => ({
      metrics: benchmark.metrics,
      longAnimationFramesSupported: benchmark.longAnimationFramesSupported,
    }))
    return () => {
      const metrics = state.value.metrics
      return (
        <section class="metrics-strip" aria-label="Live performance metrics">
          <Metric
            label="WORKER SAMPLES"
            value={formatRate(metrics.actualTicksPerSecond)}
            detail="generated samples/s"
            testId="actual-rate"
          />
          <Metric
            label="ROW UPDATES"
            value={formatRate(metrics.rowUpdatesPerSecond)}
            detail="unique rows applied/s"
            testId="row-update-rate"
          />
          <Metric
            label="MESSAGES"
            value={metrics.workerMessagesPerSecond.toFixed(1)}
            detail="worker messages/s"
            testId="message-rate"
          />
          <Metric
            label="STATE APPLIES"
            value={metrics.stateApplicationsPerSecond.toFixed(1)}
            detail="quote snapshots/s"
            testId="state-apply-rate"
          />
          <Metric
            label="TABLE COMMITS"
            value={metrics.tableRendersPerSecond.toFixed(1)}
            detail="completed renders/s"
            testId="table-render-rate"
          />
          <Metric
            label="AVG RENDER"
            value={formatMs(metrics.averageRenderMs)}
            detail="mutation → render"
          />
          <Metric
            label="P95 RENDER"
            value={formatMs(metrics.p95RenderMs)}
            detail={`max ${formatMs(metrics.maxRenderMs)}`}
          />
          <Metric
            label="LONG FRAMES"
            value={
              state.value.longAnimationFramesSupported
                ? String(metrics.longAnimationFrames)
                : 'N/A'
            }
            detail={
              state.value.longAnimationFramesSupported
                ? `worst ${formatMs(metrics.worstLongAnimationFrameMs)}`
                : 'unsupported'
            }
            testId="long-frame-count"
          />
        </section>
      )
    }
  },
})

const Metric = defineComponent({
  name: 'Metric',
  props: {
    label: { type: String, required: true },
    value: { type: String, required: true },
    detail: { type: String, required: true },
    testId: String,
  },
  setup(props) {
    return () => (
      <article>
        <span>{props.label}</span>
        <strong data-testid={props.testId}>{props.value}</strong>
        <small>{props.detail}</small>
      </article>
    )
  },
})

const MarketStatusbar = defineComponent({
  name: 'MarketStatusbar',
  setup() {
    const state = useTradingShellState((benchmark) => ({
      lastBatchSize: benchmark.metrics.lastBatchSize,
      lastUpdateCount: benchmark.metrics.lastUpdateCount,
      mountedCells: benchmark.mountedCells,
      liveComponents: benchmark.liveComponents,
    }))
    return () => (
      <footer class="market-statusbar">
        <span>
          MESSAGE SAMPLES{' '}
          <strong>{formatInteger(state.value.lastBatchSize)}</strong>
        </span>
        <span>
          ROW UPDATES{' '}
          <strong>{formatInteger(state.value.lastUpdateCount)}</strong>
        </span>
        <span>
          HOSTS <strong>{formatInteger(state.value.mountedCells)}</strong>
        </span>
        <span>
          COMPONENTS{' '}
          <strong>{formatInteger(state.value.liveComponents)}</strong>
        </span>
      </footer>
    )
  },
})

const Configurator = defineComponent({
  name: 'Configurator',
  setup() {
    const controller = useTradingShellController()
    const feed = useMarketFeedController()
    const running = useSelector(feed.running)
    const instrumentCount = useSelector(feed.instrumentCount)
    const targetTicksPerSecond = useSelector(feed.targetTicksPerSecond)
    const publishIntervalMs = useSelector(feed.publishIntervalMs)
    const updateSparklines = useSelector(feed.updateSparklines)
    const sparklineSampleIntervalMs = useSelector(
      feed.sparklineSampleIntervalMs,
    )
    const feedState = computed(() => ({
      running: running.value,
      instrumentCount: instrumentCount.value,
      targetTicksPerSecond: targetTicksPerSecond.value,
      publishIntervalMs: publishIntervalMs.value,
      updateSparklines: updateSparklines.value,
      sparklineSampleIntervalMs: sparklineSampleIntervalMs.value,
    }))
    const benchmarkState = useTradingShellState((state) => state)
    const rendererMode = useSelector(controller.renderAtoms.rendererMode)
    const virtualScrollForced = computed(
      () => feedState.value.instrumentCount >= FORCED_VIRTUALIZATION_ROW_COUNT,
    )
    const virtualScrollMode = computed(() =>
      resolveVirtualScrollMode(
        benchmarkState.value.requestedVirtualScrollMode,
        feedState.value.instrumentCount,
      ),
    )

    return () => (
      <aside
        id="benchmark-configurator"
        class="configurator"
        aria-label="Benchmark configurator"
      >
        <header>
          <span>CONFIGURATOR</span>
          <small>RUN PARAMETERS</small>
        </header>
        <section class="config-section" aria-labelledby="feed-settings">
          <h2 id="feed-settings">FEED</h2>
          <button
            class="primary-action"
            type="button"
            data-testid="feed-toggle"
            onClick={feed.actions.toggle}
          >
            {feedState.value.running ? 'PAUSE FEED' : 'START FEED'}
          </button>
          <label class="field">
            <span>Instruments (rows)</span>
            <select
              data-testid="instrument-count-select"
              value={feedState.value.instrumentCount}
              onChange={(event) => {
                controller.actions.resetViewState()
                feed.actions.setInstrumentCount(numberValue(event))
              }}
            >
              {configuratorOptions.instrumentCounts.map(optionNode)}
            </select>
          </label>
          <label class="field rate-field">
            <span>
              Synthetic quote workload
              <strong data-testid="target-sample-rate">
                {formatRate(feedState.value.targetTicksPerSecond)} samples/s
              </strong>
            </span>
            <input
              data-testid="target-rate-slider"
              type="range"
              min={0}
              max={feedSampleRateOptions.length - 1}
              step={1}
              value={feedSampleRateIndex(feedState.value.targetTicksPerSecond)}
              onChange={(event) =>
                feed.actions.setTargetRate(feedSampleRateAt(numberValue(event)))
              }
            />
            <small>
              Fixed worker-side workload levels. Samples are coalesced; this is
              not the message delivery rate.
            </small>
          </label>
          <label class="field">
            <span>Worker delivery interval</span>
            <select
              data-testid="publish-interval-select"
              value={feedState.value.publishIntervalMs}
              onChange={(event) =>
                feed.actions.setPublishInterval(numberValue(event))
              }
            >
              {configuratorOptions.workerDeliveryIntervals.map(optionNode)}
            </select>
            <small>One coalesced worker message at this target cadence.</small>
          </label>
        </section>
        <section class="config-section" aria-labelledby="render-settings">
          <h2 id="render-settings">RENDER PATH</h2>
          <label class="field" data-testid="virtual-scroll-mode">
            <span>Row rendering</span>
            <select
              data-testid="virtual-scroll-select"
              value={virtualScrollMode.value}
              disabled={virtualScrollForced.value}
              onChange={(event) =>
                controller.actions.setVirtualScrollEnabled(
                  stringValue(event) === 'tanstack',
                )
              }
            >
              {configuratorOptions.rowRenderingModes.map(optionNode)}
            </select>
            <small>
              {virtualScrollForced.value
                ? 'TanStack Virtual is required and locked at 1,500 or more rows.'
                : 'Full DOM is the default below 200 rows; TanStack Virtual is the default from 200 rows and remains selectable.'}
            </small>
          </label>
          <label class="toggle-field">
            <input
              type="checkbox"
              checked={rendererMode.value === 'swap'}
              onChange={(event) =>
                controller.actions.setRendererMode(
                  checkedValue(event) ? 'swap' : 'stable',
                )
              }
            />
            <span>
              Swap Tick component A ↔ B
              <small>destroy and recreate when direction changes</small>
            </span>
          </label>
          <label class="toggle-field">
            <input
              type="checkbox"
              checked={feedState.value.updateSparklines}
              onChange={(event) =>
                feed.actions.setSparklineUpdates(checkedValue(event))
              }
            />
            <span>
              Update intraday charts
              <small>sample rolling prices independently</small>
            </span>
          </label>
          <label class="field">
            <span>Intraday chart sampling</span>
            <select
              data-testid="sparkline-sample-interval-select"
              value={feedState.value.sparklineSampleIntervalMs}
              onChange={(event) =>
                feed.actions.setSparklineSampleInterval(numberValue(event))
              }
            >
              {configuratorOptions.intradaySamplingIntervals.map(optionNode)}
            </select>
          </label>
        </section>
        <section class="config-section" aria-labelledby="stress-actions">
          <h2 id="stress-actions">STRESS ACTIONS</h2>
          <div class="action-grid">
            <button type="button" onClick={feed.actions.runBurst}>
              RUN 25K BURST
            </button>
            <button type="button" onClick={controller.actions.resetMarket}>
              RESET SESSION
            </button>
          </div>
        </section>
        <Diagnostics />
        <SelectedInstrument />
      </aside>
    )
  },
})

const Diagnostics = defineComponent({
  name: 'Diagnostics',
  setup() {
    const state = useTradingShellState((benchmark) => benchmark)
    return () => {
      const { metrics } = state.value
      return (
        <section
          class="config-section diagnostics"
          aria-labelledby="diagnostics"
        >
          <h2 id="diagnostics">DIAGNOSTICS</h2>
          <dl>
            <Diagnostic
              label="Mounted cells"
              value={formatInteger(state.value.mountedCells)}
            />
            <Diagnostic
              label="Live components"
              value={formatInteger(state.value.liveComponents)}
            />
            <Diagnostic
              label="Created / destroyed"
              value={`${formatInteger(metrics.componentsCreated)} / ${formatInteger(metrics.componentsDestroyed)}`}
            />
            <Diagnostic
              label="Renderer callbacks / s"
              value={formatRate(metrics.cellRendererCallsPerSecond)}
              testId="cell-render-rate"
            />
            <Diagnostic
              label="Component executions / s"
              value={formatRate(metrics.componentRenderCallsPerSecond)}
              testId="component-render-rate"
            />
            <Diagnostic
              label="Executions by component / s"
              value={formatInvocationRates(metrics.componentRenderRates)}
              testId="component-render-breakdown"
            />
            <Diagnostic
              label="Callbacks by column / s"
              value={formatInvocationRates(metrics.cellRendererRates)}
              testId="cell-render-breakdown"
            />
            <Diagnostic
              label="DOM mutation records / s"
              value={formatRate(metrics.domMutationsPerSecond)}
              testId="dom-mutation-rate"
            />
            <Diagnostic
              label="Core row model calls / s"
              value={metrics.rowModelCallsPerSecond.toFixed(1)}
              testId="row-model-call-rate"
            />
            <Diagnostic
              label="Core row model avg / max"
              value={`${formatMs(metrics.rowModelAverageMs)} / ${formatMs(metrics.rowModelMaxMs)}`}
              testId="row-model-duration"
            />
            <Diagnostic
              label="Visible rows"
              value={formatInteger(metrics.visibleRows)}
              testId="visible-row-count"
            />
            <Diagnostic
              label="Worker messages"
              value={formatInteger(metrics.workerMessages)}
              testId="worker-messages"
            />
            <Diagnostic
              label="Worker-coalesced updates / s"
              value={formatRate(metrics.supersededUpdatesPerSecond)}
              testId="superseded-update-rate"
            />
            <Diagnostic
              label="Last samples / updated rows"
              value={`${formatInteger(metrics.lastBatchSize)} / ${formatInteger(metrics.lastUpdateCount)}`}
            />
            <Diagnostic
              label="Renders > 16.7 ms"
              value={formatInteger(metrics.slowRenders)}
            />
            <Diagnostic
              label="JS heap"
              value={
                metrics.heapMb === null
                  ? 'N/A'
                  : `${metrics.heapMb.toFixed(1)} MB`
              }
            />
          </dl>
        </section>
      )
    }
  },
})

const Diagnostic = defineComponent({
  name: 'Diagnostic',
  props: {
    label: { type: String, required: true },
    value: { type: String, required: true },
    testId: String,
  },
  setup(props) {
    return () => (
      <div>
        <dt>{props.label}</dt>
        <dd data-testid={props.testId}>{props.value}</dd>
      </div>
    )
  },
})

const SelectedInstrument = defineComponent({
  name: 'SelectedInstrument',
  setup() {
    const controller = useTradingShellController()
    const feed = useMarketFeedController()
    const selectedSymbol = useSelector(controller.renderAtoms.selectedSymbol)
    const quotes = useSelector(feed.quotes)
    const selectedQuote = computed(() =>
      feed.getQuoteBySymbol(quotes.value, selectedSymbol.value),
    )
    return () => (
      <section
        class="config-section selected-instrument"
        data-testid="selected-instrument"
      >
        <h2>SELECTED INSTRUMENT</h2>
        {selectedQuote.value ? (
          <>
            <div class="selection">
              <div>
                <strong>{selectedQuote.value.symbol}</strong>
                <span>{selectedQuote.value.company}</span>
              </div>
              <small>{selectedQuote.value.venue}</small>
            </div>
            <dl>
              <div>
                <dt>Last</dt>
                <dd>{selectedQuote.value.price.toFixed(2)}</dd>
              </div>
              <div>
                <dt>Bid / ask</dt>
                <dd>
                  {selectedQuote.value.bid.toFixed(2)} /{' '}
                  {selectedQuote.value.ask.toFixed(2)}
                </dd>
              </div>
            </dl>
          </>
        ) : (
          <p>
            Click or begin a cell selection in any row to inspect its
            instrument.
          </p>
        )}
      </section>
    )
  },
})

function optionNode(option: {
  readonly label: string
  readonly value: number | string
}) {
  return (
    <option key={option.value} value={option.value}>
      {option.label}
    </option>
  )
}

function stringValue(event: Event): string {
  return (event.target as HTMLInputElement | HTMLSelectElement).value
}

function numberValue(event: Event): number {
  return Number(stringValue(event))
}

function checkedValue(event: Event): boolean {
  return (event.target as HTMLInputElement).checked
}

function formatRate(value: number): string {
  return rateFormatter.format(value)
}

function formatInteger(value: number): string {
  return integerFormatter.format(value)
}

function formatMs(value: number): string {
  return `${value.toFixed(2)} ms`
}

function formatInvocationRates(
  rates: FeedMetrics['cellRendererRates'],
): string {
  const active = rates.filter((entry) => entry.callsPerSecond > 0)
  return active.length === 0
    ? '—'
    : active
        .map((entry) => `${entry.name} ${formatRate(entry.callsPerSecond)}`)
        .join(' · ')
}
