// examples/react/query-router-search-params/src/components/debouncedInput.tsx
import { useEffect, useState } from 'react'
import type { InputHTMLAttributes } from 'react'

export function DebouncedInput({
  value: initialValue,
  onChange,
  debounce = 200,
  ...props
}: {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'>) {
  const [value, setValue] = useState<string | number>(initialValue)

  useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  useEffect(() => {
    const timeout = setTimeout(() => {
      onChange(value)
    }, debounce)

    return () => clearTimeout(timeout)
  }, [value])

  return (
    <input
      {...props}
      value={value ?? ''}
      onChange={(e) => {
        if (e.target.value === '') return setValue('')
        if (props.type === 'number') {
          setValue(e.target.valueAsNumber)
        } else {
          setValue(e.target.value)
        }
      }}
    />
  )
}

// examples/svelte/basic-dynamic-columns/src/DebouncedInput.svelte
<script lang="ts">
  let {
    value,
    onchange,
    debounce = 500,
    ...rest
  }: {
    value: string | number
    onchange: (value: string | number) => void
    debounce?: number
    [key: string]: any
  } = $props()

  let internalValue: string | number = $state('')

  $effect(() => {
    internalValue = value
  })

  $effect(() => {
    const v = internalValue
    const timeout = setTimeout(() => {
      onchange(v)
    }, debounce)
    return () => clearTimeout(timeout)
  })
</script>

<input {...rest} bind:value={internalValue} />
