// examples/svelte/filters-faceted/src/ColumnFilter.svelte
<script lang="ts">
  import DebouncedInput from './DebouncedInput.svelte'
  import type { Person } from './makeData'
  import type { Column, Table } from '@tanstack/svelte-table'

  let {
    column,
    table,
  }: {
    column: Column<any, Person, unknown>
    table: Table<any, Person>
  } = $props()

  const firstValue = $derived(
    table.getPreFilteredRowModel().flatRows[0]?.getValue(column.id),
  )

  const isNumber = $derived(typeof firstValue === 'number')

  function getSortedUniqueValues(): Array<string> {
    if (isNumber) return []
    return Array.from(column.getFacetedUniqueValues().keys()).sort() as Array<string>
  }
</script>

{#if isNumber}
  <div>
    <div class="flex space-x-2">
      <DebouncedInput
        type="number"
        min={Number(column.getFacetedMinMaxValues()?.[0] ?? '')}
        max={Number(column.getFacetedMinMaxValues()?.[1] ?? '')}
        value={(column.getFilterValue() as [number, number] | undefined)?.[0] ?? ''}
        onchange={(value) =>
          column.setFilterValue((old: [number, number]) => [
            value,
            old?.[1],
          ])
        }
        debounce={500}
        placeholder={`Min ${column.getFacetedMinMaxValues()?.[0] ? `(${column.getFacetedMinMaxValues()?.[0]})` : ''}`}
        class="w-24 border shadow rounded"
      />
      <DebouncedInput
        type="number"
        min={Number(column.getFacetedMinMaxValues()?.[0] ?? '')}
        max={Number(column.getFacetedMinMaxValues()?.[1] ?? '')}
        value={(column.getFilterValue() as [number, number] | undefined)?.[1] ?? ''}
        onchange={(value) =>
          column.setFilterValue((old: [number, number]) => [
            old?.[0],
            value,
          ])
        }
        debounce={500}
        placeholder={`Max ${column.getFacetedMinMaxValues()?.[1] ? `(${column.getFacetedMinMaxValues()?.[1]})` : ''}`}
        class="w-24 border shadow rounded"
      />
    </div>
  </div>
{:else}
  <div>
    <datalist id="{column.id}list">
      {#each getSortedUniqueValues().slice(0, 5000) as value}
        <option value={value}></option>
      {/each}
    </datalist>
    <DebouncedInput
      type="text"
      value={(column.getFilterValue() ?? '') as string}
      onchange={(value) => column.setFilterValue(value)}
      debounce={500}
      placeholder={`Search... (${column.getFacetedUniqueValues().size})`}
      class="w-36 border shadow rounded"
      list="{column.id}list"
    />
  </div>
{/if}

// examples/solid/filters/src/ColumnFilter.tsx
import { debounce } from '@solid-primitives/scheduled'
import { For, Show, createMemo } from 'solid-js'
import type { Column, Table } from '@tanstack/solid-table'

function ColumnFilter(props: {
  column: Column<any, unknown>
  table: Table<any>
}) {
  const firstValue = props.table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(props.column.id)

  const columnFilterValue = () => props.column.getFilterValue()

  const sortedUniqueValues = createMemo(() =>
    typeof firstValue === 'number'
      ? []
      : Array.from(props.column.getFacetedUniqueValues().keys()).sort(),
  )

  return (
    <Show
      when={typeof firstValue === 'number'}
      fallback={
        <div>
          <datalist id={`${props.column.id}list`}>
            <For each={sortedUniqueValues().slice(0, 5000)}>
              {(value: string) => <option value={value} />}
            </For>
          </datalist>
          <input
            type="text"
            value={(columnFilterValue() ?? '') as string}
            onInput={debounce(
              (e) => props.column.setFilterValue(e.target.value),
              500,
            )}
            placeholder={`Search... (${props.column.getFacetedUniqueValues().size})`}
            class="w-36 border shadow rounded"
            list={`${props.column.id}list`}
          />
        </div>
      }
    >
      <div>
        <div class="flex space-x-2">
          <input
            type="number"
            min={Number(props.column.getFacetedMinMaxValues()?.[0] ?? '')}
            max={Number(props.column.getFacetedMinMaxValues()?.[1] ?? '')}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[0] ?? ''
            }
            onInput={debounce(
              (e) =>
                props.column.setFilterValue((old: [number, number]) => [
                  e.target.value,
                  old[1],
                ]),
              500,
            )}
            placeholder={`Min ${
              props.column.getFacetedMinMaxValues()?.[0]
                ? `(${props.column.getFacetedMinMaxValues()?.[0]})`
                : ''
            }`}
            class="w-24 border shadow rounded"
          />
          <input
            type="number"
            min={Number(props.column.getFacetedMinMaxValues()?.[0] ?? '')}
            max={Number(props.column.getFacetedMinMaxValues()?.[1] ?? '')}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[1] ?? ''
            }
            onInput={debounce(
              (e) =>
                props.column.setFilterValue((old: [number, number]) => [
                  old[0],
                  e.target.value,
                ]),
              500,
            )}
            placeholder={`Max ${
              props.column.getFacetedMinMaxValues()?.[1]
                ? `(${props.column.getFacetedMinMaxValues()?.[1]})`
                : ''
            }`}
            class="w-24 border shadow rounded"
          />
        </div>
      </div>
    </Show>
  )
}

export default ColumnFilter
