// examples/react/kitchen-sink/src/components/DebouncedInput.tsx
import React from 'react'

type Props = {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange'>

export const DebouncedInput: React.FC<Props> = ({
  value: initialValue,
  onChange,
  debounce = 500,
  ...props
}) => {
  const [value, setValue] = React.useState<number | string>(initialValue)

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) =>
    setValue(event.target.value)

  React.useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  React.useEffect(() => {
    const timeout = setTimeout(() => {
      onChange(value)
    }, debounce)

    return () => clearTimeout(timeout)
  }, [value])

  return <input {...props} value={value} onChange={handleInputChange} />
}

export default DebouncedInput

// examples/solid/with-tanstack-router/src/components/debouncedInput.tsx
import { createEffect, createSignal, onCleanup } from 'solid-js'

type DebouncedInputProps = {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
  class?: string
  type?: string
  placeholder?: string
}

export function DebouncedInput(props: DebouncedInputProps) {
  const [value, setValue] = createSignal<string | number>(props.value)

  createEffect(() => {
    setValue(() => props.value)
  })

  createEffect(() => {
    const currentValue = value()
    const timeout = setTimeout(() => {
      props.onChange(currentValue)
    }, props.debounce ?? 200)
    onCleanup(() => clearTimeout(timeout))
  })

  return (
    <input
      type={props.type ?? 'text'}
      value={value()}
      onInput={(e) => {
        if (e.currentTarget.value === '') {
          setValue('')
        } else if (props.type === 'number') {
          setValue(e.currentTarget.valueAsNumber)
        } else {
          setValue(e.currentTarget.value)
        }
      }}
      placeholder={props.placeholder}
      class={props.class}
    />
  )
}
