// examples/preact/composable-tables/src/components/cell-components.tsx
/**
 * Cell-level components that use useCellContext
 *
 * These components can be used via the pre-bound cellComponents
 * in AppCell children, e.g., <cell.TextCell />
 */
import { useCellContext } from '../hooks/table'
import { IndeterminateCheckbox } from './indeterminate-checkbox'

/**
 * Row-selection checkbox cell - toggles selection for the current row.
 *
 * Unlike React (which needs a `Subscribe` boundary to work around React
 * Compiler memoization), Preact re-renders this cell when selection state
 * changes via the parent table's subscription, so reading `row.getIsSelected()`
 * directly is enough.
 */
export function SelectCell() {
  const cell = useCellContext()
  const row = cell.row

  return (
    <IndeterminateCheckbox
      checked={row.getIsSelected()}
      disabled={!row.getCanSelect()}
      indeterminate={row.getIsSomeSelected()}
      onClick={row.getToggleSelectedHandler()}
    />
  )
}

/**
 * Generic text cell renderer
 */
export function TextCell() {
  const cell = useCellContext<string>()
  return <span>{cell.getValue()}</span>
}

/**
 * Number cell with locale formatting
 */
export function NumberCell() {
  const cell = useCellContext<number>()
  return <span>{cell.getValue().toLocaleString()}</span>
}

/**
 * Status badge cell for status column
 */
export function StatusCell() {
  const cell = useCellContext<'relationship' | 'complicated' | 'single'>()
  const status = cell.getValue()
  return <span className={`status-badge ${status}`}>{status}</span>
}

/**
 * Progress bar cell
 */
export function ProgressCell() {
  const cell = useCellContext<number>()
  const progress = cell.getValue()
  return (
    <div className="progress-bar">
      <div className="progress-bar-fill" style={{ width: `${progress}%` }} />
    </div>
  )
}

/**
 * Row actions cell - actions for the current row
 */
export function RowActionsCell() {
  const cell = useCellContext()
  const row = cell.row

  return (
    <div className="row-actions">
      <button
        onClick={() =>
          alert(`View: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="View"
      >
        👁️
      </button>
      <button
        onClick={() =>
          alert(`Edit: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="Edit"
      >
        ✏️
      </button>
      <button
        onClick={() =>
          alert(`Delete: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="Delete"
      >
        🗑️
      </button>
    </div>
  )
}

/**
 * Price cell with currency formatting
 */
export function PriceCell() {
  const cell = useCellContext<number>()
  return (
    <span className="price">
      $
      {cell.getValue().toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })}
    </span>
  )
}

/**
 * Category badge cell
 */
export function CategoryCell() {
  const cell = useCellContext<'electronics' | 'clothing' | 'food' | 'books'>()
  const category = cell.getValue()
  return <span className={`category-badge ${category}`}>{category}</span>
}

// examples/angular/composable-tables/src/app/components/cell-components.ts
// /**
//  * Cell-level components that use useCellContext
//  *
//  * These components can be used via the pre-bound cellComponents
//  * in AppCell children, e.g., <cell.TextCell />
//  */
// import { useCellContext } from '../hooks/table'
//

import { Component, computed } from '@angular/core'
import { injectFlexRenderContext } from '@tanstack/angular-table'
import { CurrencyPipe } from '@angular/common'
import { injectTableCellContext } from '../table'
import type { CellContext, TableFeatures } from '@tanstack/angular-table'

@Component({
  selector: 'span',
  host: {
    'tanstack-table-text-cell': '',
  },
  template: ` {{ cell.getValue() }} `,
})
export class TextCell {
  readonly cell =
    injectFlexRenderContext<CellContext<TableFeatures, any, string>>()
}

@Component({
  selector: 'span',
  host: {
    'tanstack-table-number-cell': '',
  },
  template: ` {{ cell.getValue().toLocaleString() }} `,
})
export class NumberCell {
  readonly cell =
    injectFlexRenderContext<CellContext<TableFeatures, any, number>>()
}

@Component({
  selector: 'span',
  host: {
    'tanstack-table-status-cell': '',
    '[class.status-badge]': 'true',
    '[class]': 'cell().getValue()',
  },
  template: ` {{ cell().getValue() }} `,
})
export class StatusCell {
  readonly cell = injectTableCellContext<
    'relationship' | 'complicated' | 'single'
  >()
}

@Component({
  selector: 'table-progress-cell',
  template: `
    <div class="progress-bar"></div>
    <div class="progress-bar-fill" [style.width.%]="progress()"></div>
  `,
})
export class ProgressCell {
  readonly cell = injectTableCellContext<number>()

  readonly progress = computed(() => this.cell().getValue())
}

@Component({
  selector: 'table-progress-cell',
  template: `
    <div class="row-actions">
      <button (click)="view()" title="View">👁️</button>
      <button (click)="edit()" title="Edit">️️✏️</button>
      <button (click)="delete()" title="Delete">🗑️</button>
    </div>
  `,
})
export class RowActionsCell {
  readonly cell = injectTableCellContext<number>()

  view() {
    alert(
      `View: ${this.cell().row.original.firstName} ${this.cell().row.original.lastName}`,
    )
  }

  edit() {
    alert(
      `Edit: ${this.cell().row.original.firstName} ${this.cell().row.original.lastName}`,
    )
  }

  delete() {
    alert(
      `Delete: ${this.cell().row.original.firstName} ${this.cell().row.original.lastName}`,
    )
  }
}

@Component({
  selector: 'table-price-cell',
  template: ` <span class="price"> {{ price() | currency }} </span> `,
  imports: [CurrencyPipe],
})
export class PriceCell {
  readonly cell = injectTableCellContext<number>()

  readonly price = computed(() =>
    this.cell().getValue().toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    }),
  )
}

@Component({
  selector: 'span',
  host: {
    'tanstack-table-category-cell': '',
    '[class.category-badge]': 'true',
    '[class]': 'cell().getValue()',
  },
  template: ` {{ cell().getValue() }} `,
})
export class CategoryCell {
  readonly cell = injectTableCellContext<
    'electronics' | 'clothing' | 'food' | 'books'
  >()
}
