// examples/solid/filters/src/ColumnFilter.tsx
import { createDebouncer } from '@tanstack/solid-pacer/debouncer'
import { Show } from 'solid-js'
import type { Person } from './makeData'
import type { _features } from './App'
import type { Column, Table } from '@tanstack/solid-table'

function ColumnFilter(props: {
  column: Column<typeof _features, Person, unknown>
  table: Table<typeof _features, Person>
}) {
  const firstValue = props.table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(props.column.id)

  const columnFilterValue = () => props.column.getFilterValue()
  const columnFilterDebouncer = createDebouncer(
    (value: unknown) => props.column.setFilterValue(value),
    { wait: 500 },
  )

  return (
    <Show
      when={typeof firstValue === 'number'}
      fallback={
        <div>
          <input
            type="text"
            value={(columnFilterValue() ?? '') as string}
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(e.currentTarget.value)
            }
            placeholder={`Search...`}
            class="filter-select"
            list={`${props.column.id}list`}
          />
        </div>
      }
    >
      <div>
        <div class="filter-row">
          <input
            type="number"
            min={0}
            max={100}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[0] ?? ''
            }
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(
                (old: [number, number] | undefined) => [
                  e.currentTarget.value,
                  old?.[1] ?? '',
                ],
              )
            }
            placeholder={`Min`}
            class="filter-input"
          />
          <input
            type="number"
            min={0}
            max={100}
            value={
              (columnFilterValue() as [number, number] | undefined)?.[1] ?? ''
            }
            onInput={(e) =>
              columnFilterDebouncer.maybeExecute(
                (old: [number, number] | undefined) => [
                  old?.[0] ?? '',
                  e.currentTarget.value,
                ],
              )
            }
            placeholder={`Max`}
            class="filter-input"
          />
        </div>
      </div>
    </Show>
  )
}

export default ColumnFilter

// examples/svelte/filtering/src/ColumnFilter.svelte
<script lang="ts">
  import DebouncedInput from './DebouncedInput.svelte'
  import type { Person } from './makeData'
  import type { Column, Table } from '@tanstack/svelte-table'

  let {
    column,
    table,
  }: {
    column: Column<any, Person, unknown>
    table: Table<any, Person>
  } = $props()

  const firstValue = $derived(
    table.getPreFilteredRowModel().flatRows[0]?.getValue(column.id),
  )

  const isNumber = $derived(typeof firstValue === 'number')
</script>

{#if isNumber
}
  <div>
    <div class="filter-row">
      <DebouncedInput
        type="number"
        min={0}
        max={100}
        value={(column.getFilterValue() as [number, number] | undefined)?.[0] ?? ''}
        onchange={(value) =>
          column.setFilterValue((old: [number, number] | undefined) => [
            value,
            old?.[1] ?? '',
          ])
        }
        debounce={500}
        placeholder="Min"
        class="filter-input"
      />
      <DebouncedInput
        type="number"
        min={0}
        max={100}
        value={(column.getFilterValue() as [number, number] | undefined)?.[1] ?? ''}
        onchange={(value) =>
          column.setFilterValue((old: [number, number] | undefined) => [
            old?.[0] ?? '',
            value,
          ])
        }
        debounce={500}
        placeholder="Max"
        class="filter-input"
      />
    </div>
  </div>
{:else}
  <div>
    <DebouncedInput
      type="text"
      value={(column.getFilterValue() ?? '') as string}
      onchange={(value) => column.setFilterValue(value)}
      debounce={500}
      placeholder="Search..."
      class="filter-select"
      list="{column.id}list"
    />
  </div>
{/if}
