// examples/vue/filters/src/Filter.vue
<script lang="ts" setup>
import type { Column, Table } from '@tanstack/vue-table'
import { computed, PropType } from 'vue'
import DebouncedInput from './DebouncedInput.vue'
const props = defineProps({
  column: {
    type: Object as PropType<Column<any, unknown>>,
    required: true,
  },
  table: {
    type: Object as PropType<Table<any>>,
    required: true,
  },
})
const firstValue = computed(
  () =>
    props.table.getPreFilteredRowModel().flatRows[0]?.getValue(props.column.id)
)
const columnFilterValue = computed(() => props.column.getFilterValue())
const sortedUniqueValues = computed(() =>
  typeof firstValue.value === 'number'
    ? []
    : Array.from(props.column.getFacetedUniqueValues().keys()).sort()
)
</script>

<template>
  <div v-if="typeof firstValue === 'number'">
    <div class="flex space-x-2">
      <DebouncedInput
        type="number"
        :min="Number(column.getFacetedMinMaxValues()?.[0] ?? '')"
        :max="Number(column.getFacetedMinMaxValues()?.[1] ?? '')"
        :modelValue="(columnFilterValue as [number, number])?.[0] ?? ''"
        @update:modelValue="
          value =>
            column.setFilterValue((old: [number, number]) => [value, old?.[1]])
        "
        :placeholder="`Min ${
          column.getFacetedMinMaxValues()?.[0]
            ? `(${column.getFacetedMinMaxValues()?.[0]})`
            : ''
        }`"
        class="w-24 border shadow rounded"
      />
      <DebouncedInput
        type="number"
        :min="Number(column.getFacetedMinMaxValues()?.[0] ?? '')"
        :max="Number(column.getFacetedMinMaxValues()?.[1] ?? '')"
        :modelValue="(columnFilterValue as [number, number])?.[1] ?? ''"
        @update:modelValue="
          value =>
            column.setFilterValue((old: [number, number]) => [old?.[0], value])
        "
        :placeholder="`Max ${
          column.getFacetedMinMaxValues()?.[1]
            ? `(${column.getFacetedMinMaxValues()?.[1]})`
            : ''
        }`"
        class="w-24 border shadow rounded"
      />
    </div>
    <div class="h-1" />
  </div>
  <div v-else>
    <datalist :id="column.id + 'list'">
      <option
        v-for="value in sortedUniqueValues.slice(0, 5000)"
        :key="value"
        :value="value"
      />
    </datalist>
    <DebouncedInput
      type="text"
      :modelValue="(columnFilterValue ?? '') as string"
      @update:modelValue="value => column.setFilterValue(value)"
      :placeholder="`Search... (${column.getFacetedUniqueValues().size})`"
      class="w-36 border shadow rounded"
      :list="column.id + 'list'"
    />
    <div class="h-1" />
  </div>
</template>

// examples/angular/row-selection-signal/src/app/filter.ts
import { Component, input } from '@angular/core'
import type { OnInit } from '@angular/core'
import type { Column, RowData, Table } from '@tanstack/angular-table'

@Component({
  selector: 'app-table-filter',
  template: ` @if (columnType) {
    @if (columnType == 'number') {
      <div class="flex space-x-2">
        <input
          #min
          type="number"
          class="w-24 border shadow rounded"
          placeholder="Min"
          [value]="getMinValue()"
          (input)="updateMinFilterValue(min.value)"
        />
        <input
          #max
          type="number"
          class="w-36 border shadow rounded"
          placeholder="max"
          [value]="getMaxValue()"
          (input)="updateMaxFilterValue(max.value)"
        />
      </div>
    } @else {
      <input
        #search
        type="text"
        class="w-36 border shadow rounded"
        placeholder="Search..."
        [value]="column().getFilterValue() ?? ''"
        (input)="column().setFilterValue(search.value)"
      />
    }
  }`,
})
export class FilterComponent<T extends RowData> implements OnInit {
  column = input.required<Column<any, any>>()

  table = input.required<Table<any, T>>()

  columnType!: string

  ngOnInit() {
    this.columnType = typeof this.table()
      .getPreFilteredRowModel()
      .flatRows[0]?.getValue(this.column().id)
  }

  getMinValue() {
    const minValue = this.column().getFilterValue() as any

    return (minValue?.[0] ?? '') as string
  }

  getMaxValue() {
    const maxValue = this.column().getFilterValue() as any
    return (maxValue?.[1] ?? '') as string
  }

  updateMinFilterValue(newValue: string): void {
    this.column().setFilterValue((old: any) => {
      return [newValue, old?.[1]]
    })
  }

  updateMaxFilterValue(newValue: string): void {
    this.column().setFilterValue((old: any) => [old?.[0], newValue])
  }
}
