// examples/lit/composable-tables/src/components/cell-components.ts
import { html } from 'lit'
import type { Cell } from '@tanstack/lit-table'

// Cell components are plain functions that receive the cell instance as their
// first argument (bound automatically by AppCell in createTableHook).
// In column definitions, call them as: cell: ({ cell }) => cell.TextCell()

export function TextCell(cell: Cell<any, any, string>) {
  return html`<span>${String(cell.getValue() ?? '')}</span>`
}

export function NumberCell(cell: Cell<any, any, number>) {
  return html`<span>${Number(cell.getValue() ?? 0).toLocaleString()}</span>`
}

export function StatusCell(cell: Cell<any, any, string>) {
  const status = String(cell.getValue() ?? '')
  const statusClass =
    status === 'single'
      ? 'single'
      : status === 'complicated'
        ? 'complicated'
        : 'relationship'
  return html`<span class="status-badge ${statusClass}">${status}</span>`
}

export function ProgressCell(cell: Cell<any, any, number>) {
  const value = Number(cell.getValue() ?? 0)
  return html`
    <div class="progress-bar">
      <div class="progress-bar-fill" style="width: ${value}%"></div>
    </div>
  `
}

export function RowActionsCell(cell: Cell<any, any, any>) {
  const row = cell.row.original as {
    firstName?: string
    name?: string
  }
  const name = row.firstName ?? row.name ?? 'row'
  return html`
    <div class="row-actions">
      <button @click=${() => alert(`View ${name}`)}>View</button>
      <button @click=${() => alert(`Edit ${name}`)}>Edit</button>
      <button @click=${() => alert(`Delete ${name}`)}>Delete</button>
    </div>
  `
}

export function PriceCell(cell: Cell<any, any, number>) {
  const value = Number(cell.getValue() ?? 0)
  return html`<span class="price"
    >$${value.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    })}</span
  >`
}

export function CategoryCell(cell: Cell<any, any, string>) {
  const category = String(cell.getValue() ?? '')
  return html`<span class="category-badge ${category}">${category}</span>`
}

// examples/react/composable-tables/src/components/cell-components.tsx
/**
 * Cell-level components that use useCellContext
 *
 * These components can be used via the pre-bound cellComponents
 * in AppCell children, e.g., <cell.TextCell />
 */
import { useCellContext } from '../hooks/table'

/**
 * Generic text cell renderer
 */
export function TextCell() {
  const cell = useCellContext<string>()
  return <span>{cell.getValue()}</span>
}

/**
 * Number cell with locale formatting
 */
export function NumberCell() {
  const cell = useCellContext<number>()
  return <span>{cell.getValue().toLocaleString()}</span>
}

/**
 * Status badge cell for status column
 */
export function StatusCell() {
  const cell = useCellContext<'relationship' | 'complicated' | 'single'>()
  const status = cell.getValue()
  return <span className={`status-badge ${status}`}>{status}</span>
}

/**
 * Progress bar cell
 */
export function ProgressCell() {
  const cell = useCellContext<number>()
  const progress = cell.getValue()
  return (
    <div className="progress-bar">
      <div className="progress-bar-fill" style={{ width: `${progress}%` }} />
    </div>
  )
}

/**
 * Row actions cell - actions for the current row
 */
export function RowActionsCell() {
  const cell = useCellContext()
  const row = cell.row

  return (
    <div className="row-actions">
      <button
        onClick={() =>
          alert(`View: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="View"
      >
        👁️
      </button>
      <button
        onClick={() =>
          alert(`Edit: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="Edit"
      >
        ✏️
      </button>
      <button
        onClick={() =>
          alert(`Delete: ${row.original.firstName} ${row.original.lastName}`)
        }
        title="Delete"
      >
        🗑️
      </button>
    </div>
  )
}

/**
 * Price cell with currency formatting
 */
export function PriceCell() {
  const cell = useCellContext<number>()
  return (
    <span className="price">
      $
      {cell.getValue().toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })}
    </span>
  )
}

/**
 * Category badge cell
 */
export function CategoryCell() {
  const cell = useCellContext<'electronics' | 'clothing' | 'food' | 'books'>()
  const category = cell.getValue()
  return <span className={`category-badge ${category}`}>{category}</span>
}
