// examples/lit/composable-tables/src/components/table-components.ts
import { LitElement, html, nothing } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { useTableContext } from '../hooks/table'

// Table-level components are LitElement custom elements that use
// useTableContext(this) to access the table instance from the nearest
// ancestor that called useAppTable. They render in light DOM so that
// global CSS applies and @lit/context events bubble correctly.

@customElement('pagination-controls')
export class PaginationControls extends LitElement {
  private _table = useTableContext(this)

  createRenderRoot() {
    return this
  }

  protected render() {
    const table = this._table.value
    if (!table) return nothing

    return html`
      <div class="pagination">
        <button
          @click=${() => table.firstPage()}
          ?disabled=${!table.getCanPreviousPage()}
        >
          &lt;&lt;
        </button>
        <button
          @click=${() => table.previousPage()}
          ?disabled=${!table.getCanPreviousPage()}
        >
          &lt;
        </button>
        <button
          @click=${() => table.nextPage()}
          ?disabled=${!table.getCanNextPage()}
        >
          &gt;
        </button>
        <button
          @click=${() => table.lastPage()}
          ?disabled=${!table.getCanLastPage()}
        >
          &gt;&gt;
        </button>
        <span>
          Page
          <strong>
            ${(table.state.pagination.pageIndex + 1).toLocaleString()} of
            ${table.getPageCount().toLocaleString()}
          </strong>
        </span>
        <span>
          | Go to page:
          <input
            type="number"
            .value=${String(table.state.pagination.pageIndex + 1)}
            @change=${(e: Event) => {
              const page = (e.target as HTMLInputElement).value
                ? Number((e.target as HTMLInputElement).value) - 1
                : 0
              table.setPageIndex(page)
            }}
            style="width: 64px"
          />
        </span>
        <select
          .value=${String(table.state.pagination.pageSize)}
          @change=${(e: Event) => {
            table.setPageSize(Number((e.target as HTMLSelectElement).value))
          }}
        >
          ${[10, 20, 30, 40, 50].map(
            (pageSize) =>
              html`<option value=${pageSize}>Show ${pageSize}</option>`,
          )}
        </select>
      </div>
    `
  }
}

@customElement('row-count')
export class RowCount extends LitElement {
  private _table = useTableContext(this)

  createRenderRoot() {
    return this
  }

  protected render() {
    const table = this._table.value
    if (!table) return nothing

    return html`
      <div class="row-count">
        Showing ${table.getRowModel().rows.length.toLocaleString()} of
        ${table.getRowCount().toLocaleString()} rows
      </div>
    `
  }
}

@customElement('table-toolbar')
export class TableToolbar extends LitElement {
  private _table = useTableContext(this)

  @property()
  declare title: string

  @property({ attribute: false })
  declare onRefresh: (() => void) | undefined

  @property({ attribute: false })
  declare onStressTest: (() => void) | undefined

  createRenderRoot() {
    return this
  }

  protected render() {
    const table = this._table.value
    if (!table) return nothing

    return html`
      <div class="table-toolbar">
        <h2>${this.title}</h2>
        <div class="table-toolbar-actions">
          ${
            this.onRefresh
              ? html`<button @click=${this.onRefresh}>Regenerate Data</button>`
              : nothing
          }
          ${
            this.onStressTest
              ? html`<button @click=${this.onStressTest}>
                  Stress Test (1M rows)
                </button>`
              : nothing
          }
          <button @click=${() => table.resetColumnFilters()}>
            Clear Filters
          </button>
          <button @click=${() => table.resetSorting()}>Clear Sorting</button>
        </div>
      </div>
    `
  }
}

// examples/react/composable-tables/src/components/table-components.tsx
/**
 * Table-level components that use useTableContext
 *
 * These components can be used via the pre-bound tableComponents
 * directly on the table object, e.g., <table.PaginationControls />
 */
import { useTableContext } from '../hooks/table'

/**
 * Pagination controls for the table
 */
export function PaginationControls() {
  const table = useTableContext()

  return (
    <div className="pagination">
      <button
        onClick={() => table.firstPage()}
        disabled={!table.getCanPreviousPage()}
      >
        {'<<'}
      </button>
      <button
        onClick={() => table.previousPage()}
        disabled={!table.getCanPreviousPage()}
      >
        {'<'}
      </button>
      <button
        onClick={() => table.nextPage()}
        disabled={!table.getCanNextPage()}
      >
        {'>'}
      </button>
      <button
        onClick={() => table.lastPage()}
        disabled={!table.getCanLastPage()}
      >
        {'>>'}
      </button>
      <span>
        Page{' '}
        <strong>
          {(table.state.pagination.pageIndex + 1).toLocaleString()} of{' '}
          {table.getPageCount().toLocaleString()}
        </strong>
      </span>
      <span>
        | Go to page:
        <input
          type="number"
          min="1"
          max={table.getPageCount()}
          defaultValue={table.state.pagination.pageIndex + 1}
          onChange={(e) => {
            const page = e.target.value ? Number(e.target.value) - 1 : 0
            table.setPageIndex(page)
          }}
        />
      </span>
      <select
        value={table.state.pagination.pageSize}
        onChange={(e) => {
          table.setPageSize(Number(e.target.value))
        }}
      >
        {[10, 20, 30, 40, 50].map((pageSize) => (
          <option key={pageSize} value={pageSize}>
            Show {pageSize}
          </option>
        ))}
      </select>
    </div>
  )
}

/**
 * Row count display
 */
export function RowCount() {
  const table = useTableContext()

  return (
    <div className="row-count">
      Showing {table.getRowModel().rows.length.toLocaleString()} of{' '}
      {table.getRowCount().toLocaleString()} rows
    </div>
  )
}

/**
 * Table toolbar with title and actions
 */
export function TableToolbar({
  title,
  onRefresh,
  onStressTest,
}: {
  title: string
  onRefresh?: () => void
  onStressTest?: () => void
}) {
  const table = useTableContext()

  return (
    <div className="table-toolbar">
      <h2>{title}</h2>
      <div className="table-toolbar-actions">
        {onRefresh && <button onClick={onRefresh}>Regenerate Data</button>}
        {onStressTest && (
          <button onClick={onStressTest}>Stress Test (1M rows)</button>
        )}
        <button onClick={() => table.resetColumnFilters()}>
          Clear Filters
        </button>
        <button onClick={() => table.resetSorting()}>Clear Sorting</button>
      </div>
    </div>
  )
}
