// examples/angular/kitchen-sink/src/app/debounced-input/debounced-input.ts
import { Directive, HostListener, input, output } from '@angular/core'

@Directive({
  standalone: true,
  selector: 'input[debouncedInput]',
})
export class DebouncedInput {
  readonly debounce = input<number>(300)
  readonly changeEvent = output<Event>()

  private timeout: ReturnType<typeof setTimeout> | undefined

  @HostListener('input', ['$event'])
  onInput(event: Event) {
    clearTimeout(this.timeout)
    this.timeout = setTimeout(() => {
      this.changeEvent.emit(event)
    }, this.debounce())
  }
}

// examples/react/kitchen-sink/src/components/DebouncedInput.tsx
import React from 'react'

type Props = {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange'>

export const DebouncedInput: React.FC<Props> = ({
  value: initialValue,
  onChange,
  debounce = 500,
  ...props
}) => {
  const [value, setValue] = React.useState<number | string>(initialValue)

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) =>
    setValue(event.target.value)

  React.useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  React.useEffect(() => {
    const timeout = setTimeout(() => {
      onChange(value)
    }, debounce)

    return () => clearTimeout(timeout)
  }, [value])

  return <input {...props} value={value} onChange={handleInputChange} />
}

export default DebouncedInput
