// examples/vue/filters-faceted/src/Filter.vue
<script lang="ts" setup>
import { computed } from 'vue'
import DebouncedInput from './DebouncedInput.vue'
import type { MyColumnMeta, Person, appFeatures } from './tableHelper'
import type { PropType } from 'vue'
import type { Column } from '@tanstack/vue-table'

const props = defineProps({
  column: {
    type: Object as PropType<Column<typeof appFeatures, Person>>,
    required: true,
  },
})

const filterVariant = computed<MyColumnMeta['filterVariant']>(
  () => props.column.columnDef.meta?.filterVariant,
)

const columnFilterValue = computed(() => props.column.getFilterValue())

// dynamically generated options / autocomplete values from the faceting feature
const sortedUniqueValues = computed(() =>
  filterVariant.value === 'range'
    ? []
    : Array.from(props.column.getFacetedUniqueValues().keys())
        .sort()
        .slice(0, 5000),
)
</script>

<template>
  <div v-if="filterVariant === 'range'">
    <div class="filter-row">
      <DebouncedInput
        type="number"
        :min="Number(column.getFacetedMinMaxValues()?.[0] ?? '')"
        :max="Number(column.getFacetedMinMaxValues()?.[1] ?? '')"
        :modelValue="(columnFilterValue as [number, number])?.[0] ?? ''"
        @update:modelValue="
          (value) =>
            column.setFilterValue((old: [number, number]) => [value, old?.[1]])
        "
        :placeholder="`Min ${
          column.getFacetedMinMaxValues()?.[0] !== undefined
            ? `(${column.getFacetedMinMaxValues()?.[0]})`
            : ''
        }`"
        class="filter-input"
      />
      <DebouncedInput
        type="number"
        :min="Number(column.getFacetedMinMaxValues()?.[0] ?? '')"
        :max="Number(column.getFacetedMinMaxValues()?.[1] ?? '')"
        :modelValue="(columnFilterValue as [number, number])?.[1] ?? ''"
        @update:modelValue="
          (value) =>
            column.setFilterValue((old: [number, number]) => [old?.[0], value])
        "
        :placeholder="`Max ${
          column.getFacetedMinMaxValues()?.[1]
            ? `(${column.getFacetedMinMaxValues()?.[1]})`
            : ''
        }`"
        class="filter-input"
      />
    </div>
    <div class="spacer-xs" />
  </div>

  <select
    v-else-if="filterVariant === 'select'"
    :value="columnFilterValue?.toString()"
    @change="
      (e) => column.setFilterValue((e.target as HTMLSelectElement).value)
    "
  >
    <option value="">All</option>
    <option v-for="value in sortedUniqueValues" :key="value" :value="value">
      {{ value }}
    </option>
  </select>

  <div v-else>
    <datalist :id="column.id + 'list'">
      <option v-for="value in sortedUniqueValues" :key="value" :value="value" />
    </datalist>
    <DebouncedInput
      type="text"
      :modelValue="(columnFilterValue ?? '') as string"
      @update:modelValue="(value) => column.setFilterValue(value)"
      :placeholder="`Search... (${column.getFacetedUniqueValues().size})`"
      class="filter-select"
      :list="column.id + 'list'"
    />
    <div class="spacer-xs" />
  </div>
</template>

// examples/react/kitchen-sink/src/components/Filter.tsx
import { Column, RowData, Table } from '@tanstack/react-table'
import React from 'react'
import DebouncedInput from './DebouncedInput'

type NumberInputProps = {
  columnFilterValue: [number, number]
  getFacetedMinMaxValues: () => [number, number] | undefined
  setFilterValue: (updater: any) => void
}

const NumberInput: React.FC<NumberInputProps> = ({
  columnFilterValue,
  getFacetedMinMaxValues,
  setFilterValue,
}) => {
  const minOpt = getFacetedMinMaxValues()?.[0]
  const min = Number(minOpt ?? '')

  const maxOpt = getFacetedMinMaxValues()?.[1]
  const max = Number(maxOpt)

  return (
    <div>
      <div className="flex space-x-2">
        <DebouncedInput
          type="number"
          min={min}
          max={max}
          value={columnFilterValue?.[0] ?? ''}
          onChange={(value) =>
            setFilterValue((old: [number, number]) => [value, old?.[1]])
          }
          placeholder={`Min ${minOpt ? `(${min})` : ''}`}
          className="w-24 border rounded"
        />
        <DebouncedInput
          type="number"
          min={min}
          max={max}
          value={columnFilterValue?.[1] ?? ''}
          onChange={(value) =>
            setFilterValue((old: [number, number]) => [old?.[0], value])
          }
          placeholder={`Max ${maxOpt ? `(${max})` : ''}`}
          className="w-24 border rounded"
        />
      </div>
      <div className="h-1" />
    </div>
  )
}

type TextInputProps = {
  columnId: string
  columnFilterValue: string
  columnSize: number
  setFilterValue: (updater: any) => void
  sortedUniqueValues: any[]
}

const TextInput: React.FC<TextInputProps> = ({
  columnId,
  columnFilterValue,
  columnSize,
  setFilterValue,
  sortedUniqueValues,
}) => {
  const dataListId = columnId + 'list'

  return (
    <React.Fragment>
      <datalist id={dataListId}>
        {sortedUniqueValues.slice(0, 5000).map((value: any) => (
          <option value={value} key={value} />
        ))}
      </datalist>
      <DebouncedInput
        type="text"
        value={columnFilterValue ?? ''}
        onChange={(value) => setFilterValue(value)}
        placeholder={`Search... (${columnSize})`}
        className="w-36 border rounded"
        list={dataListId}
      />
      <div className="h-1" />
    </React.Fragment>
  )
}

type Props<T extends RowData> = {
  column: Column<T, unknown>
  table: Table<T>
}

export function Filter<T extends RowData>({ column, table }: Props<T>) {
  const firstValue = table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(column.id)

  const columnFilterValue = column.getFilterValue()
  const uniqueValues = column.getFacetedUniqueValues()

  const sortedUniqueValues = React.useMemo(
    () =>
      typeof firstValue === 'number'
        ? []
        : Array.from(uniqueValues.keys()).sort(),
    [uniqueValues],
  )

  return typeof firstValue === 'number' ? (
    <NumberInput
      columnFilterValue={columnFilterValue as [number, number]}
      getFacetedMinMaxValues={column.getFacetedMinMaxValues}
      setFilterValue={column.setFilterValue}
    />
  ) : (
    <TextInput
      columnId={column.id}
      columnFilterValue={columnFilterValue as string}
      columnSize={uniqueValues.size}
      setFilterValue={column.setFilterValue}
      sortedUniqueValues={sortedUniqueValues}
    />
  )
}

export default Filter
