// examples/solid/filters-faceted-bucketed/src/ColumnFilter.tsx
import { For, Show } from 'solid-js'
import type { Account } from './makeData'
import type { FacetKey } from './buckets'
import type { features } from './App'
import type { Column, Table } from '@tanstack/solid-table'

function ColumnFilter(props: {
  column: Column<typeof features, Account>
  table: Table<typeof features, Account>
}) {
  const selected = () =>
    (props.column.getFilterValue() ?? []) as Array<FacetKey>
  const options = () => props.column.columnDef.meta?.facetOptions ?? []

  const toggleFacet = (value: FacetKey) => {
    props.column.setFilterValue(
      selected().includes(value)
        ? selected().filter((selectedValue) => selectedValue !== value)
        : [...selected(), value],
    )
  }

  return (
    <Show
      when={props.column.columnDef.meta?.filterVariant === 'facets'}
      fallback={
        <input
          type="text"
          value={(props.column.getFilterValue() ?? '') as string}
          onInput={(event) =>
            props.column.setFilterValue(event.currentTarget.value)
          }
          placeholder="Search…"
          class="filter-select"
        />
      }
    >
      <fieldset class="facet-options">
        <For each={options()}>
          {(option) => (
            <label>
              <input
                type="checkbox"
                checked={selected().includes(option.value)}
                onChange={() => toggleFacet(option.value)}
              />
              <span>{option.label}</span>
              <span class="count">
                {(
                  props.column.getFacetedUniqueValues().get(option.value) ?? 0
                ).toLocaleString()}
              </span>
            </label>
          )}
        </For>
      </fieldset>
    </Show>
  )
}

export default ColumnFilter

// examples/svelte/filters-faceted-bucketed/src/ColumnFilter.svelte
<script lang="ts">
  import type { Column, Table } from '@tanstack/svelte-table'
  import type { features } from './features'
  import type { Account } from './makeData'
  import type { FacetKey } from './buckets'

  let { column, table: _table }: {
    column: Column<typeof features, Account, unknown>
    table: Table<typeof features, Account>
  } = $props()

  const variant = $derived(column.columnDef.meta?.filterVariant)
  const options = $derived(column.columnDef.meta?.facetOptions ?? [])
  const selected = $derived((column.getFilterValue() ?? []) as Array<FacetKey>)
  const counts = $derived(column.getFacetedUniqueValues())

  function toggleFacet(value: FacetKey) {
    column.setFilterValue(
      selected.includes(value)
        ? selected.filter((selectedValue) => selectedValue !== value)
        : [...selected, value],
    )
  }
</script>

{#if variant === 'facets'}
  <fieldset class="facet-options">
    {#each options as option (option.value)}
      <label>
        <input
          type="checkbox"
          checked={selected.includes(option.value)}
          onchange={() => toggleFacet(option.value)}
        />
        <span>{option.label}</span>
        <span class="count">{(counts.get(option.value) ?? 0).toLocaleString()}</span>
      </label>
    {/each}
  </fieldset>
{:else}
  <input
    type="text"
    value={(column.getFilterValue() ?? '') as string}
    oninput={(event) => column.setFilterValue(event.currentTarget.value)}
    placeholder="Search…"
    class="filter-select"
  />
{/if}
