// examples/solid/column-pinning/src/App.tsx
import { faker } from '@faker-js/faker'
import {
  columnOrderingFeature,
  columnPinningFeature,
  columnVisibilityFeature,
  createTableHook,
} from '@tanstack/solid-table'
import { For, createSignal } from 'solid-js'
import { makeData } from './makeData'
import type { Person } from './makeData'

const { createAppTable, createAppColumnHelper } = createTableHook({
  features: {
    columnVisibilityFeature,
    columnPinningFeature,
    columnOrderingFeature,
  },
  debugTable: true,
  debugHeaders: true,
  debugColumns: true,
})

const columnHelper = createAppColumnHelper<Person>()

const columns = columnHelper.columns([
  columnHelper.group({
    header: 'Name',
    footer: (props) => props.column.id,
    columns: columnHelper.columns([
      columnHelper.accessor('firstName', {
        cell: (info) => info.getValue(),
        footer: (props) => props.column.id,
      }),
      columnHelper.accessor((row) => row.lastName, {
        id: 'lastName',
        cell: (info) => info.getValue(),
        header: () => <span>Last Name</span>,
        footer: (props) => props.column.id,
      }),
    ]),
  }),
  columnHelper.group({
    header: 'Info',
    footer: (props) => props.column.id,
    columns: columnHelper.columns([
      columnHelper.accessor('age', {
        header: () => 'Age',
        footer: (props) => props.column.id,
      }),
      columnHelper.group({
        header: 'More Info',
        columns: columnHelper.columns([
          columnHelper.accessor('visits', {
            header: () => <span>Visits</span>,
            footer: (props) => props.column.id,
          }),
          columnHelper.accessor('status', {
            header: 'Status',
            footer: (props) => props.column.id,
          }),
          columnHelper.accessor('progress', {
            header: 'Profile Progress',
            footer: (props) => props.column.id,
          }),
        ]),
      }),
    ]),
  }),
])

function App() {
  const [data, setData] = createSignal(makeData(1_000))
  const refreshData = () => setData(makeData(1_000))
  const stressTest = () => setData(makeData(1_000_000))

  const table = createAppTable({
    columns,
    get data() {
      return data()
    },
    // initialState: { columnPinning: { start: ['firstName'], end: [] } }, // `start`/`end` follow layout direction
    // atoms: { columnPinning: columnPinningAtom }, // preferred: own pinning state with an external atom
    // state: { columnPinning }, // classic controlled state; pair with onColumnPinningChange
    // onColumnPinningChange: setColumnPinning,
    // enableColumnPinning: false, // disable pinning for every column; default true
    debugTable: true,
  })

  const randomizeColumns = () => {
    table.setColumnOrder(
      faker.helpers.shuffle(table.getAllLeafColumns().map((d) => d.id)),
    )
  }

  return (
    <div class="demo-root">
      <div class="column-toggle-panel">
        <div class="column-toggle-panel-header">
          <label>
            <input
              type="checkbox"
              checked={table.getIsAllColumnsVisible()}
              onChange={table.getToggleAllColumnsVisibilityHandler()}
            />{' '}
            Toggle All
          </label>
        </div>
        <For each={table.getAllLeafColumns()}>
          {(column) => (
            <div class="column-toggle-row">
              <label>
                <input
                  type="checkbox"
                  checked={column.getIsVisible()}
                  onChange={column.getToggleVisibilityHandler()}
                />{' '}
                {column.id}
              </label>
            </div>
          )}
        </For>
      </div>
      <div class="spacer-md" />
      <div class="button-row">
        <button
          onClick={() => refreshData()}
          class="demo-button demo-button-sm"
        >
          Regenerate Data
        </button>
        <button onClick={() => stressTest()} class="demo-button demo-button-sm">
          Stress Test (1M rows)
        </button>
        <button
          onClick={() => randomizeColumns()}
          class="demo-button demo-button-sm"
        >
          Shuffle Columns
        </button>
      </div>
      <div class="spacer-md" />
      <p class="demo-note">
        This example using the non-split APIs. Columns are just reordered within
        1 table instead of being split into 3 different tables.
      </p>
      <div class="table-row-group">
        <table class="outlined-table">
          <thead>
            <For each={table.getHeaderGroups()}>
              {(headerGroup) => (
                <tr>
                  <For each={headerGroup.headers}>
                    {(header) => (
                      <th colSpan={header.colSpan}>
                        <div class="nowrap">
                          {header.isPlaceholder ? null : (
                            <table.FlexRender header={header} />
                          )}
                        </div>
                        {!header.isPlaceholder && header.column.getCanPin() && (
                          <div class="pin-actions">
                            {header.column.getIsPinned() !== 'start' ? (
                              <button
                                class="pin-button"
                                onClick={() => header.column.pin('start')}
                              >
                                {'<='}
                              </button>
                            ) : null}
                            {header.column.getIsPinned() ? (
                              <button
                                class="pin-button"
                                onClick={() => header.column.pin(false)}
                              >
                                X
                              </button>
                            ) : null}
                            {header.column.getIsPinned() !== 'end' ? (
                              <button
                                class="pin-button"
                                onClick={() => header.column.pin('end')}
                              >
                                {'=>'}
                              </button>
                            ) : null}
                          </div>
                        )}
                      </th>
                    )}
                  </For>
                </tr>
              )}
            </For>
          </thead>
          <tbody>
            <For each={table.getRowModel().rows.slice(0, 20)}>
              {(row) => (
                <tr>
                  <For each={row.getVisibleCells()}>
                    {(cell) => (
                      <td>
                        <table.FlexRender cell={cell} />
                      </td>
                    )}
                  </For>
                </tr>
              )}
            </For>
          </tbody>
        </table>
      </div>
      <pre data-testid="table-state">
        {JSON.stringify(table.store.get(), null, 2)}
      </pre>
    </div>
  )
}

export default App

// examples/svelte/column-pinning-sticky/src/App.svelte
<script lang="ts">
  import { faker } from '@faker-js/faker'
  import {
    columnOrderingFeature,
    columnPinningFeature,
    columnResizingFeature,
    columnSizingFeature,
    columnVisibilityFeature,
    createTable,
    FlexRender,
    tableFeatures,
  } from '@tanstack/svelte-table'
  import { makeData } from './makeData'
  import type { Column } from '@tanstack/svelte-table'
  import type { Person } from './makeData'
  import './index.css'

  const features = tableFeatures({
    columnOrderingFeature,
    columnPinningFeature,
    columnResizingFeature,
    columnSizingFeature,
    columnVisibilityFeature,
  })

  type PinningStyles = {
    boxShadow: string | undefined
    'inset-inline-start': string | undefined
    'inset-inline-end': string | undefined
    opacity: number
    position: string
    width: string
    zIndex: number
  }

  const getCommonPinningStyles = (
    column: Column<typeof features, Person>,
  ): PinningStyles => {
    const isPinned = column.getIsPinned()
    const isLastLeftPinnedColumn =
      isPinned === 'start' && column.getIsLastColumn('start')
    const isFirstRightPinnedColumn =
      isPinned === 'end' && column.getIsFirstColumn('end')

    return {
      boxShadow: isLastLeftPinnedColumn
        ? '-4px 0 4px -4px gray inset'
        : isFirstRightPinnedColumn
          ? '4px 0 4px -4px gray inset'
          : undefined,
      'inset-inline-start': isPinned === 'start' ? `${column.getStart('start')}px` : undefined,
      'inset-inline-end': isPinned === 'end' ? `${column.getAfter('end')}px` : undefined,
      opacity: isPinned ? 0.95 : 1,
      position: isPinned ? 'sticky' : 'relative',
      width: `${column.getSize()}px`,
      zIndex: isPinned ? 1 : 0,
    }
  }

  const defaultColumns = [
    {
      accessorKey: 'firstName',
      id: 'firstName',
      header: 'First Name',
      cell: (info: any) => info.getValue(),
      footer: (props: any) => props.column.id,
      size: 180,
    },
    {
      accessorFn: (row: Person) => row.lastName,
      id: 'lastName',
      cell: (info: any) => info.getValue(),
      header: () => 'Last Name',
      footer: (props: any) => props.column.id,
      size: 180,
    },
    {
      accessorKey: 'age',
      id: 'age',
      header: 'Age',
      footer: (props: any) => props.column.id,
      size: 180,
    },
    {
      accessorKey: 'visits',
      id: 'visits',
      header: 'Visits',
      footer: (props: any) => props.column.id,
      size: 180,
    },
    {
      accessorKey: 'status',
      id: 'status',
      header: 'Status',
      footer: (props: any) => props.column.id,
      size: 180,
    },
    {
      accessorKey: 'progress',
      id: 'progress',
      header: 'Profile Progress',
      footer: (props: any) => props.column.id,
      size: 180,
    },
  ]

  let data = $state(makeData(20))
  const refreshData = () => { data = makeData(20) }
  const stressTest = () => { data = makeData(1_000) }

  const table = createTable(
    {
      features,
      columns: defaultColumns,
      get data() {
        return data
      },
      columnResizeMode: 'onChange',
      // initialState: { columnPinning: { start: ['firstName'], end: [] } }, // `start`/`end` follow layout direction
      // atoms: { columnPinning: columnPinningAtom }, // preferred: own pinning state with an external atom
      // state: { columnPinning }, // classic controlled state; pair with onColumnPinningChange
      // onColumnPinningChange: setColumnPinning,
      // enableColumnPinning: false, // disable pinning for every column; default true
      debugTable: true,
      debugHeaders: true,
      debugColumns: true,
    },
  )

  const randomizeColumns = () => {
    table.setColumnOrder(
      faker.helpers.shuffle(table.getAllLeafColumns().map((d) => d.id)),
    )
  }
</script>

<div class="demo-root">
  <div>
    <button onclick={() => refreshData()}>Regenerate Data</button>
    <button onclick={() => stressTest()}>Stress Test (1k rows)</button>
  </div>
  <div class="column-toggle-panel">
    <div class="column-toggle-panel-header">
      <label>
        <input
          type="checkbox"
          checked={table.getIsAllColumnsVisible()}
          onchange={table.getToggleAllColumnsVisibilityHandler()}
        />
        {' '}Toggle All
      </label>
    </div>
    {#each table.getAllLeafColumns() as column}
      <div class="column-toggle-row">
        <label>
          <input
            type="checkbox"
            checked={column.getIsVisible()}
            onchange={column.getToggleVisibilityHandler()}
          />
          {' '}{column.id}
        </label>
      </div>
    {/each}
  </div>
  <div class="spacer-md"></div>
  <div class="button-row">
    <button onclick={() => randomizeColumns()} class="demo-button demo-button-sm">
      Shuffle Columns
    </button>
  </div>
  <div class="spacer-md"></div>
  <div class="table-container">
    <table style="width: {table.getTotalSize()
    }px">
      <thead>
        {#each table.getHeaderGroups() as headerGroup (headerGroup.id)}
          <tr>
            {#each headerGroup.headers as header (header.id)}
              {@const styles = getCommonPinningStyles(header.column)}
              <th
                colSpan={header.colSpan}
                style="box-shadow: {styles.boxShadow ?? 'none'}; inset-inline-start: {styles[
                  'inset-inline-start'
                ] ?? 'auto'}; inset-inline-end: {styles['inset-inline-end'] ??
                  'auto'}; opacity: {styles.opacity}; position: {styles.position}; width: {styles.width}; z-index: {styles.zIndex}"
              >
                <div class="nowrap">
                  {#if !header.isPlaceholder}
                    <FlexRender header={header} />
                    {' '}
                  {/if}
                  {header.column.getIndex(header.column.getIsPinned() || 'center')}
                </div>
                {#if !header.isPlaceholder && header.column.getCanPin()}
                  <div class="pin-actions">
                    {#if header.column.getIsPinned() !== 'start'}
                      <button
                        class="pin-button"
                        onclick={() => header.column.pin('start')}
                      >
                        {'<='}
                      </button>
                    {/if}
                    {#if header.column.getIsPinned()}
                      <button
                        class="pin-button"
                        onclick={() => header.column.pin(false)}
                      >
                        X
                      </button>
                    {/if}
                    {#if header.column.getIsPinned() !== 'end'}
                      <button
                        class="pin-button"
                        onclick={() => header.column.pin('end')}
                      >
                        {'=>'}
                      </button>
                    {/if}
                  </div>
                {/if}
                <!-- svelte-ignore a11y_no_static_element_interactions -->
                <div
                  ondblclick={() => header.column.resetSize()}
                  onmousedown={header.getResizeHandler()}
                  ontouchstart={header.getResizeHandler()}
                  class="resizer {header.column.getIsResizing() ? 'isResizing' : ''}"
                ></div>
              </th>
            {/each}
          </tr>
        {/each}
      </thead>
      <tbody>
        {#each table.getRowModel().rows as row (row.id)}
          <tr>
            {#each row.getVisibleCells() as cell (cell.id)}
              {@const styles = getCommonPinningStyles(cell.column)}
              <td
                style="box-shadow: {styles.boxShadow ?? 'none'}; inset-inline-start: {styles[
                  'inset-inline-start'
                ] ?? 'auto'}; inset-inline-end: {styles['inset-inline-end'] ??
                  'auto'}; opacity: {styles.opacity}; position: {styles.position}; width: {styles.width}; z-index: {styles.zIndex}"
              >
                <FlexRender cell={cell} />
              </td>
            {/each}
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <pre data-testid="table-state">{JSON.stringify(table.store.get(), null, 2)
  }</pre>
</div>
