// examples/preact/composable-tables/src/components/header-components.tsx
/**
 * Header-level components that use useHeaderContext
 *
 * These components can be used via the pre-bound headerComponents
 * in AppHeader children, e.g., <header.SortIndicator />
 */
import { useHeaderContext } from '../hooks/table'

/**
 * Sort indicator showing current sort direction
 */
export function SortIndicator() {
  const header = useHeaderContext()
  const sorted = header.column.getIsSorted()

  if (!sorted) return null

  return (
    <span className="sort-indicator">{sorted === 'asc' ? '🔼' : '🔽'}</span>
  )
}

/**
 * Column filter input
 */
export function ColumnFilter() {
  const header = useHeaderContext()

  if (!header.column.getCanFilter()) return null

  const columnFilterValue = header.column.getFilterValue()

  return (
    <div className="column-filter" onClick={(e) => e.stopPropagation()}>
      <input
        type="text"
        value={(columnFilterValue ?? '') as string}
        onInput={(e) =>
          header.column.setFilterValue((e.target as HTMLInputElement).value)
        }
        placeholder={`Filter ${header.column.id}...`}
      />
    </div>
  )
}

/**
 * Footer showing the column ID
 */
export function FooterColumnId() {
  const header = useHeaderContext()
  return <span className="footer-column-id">{header.column.id}</span>
}

/**
 * Footer showing a summary/aggregation for numeric columns
 */
export function FooterSum() {
  const header = useHeaderContext()
  const table = header.getContext().table
  const rows = table.getFilteredRowModel().rows

  // Calculate sum for numeric columns
  const sum = rows.reduce((acc, row) => {
    const value = row.getValue(header.column.id)
    return acc + (typeof value === 'number' ? value : 0)
  }, 0)

  return (
    <span className="footer-sum">{sum > 0 ? sum.toLocaleString() : '—'}</span>
  )
}

// examples/lit/composable-tables/src/components/header-components.ts
import { html, nothing } from 'lit'
import type { Header } from '@tanstack/lit-table'

// Header components are plain functions that receive the header instance as
// their first argument (bound automatically by AppHeader/AppFooter in createTableHook).
// In column definitions, call them as: header.SortIndicator()

export function SortIndicator(header: Header<any, any, any>) {
  const sorted = header.column.getIsSorted()
  if (!sorted) return nothing
  return html`<span class="sort-indicator"
    >${sorted === 'asc' ? '🔼' : '🔽'}</span
  >`
}

export function ColumnFilter(header: Header<any, any, any>) {
  if (!header.column.getCanFilter()) return nothing
  const value = (header.column.getFilterValue() ?? '') as string
  return html`
    <div class="column-filter" @click=${(e: Event) => e.stopPropagation()}>
      <input
        type="text"
        .value=${value}
        @input=${(e: InputEvent) =>
          header.column.setFilterValue((e.target as HTMLInputElement).value)}
        placeholder="Filter ${header.column.id}..."
      />
    </div>
  `
}

export function FooterColumnId(header: Header<any, any, any>) {
  return html`<span>${header.column.id}</span>`
}

export function FooterSum(header: Header<any, any, any>) {
  const table = header.getContext().table
  const rows = table.getFilteredRowModel().rows
  const sum = rows.reduce((acc, row) => {
    const value = row.getValue(header.column.id)
    return acc + (typeof value === 'number' ? value : 0)
  }, 0)
  return html`<span>${sum > 0 ? sum.toLocaleString() : '—'}</span>`
}
