// examples/svelte/composable-tables/src/components/ProductsTable.svelte
<!--
  Products Table Component - uses the same createAppTable hook and components as UsersTable,
  but with different data types and column configurations.
-->
<script lang="ts">
  import { FlexRender, renderComponent } from '@tanstack/svelte-table'
  import { createAppColumnHelper, createAppTable } from '../hooks/table'
  import { makeProductData } from '../makeData'
  import type { Product } from '../makeData'

  // Create column helper with TFeatures already bound - only need TData!
  const productColumnHelper = createAppColumnHelper<Product>()

  // Data state
  let data = $state(makeProductData(1_000))

  // Refresh data callback
  function refreshData() {
    data = makeProductData(1_000)
  }
  function stressTest() {
    data = makeProductData(1_000_000)
  }

  // Define columns using the column helper - different structure than Users table
  const columns = productColumnHelper.columns([
    productColumnHelper.display({
      id: 'select',
      header: ({ header }) => renderComponent(header.SelectHeader),
      cell: ({ cell }) => renderComponent(cell.SelectCell),
    }),
    productColumnHelper.accessor('name', {
      header: 'Product Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell, {}),
    }),
    productColumnHelper.accessor('category', {
      header: 'Category',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.CategoryCell, {}),
    }),
    productColumnHelper.accessor('price', {
      header: 'Price',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.PriceCell, {}),
    }),
    productColumnHelper.accessor('stock', {
      header: 'In Stock',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell, {}),
    }),
    productColumnHelper.accessor('rating', {
      header: 'Rating',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.ProgressCell, {}),
    }),
  ])

  // Create the table using the same createAppTable hook
  const table = createAppTable({
    debugTable: true,
    columns,
    get data() {
      return data
    },
    getRowId: (row) => row.id,
    enableRowSelection: true,
  })

  const sorting = $derived(table.atoms.sorting.get())
  const columnFilters = $derived(table.atoms.columnFilters.get())
  const rows = $derived(table.getRowModel().rows)
</script>

<table.AppTable>
  <div class="table-container">
    <!-- Table toolbar using the same pre-bound component -->
    <table.TableToolbar
      title="Products Table"
      onRefresh={refreshData}
      onStressTest={stressTest}
    />

    <!-- Table element -->
    <div class="table-scroll">
    <table>
      <thead>
        {#each table.getHeaderGroups() as headerGroup (headerGroup.id)
        }
          <tr>
            {#each headerGroup.headers as h (h.id)}
              <table.AppHeader header={h
              }>
                {#snippet children(header)}
                  <th
                    colSpan={header.colSpan}
                    class={header.column.getCanSort() ? 'sortable-header' : ''}
                    onclick={header.column.getToggleSortingHandler()}
                  >
                    {#if !header.isPlaceholder}
                      <header.FlexRender
                        header={header}
                      />
                      <header.SortIndicator />
                      <header.ColumnFilter />
                      <!-- Show sort order number when multiple columns sorted -->
                      {#if sorting.length > 1 && sorting.findIndex((s) => s.id === header.column.id) > -1}
                        <span class="sort-order">
                          {sorting.findIndex((s) => s.id === header.column.id) + 1}
                        </span>
                      {/if}
                    {/if}
                  </th>
                {/snippet}
              </table.AppHeader>
            {/each
            }
          </tr>
        {/each}
      </thead>
      <tbody>
        {#each rows as row (row.id + JSON.stringify(row.original))}
          <tr>
            {#each row.getAllCells() as c (c.id)}
              <table.AppCell cell={c
              }>
                {#snippet children(cell)}
                  <td>
                    <FlexRender cell={cell} />
                  </td>
                {/snippet}
              </table.AppCell>
            {/each
            }
          </tr>
        {/each}
      </tbody>
      <tfoot>
        {#each table.getFooterGroups() as footerGroup (footerGroup.id)}
          <tr>
            {#each footerGroup.headers as f (f.id)}
              <table.AppFooter header={f
              }>
                {#snippet children(footer)}
                  <td colSpan={footer.colSpan}>
                    {#if !footer.isPlaceholder}
                      {#if footer.column.id === 'price' || footer.column.id === 'stock' || footer.column.id === 'rating'}
                        <footer.FooterSum />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> (filtered)</span>
                        {/if}
                      {:else}
                        <footer.FooterColumnId />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> ✓</span>
                        {/if}
                      {/if}
                    {/if}
                  </td>
                {/snippet}
              </table.AppFooter>
            {/each
            }
          </tr>
        {/each}
      </tfoot>
    </table>
    </div>

    <!-- Pagination using the same pre-bound component -->
    <table.PaginationControls />

    <!-- Row count using the same pre-bound component -->
    <table.RowCount />
  </div>
</table.AppTable>

// examples/lit/composable-tables/src/components/products-table.ts
import { LitElement, html, nothing } from 'lit'
import { customElement, state } from 'lit/decorators.js'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeProductData } from '../makeData'
import type { Product } from '../makeData'
// Import table-level custom elements so they are registered
import './table-components'

// Create the column helper pre-bound with features — only need the data type!
const productColumnHelper = createAppColumnHelper<Product>()

// Define columns — different structure than Users table, same reusable components
const columns = productColumnHelper.columns([
  productColumnHelper.accessor('name', {
    header: 'Product Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell(),
  }),
  productColumnHelper.accessor('category', {
    header: 'Category',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.CategoryCell(),
  }),
  productColumnHelper.accessor('price', {
    header: 'Price',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.PriceCell(),
  }),
  productColumnHelper.accessor('stock', {
    header: 'In Stock',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell(),
  }),
  productColumnHelper.accessor('rating', {
    header: 'Rating',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell(),
  }),
])

@customElement('products-table')
export class ProductsTable extends LitElement {
  @state()
  private data = makeProductData(500)

  // Create the table using the same useAppTable hook
  // NOTE: Capture `this` as `host` to avoid infinite recursion in the getter
  private appTable = (() => {
    const host = this
    return useAppTable(
      this,
      {
        debugTable: true,
        columns,
        get data() {
          return host.data
        },
      },
      (state) => ({
        pagination: state.pagination,
        sorting: state.sorting,
        columnFilters: state.columnFilters,
      }),
    )
  })()

  private refreshData = () => {
    this.data = makeProductData(500)
  }

  createRenderRoot() {
    return this
  }

  protected render() {
    const table = this.appTable.table()
    const { sorting, columnFilters } = table.state

    return html`
      <div class="table-container">
        <!-- Table toolbar using the same context-based custom element -->
        <table-toolbar
          .title=${'Products Table'}
          .onRefresh=${this.refreshData}
          .onStressTest=${() => {
            this.data = makeProductData(200_000)
          }}
        ></table-toolbar>

        <!-- Table element -->
        <table>
          <thead>
            ${table.getHeaderGroups().map(
              (headerGroup) => html`
                <tr>
                  ${headerGroup.headers.map((h) =>
                    table.AppHeader(
                      h,
                      (header) => html`
                        <th
                          colspan=${header.colSpan}
                          class=${header.column.getCanSort()
                            ? 'sortable-header'
                            : ''}
                          @click=${header.column.getToggleSortingHandler()}
                        >
                          ${header.isPlaceholder
                            ? nothing
                            : html`
                                ${header.FlexRender()} ${header.SortIndicator()}
                                ${header.ColumnFilter()}
                                ${sorting.length > 1 &&
                                sorting.findIndex(
                                  (s) => s.id === header.column.id,
                                ) > -1
                                  ? html`<span class="sort-order"
                                      >${sorting.findIndex(
                                        (s) => s.id === header.column.id,
                                      ) + 1}</span
                                    >`
                                  : nothing}
                              `}
                        </th>
                      `,
                    ),
                  )}
                </tr>
              `,
            )}
          </thead>
          <tbody>
            ${table.getRowModel().rows.map(
              (row) => html`
                <tr>
                  ${row
                    .getAllCells()
                    .map((c) =>
                      table.AppCell(
                        c,
                        (cell) => html` <td>${cell.FlexRender()}</td> `,
                      ),
                    )}
                </tr>
              `,
            )}
          </tbody>
          <tfoot>
            ${table.getFooterGroups().map(
              (footerGroup) => html`
                <tr>
                  ${footerGroup.headers.map((f) =>
                    table.AppFooter(f, (footer) => {
                      const columnId = footer.column.id
                      const hasFilter = columnFilters.some(
                        (cf) => cf.id === columnId,
                      )
                      return html`
                        <td colspan=${footer.colSpan}>
                          ${footer.isPlaceholder
                            ? nothing
                            : columnId === 'price' ||
                                columnId === 'stock' ||
                                columnId === 'rating'
                              ? html`
                                  ${footer.FooterSum()}
                                  ${hasFilter
                                    ? html`<span class="filtered-indicator">
                                        (filtered)</span
                                      >`
                                    : nothing}
                                `
                              : html`
                                  ${footer.FooterColumnId()}
                                  ${hasFilter
                                    ? html`<span class="filtered-indicator">
                                        ✓</span
                                      >`
                                    : nothing}
                                `}
                        </td>
                      `
                    }),
                  )}
                </tr>
              `,
            )}
          </tfoot>
        </table>

        <!-- Pagination and row count using the same context-based custom elements -->
        <pagination-controls></pagination-controls>
        <row-count></row-count>
      </div>
    `
  }
}
