// examples/react/kitchen-sink-hero-ui/src/components/data-table/data-table-filter-list.tsx
'use client'

import * as React from 'react'
import { Button, Input, Popover } from '@heroui/react'
import type { ExtendedColumnFilter } from '@/types'
import { useTableContext } from '@/hooks/table'
import { getFilterOperators } from '@/lib/data-table'
import { HeroSelect, toDateInputValue } from '@/components/data-table/shared'

function FilterValueInput({
  column,
  filter,
  onFilterUpdate,
}: {
  column: any
  filter: ExtendedColumnFilter
  onFilterUpdate: (
    filterId: string,
    patch: Partial<ExtendedColumnFilter>,
  ) => void
}) {
  if (!filter.filterId) return null
  const variant = column.columnDef.meta?.variant ?? 'text'
  const operator = filter.operator ?? 'includesString'
  const disabled = operator === 'isEmpty' || operator === 'isNotEmpty'

  if (disabled)
    return <div className="pb-2 text-sm text-muted">No value required</div>

  if (variant === 'select') {
    const options: Array<{ label: string; value: string }> =
      column.columnDef.meta?.options ?? []
    return (
      <HeroSelect
        label="Value"
        value={typeof filter.value === 'string' ? filter.value : null}
        options={options}
        onChange={(value) => onFilterUpdate(filter.filterId!, { value })}
      />
    )
  }

  if (variant === 'multi-select') {
    const options: Array<{ label: string; value: string }> =
      column.columnDef.meta?.options ?? []
    const values = Array.isArray(filter.value)
      ? filter.value.map(String)
      : typeof filter.value === 'string' && filter.value
        ? [filter.value]
        : []
    return (
      <label className="grid gap-1 text-sm">
        <span className="font-medium">Value</span>
        <select
          multiple
          className="min-h-24 rounded-md border border-border bg-background p-2"
          value={values}
          onChange={(event) =>
            onFilterUpdate(filter.filterId!, {
              value: Array.from(event.currentTarget.selectedOptions).map(
                (option) => option.value,
              ),
            })
          }
        >
          {options.map((option: { label: string; value: string }) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
      </label>
    )
  }

  if (variant === 'date') {
    if (operator === 'inRange') {
      const value = Array.isArray(filter.value) ? filter.value : []
      return (
        <div className="grid grid-cols-2 gap-2">
          <Input
            aria-label="From"
            type="date"
            value={toDateInputValue(value[0])}
            onChange={(event) =>
              onFilterUpdate(filter.filterId!, {
                value: [
                  event.currentTarget.value
                    ? new Date(event.currentTarget.value).toISOString()
                    : undefined,
                  value[1],
                ],
              })
            }
          />
          <Input
            aria-label="To"
            type="date"
            value={toDateInputValue(value[1])}
            onChange={(event) =>
              onFilterUpdate(filter.filterId!, {
                value: [
                  value[0],
                  event.currentTarget.value
                    ? new Date(event.currentTarget.value).toISOString()
                    : undefined,
                ],
              })
            }
          />
        </div>
      )
    }

    return (
      <Input
        aria-label="Value"
        type="date"
        value={toDateInputValue(filter.value)}
        onChange={(event) =>
          onFilterUpdate(filter.filterId!, {
            value: event.currentTarget.value
              ? new Date(event.currentTarget.value).toISOString()
              : undefined,
          })
        }
      />
    )
  }

  if (variant === 'number') {
    return (
      <Input
        aria-label="Value"
        type="number"
        value={
          typeof filter.value === 'number' || typeof filter.value === 'string'
            ? String(filter.value)
            : ''
        }
        onChange={(event) =>
          onFilterUpdate(filter.filterId!, {
            value:
              event.currentTarget.value === ''
                ? ''
                : Number(event.currentTarget.value),
          })
        }
      />
    )
  }

  return (
    <Input
      aria-label="Value"
      value={typeof filter.value === 'string' ? filter.value : ''}
      onChange={(event) =>
        onFilterUpdate(filter.filterId!, { value: event.currentTarget.value })
      }
    />
  )
}

export function DataTableFilterList(): React.ReactNode {
  const table = useTableContext()
  const columnFilters = table.state.columnFilters as Array<ExtendedColumnFilter>

  // Write through the raw controlled-state handler instead of
  // `table.setColumnFilters`: the table API auto-removes filters with empty
  // values, but a just-added filter row legitimately starts with `value: ''`
  // while the user is still building it.
  const setColumnFilters = (filters: Array<ExtendedColumnFilter>) => {
    table.options.onColumnFiltersChange?.(filters)
  }

  const filterableColumns = table
    .getAllColumns()
    .filter((column: any) => column.getCanFilter())
  const fieldOptions = filterableColumns.map((column: any) => ({
    value: column.id as string,
    label: (column.columnDef.meta?.label ?? column.id) as string,
  }))

  const updateFilter = (
    filterId: string,
    patch: Partial<ExtendedColumnFilter>,
  ) => {
    setColumnFilters(
      columnFilters.map((filter: ExtendedColumnFilter) =>
        filter.filterId === filterId ? { ...filter, ...patch } : filter,
      ),
    )
  }

  const addFilter = () => {
    const [column] = filterableColumns
    if (!column) return
    setColumnFilters([
      ...columnFilters,
      {
        id: column.id,
        filterId: crypto.randomUUID(),
        value: '',
        operator: 'includesString',
        joinOperator: columnFilters[0]?.joinOperator ?? 'and',
      },
    ] as any)
  }

  return (
    <Popover>
      <Button variant="secondary" size="sm">
        Filter{columnFilters.length ? ` (${columnFilters.length})` : ''}
      </Button>
      <Popover.Content className="w-[760px]">
        <Popover.Dialog className="space-y-4 p-3">
          <div className="font-semibold">Filters</div>
          {columnFilters.map((filter: ExtendedColumnFilter, index: number) => {
            const column = table.getColumn(filter.id)
            if (!column || !filter.filterId) return null
            const variant = column.columnDef.meta?.variant ?? 'text'
            const operators = getFilterOperators(variant)
            return (
              <div
                key={filter.filterId}
                className="grid grid-cols-[4.5rem_11rem_11rem_1fr_auto] items-end gap-2"
              >
                {index === 0 ? (
                  <div className="pb-2 text-sm">Where</div>
                ) : index === 1 ? (
                  <HeroSelect
                    label="Join"
                    value={filter.joinOperator ?? 'and'}
                    options={[
                      { value: 'and', label: 'and' },
                      { value: 'or', label: 'or' },
                    ]}
                    onChange={(joinOperator) =>
                      setColumnFilters(
                        columnFilters.map((item: ExtendedColumnFilter) => ({
                          ...item,
                          joinOperator: joinOperator as 'and' | 'or',
                        })),
                      )
                    }
                  />
                ) : (
                  <div className="pb-2 text-sm">
                    {filter.joinOperator ?? 'and'}
                  </div>
                )}
                <HeroSelect
                  label="Field"
                  value={column.id}
                  options={fieldOptions}
                  onChange={(nextColumnId) => {
                    const nextColumn = table.getColumn(nextColumnId)
                    if (nextColumn) {
                      updateFilter(filter.filterId!, {
                        id: nextColumn.id,
                        operator: getFilterOperators(
                          nextColumn.columnDef.meta?.variant ?? 'text',
                        )[0].value,
                        value: '',
                      })
                    }
                  }}
                />
                <HeroSelect
                  label="Operator"
                  value={filter.operator ?? operators[0].value}
                  options={operators.map((op) => ({
                    value: op.value,
                    label: op.label,
                  }))}
                  onChange={(operator) =>
                    updateFilter(filter.filterId!, {
                      operator: operator as ExtendedColumnFilter['operator'],
                      value: '',
                    })
                  }
                />
                <FilterValueInput
                  column={column}
                  filter={filter}
                  onFilterUpdate={updateFilter}
                />
                <Button
                  variant="ghost"
                  size="sm"
                  onPress={() =>
                    setColumnFilters(
                      columnFilters.filter(
                        (item: ExtendedColumnFilter) =>
                          item.filterId !== filter.filterId,
                      ),
                    )
                  }
                >
                  Remove
                </Button>
              </div>
            )
          })}
          <div className="flex gap-2">
            <Button size="sm" onPress={addFilter}>
              Add filter
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onPress={() => setColumnFilters([])}
            >
              Reset
            </Button>
          </div>
        </Popover.Dialog>
      </Popover.Content>
    </Popover>
  )
}

// examples/vue/kitchen-sink-shadcn/src/components/data-table/DataTableFilterList.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Check, ChevronsUpDown, ListFilter, Trash2 } from '@lucide/vue'
import { useId } from 'reka-ui'
import type {
  ExtendedColumnFilter,
  FilterOperator,
  JoinOperator,
} from '@/types'
import type { Column, RowData } from '@tanstack/vue-table'
import type { features } from '@/hooks/features'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import { getFilterOperators } from '@/lib/data-table'
import { cn } from '@/lib/utils'
import { useTableContext } from '@/hooks/table'
import DataTableFilterValueInput from '@/components/data-table/DataTableFilterValueInput.vue'

const table = useTableContext()
const columnFilters = computed(
  () => table.atoms.columnFilters.get() as Array<ExtendedColumnFilter>,
)

// Write through the raw controlled-state handler instead of
// `table.setColumnFilters`: the table API auto-removes filters with empty
// values, but a just-added filter row legitimately starts with `value: ''`
// while the user is still building it.
const setColumnFilters = (filters: Array<ExtendedColumnFilter>) => {
  table.options.onColumnFiltersChange?.(filters)
}

const id = useId()
const labelId = useId()
const descriptionId = useId()
const listId = useId()
const open = ref(false)

const filterableColumns = computed(() =>
  table.getAllColumns().filter((column) => column.getCanFilter()),
)

function getColumnFilterVariant(column: Column<typeof features, RowData>) {
  if (column.columnDef.meta?.variant) {
    return column.columnDef.meta.variant
  }

  const firstValue = table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(column.id)

  if (Array.isArray(firstValue)) return 'multi-select'
  if (typeof firstValue === 'number') return 'number'
  if (firstValue instanceof Date) return 'date'

  return 'text'
}

function onFilterAddImpl(columnId: string): ExtendedColumnFilter | null {
  const column = filterableColumns.value.find((col) => col.id === columnId)
  if (!column) return null

  const filterVariant = getColumnFilterVariant(column)
  const operators = getFilterOperators(filterVariant)
  const defaultOperator = operators[0].value

  return {
    id: columnId,
    value: filterVariant === 'multi-select' ? [] : '',
    operator: defaultOperator,
    filterId: crypto.randomUUID(),
    joinOperator: 'and',
  }
}

function onFilterAdd() {
  const firstFilterableColumn = filterableColumns.value[0]

  const newFilter = onFilterAddImpl(firstFilterableColumn.id)
  if (newFilter) {
    setColumnFilters([...columnFilters.value, newFilter])
  }
}

function onFilterUpdate(
  filterId: string,
  updates: Partial<Omit<ExtendedColumnFilter, 'filterId'>>,
) {
  const newFilters = columnFilters.value.map((filter) => {
    if (filter.filterId === filterId) {
      if (updates.id) {
        const newColumn = filterableColumns.value.find(
          (col) => col.id === updates.id,
        )
        if (newColumn) {
          const filterVariant = getColumnFilterVariant(newColumn)
          const operators = getFilterOperators(filterVariant)
          const defaultOperator = operators[0].value
          return {
            ...filter,
            ...updates,
            operator: defaultOperator,
            value: filterVariant === 'multi-select' ? [] : '',
          }
        }
      }

      if (updates.operator && filter.value) {
        const column = filterableColumns.value.find(
          (col) => col.id === filter.id,
        )
        if (column && getColumnFilterVariant(column) === 'date') {
          const currentValue = filter.value
          if (updates.operator === 'inRange' && !Array.isArray(currentValue)) {
            return {
              ...filter,
              ...updates,
              value: [currentValue, undefined],
            }
          } else if (
            updates.operator !== 'inRange' &&
            Array.isArray(currentValue)
          ) {
            return {
              ...filter,
              ...updates,
              value: currentValue[0] ?? '',
            }
          }
        }
      }

      return { ...filter, ...updates }
    }
    return filter
  })
  setColumnFilters(newFilters)
}

function onFilterRemove(filterId: string) {
  setColumnFilters(
    columnFilters.value.filter((filter) => filter.filterId !== filterId),
  )
}

function onJoinOperatorChange(value: JoinOperator) {
  if (columnFilters.value.length > 0) {
    setColumnFilters(
      columnFilters.value.map((f) => ({ ...f, joinOperator: value })),
    )
  }
}

function getFilterColumn(filter: ExtendedColumnFilter) {
  return table.getColumn(filter.id)
}

function onTriggerPointerDown(event: PointerEvent) {
  const target = event.target
  if (!(target instanceof HTMLElement)) return
  if (target.hasPointerCapture(event.pointerId)) {
    target.releasePointerCapture(event.pointerId)
  }

  if (
    event.button === 0 &&
    event.ctrlKey === false &&
    event.pointerType === 'mouse'
  ) {
    event.preventDefault()
  }
}
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        variant="outline"
        size="sm"
        class="[&_svg]:size-3"
        @click="($event.currentTarget as HTMLElement).focus()"
        @pointerdown="onTriggerPointerDown"
      >
        <ListFilter />
        Filter
        <Badge
          v-if="columnFilters.length > 0"
          variant="secondary"
          class="h-[1.14rem] rounded-[0.2rem] px-[0.32rem] font-mono font-normal text-[0.65rem]"
        >
          {{ columnFilters.length }}
        </Badge>
      </Button>
    </PopoverTrigger>
    <PopoverContent
      :aria-describedby="descriptionId"
      :aria-labelledby="labelId"
      align="start"
      :collision-padding="16"
      class="flex flex-col gap-3 origin-(--reka-popover-content-transform-origin) p-4 w-[calc(100vw-theme(spacing.12))] min-w-60 sm:min-w-80 sm:w-fit sm:max-w-none"
    >
      <div class="flex flex-col gap-1">
        <h4 :id="labelId" class="font-medium leading-none">Filters</h4>
        <p
          :id="descriptionId"
          :class="
            cn(
              'text-sm text-muted-foreground',
              columnFilters.length > 0 && 'sr-only',
            )
          "
        >
          {{
            columnFilters.length > 0
              ? 'Modify filters to refine your results.'
              : 'Add filters to refine your results.'
          }}
        </p>
      </div>
      <div
        v-if="columnFilters.length > 0"
        role="list"
        :id="listId"
        class="flex max-h-[300px] flex-col gap-2 overflow-y-auto p-0.5"
      >
        <template v-for="(filter, index) in columnFilters" :key="filter.filterId">
          <div
            v-if="getFilterColumn(filter) && filter.filterId"
            role="listitem"
            :id="`${id}-filter-${filter.filterId}`"
            class="grid items-center grid-cols-[70px_135px_125px_minmax(0,200px)_32px] gap-2"
          >
            <span
              v-if="index === 0"
              class="text-sm text-center text-muted-foreground"
            >
              Where
            </span>
            <Select
              v-else-if="index === 1"
              :model-value="filter.joinOperator"
              @update:model-value="
                (value) => onJoinOperatorChange(value as JoinOperator)
              "
            >
              <SelectTrigger
                class="h-8"
                aria-label="Select join operator"
                :aria-controls="`${id}-filter-${filter.filterId}-join-operator-listbox`"
              >
                <SelectValue placeholder="Join" />
              </SelectTrigger>
              <SelectContent
                :id="`${id}-filter-${filter.filterId}-join-operator-listbox`"
                class="min-w-(--reka-select-trigger-width)"
              >
                <SelectItem value="and">and</SelectItem>
                <SelectItem value="or">or</SelectItem>
              </SelectContent>
            </Select>
            <span v-else class="text-sm text-center text-muted-foreground">
              {{ filter.joinOperator }}
            </span>
            <Popover>
              <PopoverTrigger as-child>
                <Button
                  role="combobox"
                  :id="`${id}-filter-${filter.filterId}-trigger`"
                  :aria-controls="`${id}-filter-${filter.filterId}-field-listbox`"
                  :aria-label="`Select filter field. Current: ${getFilterColumn(filter)!.columnDef.meta?.label ?? filter.id}`"
                  variant="outline"
                  size="sm"
                  class="h-8 justify-between font-normal focus:outline-none focus:ring-1 focus:ring-ring"
                  @pointerdown="onTriggerPointerDown"
                >
                  <span class="truncate">
                    {{
                      getFilterColumn(filter)!.columnDef.meta?.label ??
                      filter.id
                    }}
                  </span>
                  <ChevronsUpDown class="opacity-50" />
                </Button>
              </PopoverTrigger>
              <PopoverContent
                :id="`${id}-filter-${filter.filterId}-field-listbox`"
                class="w-(--reka-popover-trigger-width) p-0"
              >
                <Command>
                  <CommandInput
                    placeholder="Search columns..."
                    aria-label="Search filterable columns"
                  />
                  <CommandList>
                    <CommandEmpty>No column found.</CommandEmpty>
                    <CommandGroup>
                      <CommandItem
                        v-for="col in filterableColumns"
                        :key="col.id"
                        :value="col.id"
                        @select="onFilterUpdate(filter.filterId!, { id: col.id })"
                      >
                        <span class="truncate">
                          {{ col.columnDef.meta?.label ?? col.id }}
                        </span>
                        <Check
                          :class="
                            cn(
                              'ml-auto size-4',
                              col.id === filter.id
                                ? 'opacity-100'
                                : 'opacity-0',
                            )
                          "
                          aria-hidden="true"
                        />
                      </CommandItem>
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
            <Select
              :model-value="filter.operator ?? 'includesString'"
              @update:model-value="
                (value) =>
                  onFilterUpdate(filter.filterId!, {
                    operator: value as FilterOperator,
                  })
              "
            >
              <SelectTrigger
                class="h-8"
                aria-label="Select filter operator"
                :aria-controls="`${id}-filter-${filter.filterId}-operator-listbox`"
              >
                <SelectValue placeholder="Select operator" />
              </SelectTrigger>
              <SelectContent
                :id="`${id}-filter-${filter.filterId}-operator-listbox`"
              >
                <SelectItem
                  v-for="op in getFilterOperators(
                    getColumnFilterVariant(getFilterColumn(filter)!),
                  )"
                  :key="op.value"
                  :value="op.value"
                >
                  {{ op.label }}
                </SelectItem>
              </SelectContent>
            </Select>
            <DataTableFilterValueInput
              :column="getFilterColumn(filter)!"
              :filter="filter"
              :variant="getColumnFilterVariant(getFilterColumn(filter)!)"
              :operator="filter.operator ?? 'includesString'"
              :input-id="`${id}-filter-${filter.filterId}-input`"
              :on-filter-update="onFilterUpdate"
            />
            <Button
              variant="outline"
              size="icon"
              class="size-8 [&_svg]:size-3.5"
              :aria-label="`Remove ${getFilterColumn(filter)!.columnDef.meta?.label ?? filter.id} filter`"
              @click="onFilterRemove(filter.filterId!)"
            >
              <Trash2 />
            </Button>
          </div>
        </template>
      </div>
      <div class="flex items-center gap-2">
        <Button size="sm" aria-label="Add new filter" @click="onFilterAdd">
          Add filter
        </Button>
        <Button
          v-if="columnFilters.length > 0"
          aria-label="Reset all filters"
          variant="outline"
          size="sm"
          @click="setColumnFilters([])"
        >
          Reset filters
        </Button>
      </div>
    </PopoverContent>
  </Popover>
</template>
