// examples/react/shadcn-kitchen-sink/src/components/data-table/data-table-view-options.tsx
'use client'

import * as React from 'react'
import { Check, ChevronsUpDown, GripVertical, Settings2 } from 'lucide-react'
import type {
  ColumnOrderState,
  RowData,
  Table,
  TableFeatures,
} from '@tanstack/react-table'

import { Button } from '@/components/ui/button'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import { cn } from '@/lib/utils'
import {
  Sortable,
  SortableContent,
  SortableItem,
  SortableItemHandle,
  SortableOverlay,
} from '@/components/ui/sortable'

interface DataTableViewOptionsProps<
  TFeatures extends TableFeatures,
  TRowData extends RowData,
> {
  table: Table<Pick<TFeatures, 'columnVisibilityFeature'>, TRowData>
  columnOrder: ColumnOrderState
  onColumnOrderChange: (columnOrder: ColumnOrderState) => void
}

export function DataTableViewOptions<
  TFeatures extends TableFeatures,
  TRowData extends RowData,
>({
  table,
  columnOrder,
  onColumnOrderChange,
}: DataTableViewOptionsProps<TFeatures, TRowData>) {
  const triggerRef = React.useRef<HTMLButtonElement>(null)

  return (
    <Sortable value={columnOrder} onValueChange={onColumnOrderChange}>
      <Popover>
        <PopoverTrigger asChild>
          <Button
            ref={triggerRef}
            aria-label="Toggle columns"
            variant="outline"
            role="combobox"
            size="sm"
            className="ml-auto hidden h-8 gap-2 focus:outline-none focus:ring-1 focus:ring-ring lg:flex"
            onPointerDown={(event) => {
              // prevent implicit pointer capture
              // https://www.w3.org/TR/pointerevents3/#implicit-pointer-capture
              const target = event.target
              if (!(target instanceof HTMLElement)) return
              if (target.hasPointerCapture(event.pointerId)) {
                target.releasePointerCapture(event.pointerId)
              }

              if (
                event.button === 0 &&
                event.ctrlKey === false &&
                event.pointerType === 'mouse'
              ) {
                // prevent trigger from stealing focus from the active item after opening.
                event.preventDefault()
              }
            }}
          >
            <Settings2 />
            View
            <ChevronsUpDown className="ml-auto opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent
          align="end"
          className="w-full max-w-48 p-0"
          onCloseAutoFocus={() => triggerRef.current?.focus()}
        >
          <Command>
            <CommandInput placeholder="Search columns..." />
            <SortableContent asChild>
              <CommandList>
                <CommandEmpty>No columns found.</CommandEmpty>
                <CommandGroup>
                  {table
                    .getAllColumns()
                    .sort((a, b) => {
                      const aIndex = columnOrder.indexOf(a.id)
                      const bIndex = columnOrder.indexOf(b.id)
                      return aIndex - bIndex
                    })
                    .filter(
                      (column) => typeof column.accessorFn !== 'undefined',
                    )
                    .map((column) => (
                      <SortableItem key={column.id} value={column.id} asChild>
                        <CommandItem
                          aria-selected={column.getIsVisible()}
                          data-selected={column.getIsVisible()}
                          onSelect={() =>
                            column.toggleVisibility(!column.getIsVisible())
                          }
                        >
                          <Check
                            className={cn(
                              'size-4 shrink-0',
                              column.getIsVisible()
                                ? 'opacity-100'
                                : 'opacity-0',
                            )}
                          />
                          <span className="truncate">
                            {column.columnDef.meta?.label ?? column.id}
                          </span>
                          <SortableItemHandle asChild>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="ml-auto size-6"
                            >
                              <GripVertical />
                            </Button>
                          </SortableItemHandle>
                        </CommandItem>
                      </SortableItem>
                    ))}
                </CommandGroup>
                <CommandSeparator />
                <CommandGroup>
                  <div className="flex items-center gap-1">
                    <CommandItem
                      onSelect={() => table.toggleAllColumnsVisible(false)}
                      className="w-full justify-center border"
                    >
                      Hide All
                    </CommandItem>
                    <CommandItem
                      onSelect={() => table.toggleAllColumnsVisible(true)}
                      className="w-full justify-center border"
                    >
                      Show All
                    </CommandItem>
                  </div>
                </CommandGroup>
              </CommandList>
            </SortableContent>
          </Command>
        </PopoverContent>
      </Popover>
      <SortableOverlay>
        <div className="bg-primary/10 size-full" />
      </SortableOverlay>
    </Sortable>
  )
}

// examples/vue/kitchen-sink-shadcn/src/components/data-table/DataTableViewOptions.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ChevronsUpDown, Settings2 } from '@lucide/vue'
import { DragDropProvider } from 'dnd-kit-vue'
import { useTableContext } from '@/hooks/table'
import type { RowData, VueTable } from '@tanstack/vue-table'
import type { features } from '@/hooks/features'

import { Button } from '@/components/ui/button'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import DataTableViewOptionsItem from '@/components/data-table/DataTableViewOptionsItem.vue'

const table: VueTable<typeof features, RowData> = useTableContext()
const columnOrder = computed(() => table.atoms.columnOrder.get())

const orderedToggleableColumns = computed(() =>
  table
    .getAllColumns()
    .slice()
    .sort((a, b) => {
      const aIndex = columnOrder.value.indexOf(a.id)
      const bIndex = columnOrder.value.indexOf(b.id)
      return aIndex - bIndex
    })
    .filter((column) => typeof column.accessorFn !== 'undefined'),
)

function onDragEnd(event: { canceled: boolean; operation: { source: any } }) {
  if (event.canceled) return
  const source = event.operation.source
  const from = source?.sortable?.initialIndex
  const to = source?.sortable?.index
  if (from == null || to == null || from === to) return

  // Map the drag within the toggleable subset back onto the full column order.
  const draggableIds = orderedToggleableColumns.value.map((c) => c.id)
  const movedId = draggableIds[from]
  const targetId = draggableIds[to]
  const fullOrder = columnOrder.value.filter((id) => id !== movedId)
  const insertAt = fullOrder.indexOf(targetId) + (to > from ? 1 : 0)
  fullOrder.splice(insertAt, 0, movedId)
  table.setColumnOrder(fullOrder)
}

function onTriggerPointerDown(event: PointerEvent) {
  const target = event.target
  if (!(target instanceof HTMLElement)) return
  if (target.hasPointerCapture(event.pointerId)) {
    target.releasePointerCapture(event.pointerId)
  }

  if (
    event.button === 0 &&
    event.ctrlKey === false &&
    event.pointerType === 'mouse'
  ) {
    event.preventDefault()
  }
}
</script>

<template>
  <DragDropProvider @drag-end="onDragEnd">
    <Popover>
      <PopoverTrigger as-child>
        <Button
          aria-label="Toggle columns"
          variant="outline"
          role="combobox"
          size="sm"
          class="ml-auto hidden h-8 gap-2 focus:outline-none focus:ring-1 focus:ring-ring lg:flex"
          @pointerdown="onTriggerPointerDown"
        >
          <Settings2 />
          View
          <ChevronsUpDown class="ml-auto opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent align="end" class="w-full max-w-48 p-0">
        <Command>
          <CommandInput placeholder="Search columns..." />
          <CommandList>
            <CommandEmpty>No columns found.</CommandEmpty>
            <CommandGroup>
              <DataTableViewOptionsItem
                v-for="(column, index) in orderedToggleableColumns"
                :key="column.id"
                :column="column"
                :index="index"
              />
            </CommandGroup>
            <CommandSeparator />
            <CommandGroup>
              <div class="flex items-center gap-1">
                <CommandItem
                  value="hide-all"
                  class="w-full justify-center border"
                  @select="table.toggleAllColumnsVisible(false)"
                >
                  Hide All
                </CommandItem>
                <CommandItem
                  value="show-all"
                  class="w-full justify-center border"
                  @select="table.toggleAllColumnsVisible(true)"
                >
                  Show All
                </CommandItem>
              </div>
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  </DragDropProvider>
</template>
