// examples/angular/composable-tables/src/app/components/products-table/products-table.ts
import {
  ChangeDetectionStrategy,
  Component,
  Injector,
  inject,
  signal,
} from '@angular/core'
import { NgComponentOutlet } from '@angular/common'
import {
  FlexRender,
  TanStackTable,
  TanStackTableCell,
  TanStackTableHeader,
  flexRenderComponent,
} from '@tanstack/angular-table'
import { injectTanStackTableDevtools } from '@tanstack/angular-table-devtools'
import { makeProductData } from '../../makeData'
import { createAppColumnHelper, injectAppTable } from '../../table'
import type { Product } from '../../makeData'

export const productColumnHelper = createAppColumnHelper<Product>()

@Component({
  selector: 'products-table',
  templateUrl: './products-table.html',
  imports: [
    NgComponentOutlet,
    FlexRender,
    TanStackTable,
    TanStackTableHeader,
    TanStackTableCell,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductsTable {
  private readonly injector = inject(Injector)

  readonly data = signal(makeProductData(1_000))

  readonly columns = productColumnHelper.columns([
    productColumnHelper.display({
      id: 'select',
      header: ({ header }) => flexRenderComponent(header.SelectHeader),
      cell: ({ cell }) => flexRenderComponent(cell.SelectCell),
    }),
    productColumnHelper.accessor('name', {
      header: 'Product Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => cell.TextCell,
    }),
    productColumnHelper.accessor('category', {
      header: 'Category',
      footer: (props) => props.column.id,
      cell: ({ cell }) => cell.CategoryCell,
    }),
    productColumnHelper.accessor('price', {
      header: 'Price',
      footer: (props) => props.column.id,
      cell: ({ cell }) => cell.PriceCell,
    }),
    productColumnHelper.accessor('stock', {
      header: 'In Stock',
      footer: (props) => props.column.id,
      cell: ({ cell }) => cell.NumberCell,
    }),
    productColumnHelper.accessor('rating', {
      header: 'Rating',
      footer: (props) => props.column.id,
      cell: ({ cell }) => cell.ProgressCell,
    }),
  ])

  table = injectAppTable(() => ({
    key: 'products-table', // needed for devtools
    columns: this.columns,
    data: this.data(),
    getRowId: (row) => row.id,
    enableRowSelection: true,
    // more table options
  }))

  ngOnInit() {
    this.registerTableDevtools()
  }

  private registerTableDevtools() {
    injectTanStackTableDevtools(() => ({
      table: this.table,
      injector: this.injector,
    }))
  }

  onRefresh = () => {
    this.data.set([...makeProductData(1_000)])
  }

  refreshData = () => this.data.set(makeProductData(1_000))
  stressTest = () => this.data.set(makeProductData(1_000_000))
}

// examples/vue/composable-tables/src/components/ProductsTable.vue
<script setup lang="ts">
import { useTanStackTableDevtools } from '@tanstack/vue-table-devtools'
import { ref } from 'vue'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeProductData } from '../makeData'
import type { Product } from '../makeData'

const columnHelper = createAppColumnHelper<Product>()

const data = ref(makeProductData(1_000))

const columns = columnHelper.columns([
  columnHelper.display({
    id: 'select',
    header: ({ header }) => header.SelectAllHeader,
    cell: ({ cell }) => cell.SelectCell,
  }),
  columnHelper.accessor('name', {
    header: 'Product',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('category', {
    header: 'Category',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.CategoryCell,
  }),
  columnHelper.accessor('price', {
    header: 'Price',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.PriceCell,
  }),
  columnHelper.accessor('stock', {
    header: 'In Stock',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('rating', {
    header: 'Rating',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell,
  }),
])

function refreshData() {
  data.value = makeProductData(1_000)
}

function stressTest() {
  data.value = makeProductData(200_000)
}

const table = useAppTable({
  key: 'products-table', // needed for devtools
  debugTable: true,
  enableRowSelection: true,
  columns,
  data,
  initialState: {
    pagination: {
      pageIndex: 0,
      pageSize: 8,
    },
  },
})

useTanStackTableDevtools(table)
</script>

<template>
  <component :is="table.AppTable">
    <section class="table-container">
      <component
        :is="table.TableToolbar"
        title="Products Table"
        :onRefresh="refreshData"
        :onStressTest="stressTest"
      />

      <div class="table-scroll">
        <table>
          <thead>
            <tr
              v-for="headerGroup in table.getHeaderGroups()"
              :key="headerGroup.id"
            >
              <component
                :is="table.AppHeader"
                v-for="header in headerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appHeader }"
              >
                <th
                  :colspan="appHeader.colSpan"
                  :class="{ 'sortable-header': appHeader.column.getCanSort() }"
                  @click="appHeader.column.getToggleSortingHandler()?.($event)"
                >
                  <template v-if="!appHeader.isPlaceholder">
                    <component :is="appHeader.FlexRender" />
                    <component :is="appHeader.SortIndicator" />
                    <component :is="appHeader.ColumnFilter" />
                  </template>
                </th>
              </component>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in table.getRowModel().rows" :key="row.id">
              <component
                :is="table.AppCell"
                v-for="cell in row.getAllCells()"
                :key="cell.id"
                :cell="cell"
                v-slot="{ cell: appCell }"
              >
                <td>
                  <component :is="appCell.FlexRender" />
                </td>
              </component>
            </tr>
          </tbody>
          <tfoot>
            <tr
              v-for="footerGroup in table.getFooterGroups()"
              :key="footerGroup.id"
            >
              <component
                :is="table.AppFooter"
                v-for="header in footerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appFooter }"
              >
                <td :colspan="appFooter.colSpan">
                  <template v-if="!appFooter.isPlaceholder">
                    <component
                      :is="
                        ['price', 'stock', 'rating'].includes(
                          appFooter.column.id,
                        )
                          ? appFooter.FooterSum
                          : appFooter.FooterColumnId
                      "
                    />
                  </template>
                </td>
              </component>
            </tr>
          </tfoot>
        </table>
      </div>

      <component :is="table.PaginationControls" />
      <component :is="table.RowCount" />
    </section>
  </component>
</template>
