// examples/angular/composable-tables/src/app/components/users-table/users-table.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core'
import { NgComponentOutlet } from '@angular/common'
import {
  FlexRender,
  TanStackTable,
  TanStackTableCell,
  TanStackTableHeader,
  flexRenderComponent,
} from '@tanstack/angular-table'
import { injectTanStackTableDevtools } from '@tanstack/angular-table-devtools'
import { makeData } from '../../makeData'
import { createAppColumnHelper, injectAppTable } from '../../table'
import type { Person } from '../../makeData'

export const personColumnHelper = createAppColumnHelper<Person>()

@Component({
  selector: 'users-table',
  templateUrl: './users-table.html',
  imports: [
    NgComponentOutlet,
    FlexRender,
    TanStackTable,
    TanStackTableHeader,
    TanStackTableCell,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UsersTable {
  constructor() {
    injectTanStackTableDevtools(() => ({
      table: this.table,
    }))
  }
  readonly data = signal(makeData(1_000))

  readonly columns = personColumnHelper.columns([
    personColumnHelper.accessor('firstName', {
      header: 'First Name',
      footer: ({ header }) => flexRenderComponent(header.FooterColumnId),
      cell: ({ cell }) => flexRenderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('lastName', {
      header: 'Last Name',
      footer: ({ header }) => flexRenderComponent(header.FooterColumnId),
      cell: ({ cell }) => flexRenderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('age', {
      header: 'Age',
      footer: ({ header }) => flexRenderComponent(header.FooterSum),
      cell: ({ cell }) => flexRenderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('visits', {
      header: 'Visits',
      footer: ({ header }) => flexRenderComponent(header.FooterSum),
      cell: ({ cell }) => flexRenderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('status', {
      header: 'Status',
      footer: ({ header }) => flexRenderComponent(header.FooterColumnId),
      cell: ({ cell }) => flexRenderComponent(cell.StatusCell),
    }),
    personColumnHelper.accessor('progress', {
      header: 'Progress',
      footer: ({ header }) => flexRenderComponent(header.FooterSum),
      cell: ({ cell }) => flexRenderComponent(cell.ProgressCell),
    }),
    personColumnHelper.display({
      id: 'actions',
      header: 'Actions',
      cell: ({ cell }) => flexRenderComponent(cell.RowActionsCell),
    }),
  ])

  table = injectAppTable(() => ({
    key: 'users-table', // needed for devtools
    columns: this.columns,
    data: this.data(),
    debugTable: true,
    // more table options
  }))

  onRefresh = () => {
    this.data.set([...makeData(1_000)])
  }

  refreshData = () => this.data.set(makeData(1_000))
  stressTest = () => this.data.set(makeData(200_000))
}

// examples/vue/composable-tables/src/components/UsersTable.vue
<script setup lang="ts">
import { useTanStackTableDevtools } from '@tanstack/vue-table-devtools'
import { ref } from 'vue'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeData } from '../makeData'
import type { Person } from '../makeData'

const columnHelper = createAppColumnHelper<Person>()

const data = ref(makeData(1_000))

const columns = columnHelper.columns([
  columnHelper.accessor('firstName', {
    header: 'First Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('lastName', {
    header: 'Last Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('age', {
    header: 'Age',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('visits', {
    header: 'Visits',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('status', {
    header: 'Status',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.StatusCell,
  }),
  columnHelper.accessor('progress', {
    header: 'Progress',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell,
  }),
  columnHelper.display({
    id: 'actions',
    header: 'Actions',
    cell: ({ cell }) => cell.RowActionsCell,
  }),
])

function refreshData() {
  data.value = makeData(1_000)
}

function stressTest() {
  data.value = makeData(200_000)
}

const table = useAppTable({
  key: 'users-table', // needed for devtools
  debugTable: true,
  columns,
  data,
  initialState: {
    pagination: {
      pageIndex: 0,
      pageSize: 10,
    },
  },
})

useTanStackTableDevtools(table)

// Typed selector — avoids implicit 'any' for `state` in the template
function tableSelector(state: ReturnType<typeof table.store.get>) {
  return {
    sorting: state.sorting,
    columnFilters: state.columnFilters,
  }
}
</script>

<template>
  <component :is="table.AppTable" :selector="tableSelector" v-slot="{ state }">
    <section class="table-container">
      <component
        :is="table.TableToolbar"
        title="Users Table"
        :onRefresh="refreshData"
        :onStressTest="stressTest"
      />

      <table>
        <thead>
          <tr
            v-for="headerGroup in table.getHeaderGroups()"
            :key="headerGroup.id"
          >
            <component
              :is="table.AppHeader"
              v-for="header in headerGroup.headers"
              :key="header.id"
              :header="header"
              v-slot="{ header: appHeader }"
            >
              <th
                :colspan="appHeader.colSpan"
                :class="{ 'sortable-header': appHeader.column.getCanSort() }"
                @click="appHeader.column.getToggleSortingHandler()?.($event)"
              >
                <template v-if="!appHeader.isPlaceholder">
                  <component :is="appHeader.FlexRender" />
                  <component :is="appHeader.SortIndicator" />
                  <component :is="appHeader.ColumnFilter" />
                  <span v-if="state.sorting.length > 1" class="sort-indicator">
                    {{
                      state.sorting.findIndex(
                        (sort: { id: string }) =>
                          sort.id === appHeader.column.id,
                      ) + 1 || ''
                    }}
                  </span>
                </template>
              </th>
            </component>
          </tr>
        </thead>
        <tbody>
          <tr v-for="row in table.getRowModel().rows" :key="row.id">
            <component
              :is="table.AppCell"
              v-for="cell in row.getAllCells()"
              :key="cell.id"
              :cell="cell"
              v-slot="{ cell: appCell }"
            >
              <td>
                <component :is="appCell.FlexRender" />
              </td>
            </component>
          </tr>
        </tbody>
        <tfoot>
          <tr
            v-for="footerGroup in table.getFooterGroups()"
            :key="footerGroup.id"
          >
            <component
              :is="table.AppFooter"
              v-for="header in footerGroup.headers"
              :key="header.id"
              :header="header"
              v-slot="{ header: appFooter }"
            >
              <td :colspan="appFooter.colSpan">
                <template v-if="!appFooter.isPlaceholder">
                  <component
                    :is="
                      ['age', 'visits', 'progress'].includes(
                        appFooter.column.id,
                      )
                        ? appFooter.FooterSum
                        : appFooter.FooterColumnId
                    "
                  />
                </template>
              </td>
            </component>
          </tr>
        </tfoot>
      </table>

      <component :is="table.PaginationControls" />
      <component :is="table.RowCount" />
    </section>
  </component>
</template>
