// examples/svelte/composable-tables/src/components/UsersTable.svelte
<!--
  Users Table Component - uses createAppTable and composable components.
-->
<script lang="ts">
  import { FlexRender, renderComponent } from '@tanstack/svelte-table'
  import { createAppColumnHelper, createAppTable } from '../hooks/table'
  import { makeData } from '../makeData'
  import type { Person } from '../makeData'

  // Create column helper with TFeatures already bound - only need TData!
  const personColumnHelper = createAppColumnHelper<Person>()

  // Data state
  let data = $state(makeData(1_000))

  // Refresh data callback
  function refreshData() {
    data = makeData(1_000)
  }
  function stressTest() {
    data = makeData(1_000_000)
  }

  // Define columns using the column helper
  // NOTE: You must use `createAppColumnHelper` instead of `createColumnHelper`
  // when using pre-bound components like cell.TextCell
  const columns = personColumnHelper.columns([
    personColumnHelper.display({
      id: 'select',
      header: ({ header }) => renderComponent(header.SelectHeader),
      cell: ({ cell }) => renderComponent(cell.SelectCell),
    }),
    personColumnHelper.accessor('firstName', {
      header: 'First Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('lastName', {
      header: 'Last Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('age', {
      header: 'Age',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('visits', {
      header: 'Visits',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('status', {
      header: 'Status',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.StatusCell),
    }),
    personColumnHelper.accessor('progress', {
      header: 'Progress',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.ProgressCell),
    }),
    personColumnHelper.display({
      id: 'actions',
      header: 'Actions',
      cell: ({ cell }) => renderComponent(cell.RowActionsCell),
    }),
  ])

  // Create the table - features and rowModels are already configured!
  const table = createAppTable({
    columns,
    get data() {
      return data
    },
    enableRowSelection: true,
    debugTable: true,
  })

  // Reactive derived values from table state.
  // Reading table.state creates a $state dependency (via the notifier)
  // that triggers re-renders when any table state changes.
  let sorting = $derived(table.state.sorting)
  let columnFilters = $derived(table.state.columnFilters)

  // IMPORTANT: Derive rows from table state so Svelte tracks the dependency.
  // We must read a $state value that changes on every table update.
  // JSON.stringify forces a deep read, ensuring Svelte sees the dependency.
  const rows = $derived.by(() => {
    data
    JSON.stringify(table.state)
    return table.getRowModel().rows
  })
</script>

<table.AppTable>
  <div class="table-container">
    <!-- Table toolbar using pre-bound component -->
    <table.TableToolbar
      title="Users Table"
      onRefresh={refreshData}
      onStressTest={stressTest}
    />

    <!-- Table element -->
    <div class="table-scroll">
    <table>
      <thead>
        {#each table.getHeaderGroups() as headerGroup (headerGroup.id)
        }
          <tr>
            {#each headerGroup.headers as h (h.id)}
              <table.AppHeader header={h
              }>
                {#snippet children(header)}
                  <th
                    colSpan={header.colSpan}
                    class={header.column.getCanSort() ? 'sortable-header' : ''}
                    onclick={header.column.getToggleSortingHandler()}
                  >
                    {#if !header.isPlaceholder}
                      <header.FlexRender
                        header={header}
                      />
                      <header.SortIndicator />
                      <header.ColumnFilter />
                      <!-- Show sort order number when multiple columns sorted -->
                      {#if sorting.length > 1 && sorting.findIndex((s) => s.id === header.column.id) > -1}
                        <span class="sort-order">
                          {sorting.findIndex((s) => s.id === header.column.id) + 1}
                        </span>
                      {/if}
                    {/if}
                  </th>
                {/snippet}
              </table.AppHeader>
            {/each
            }
          </tr>
        {/each}
      </thead>
      <tbody>
        {#each rows as row (row.id + JSON.stringify(row.original))}
          <tr>
            {#each row.getAllCells() as c (c.id)}
              <table.AppCell cell={c
              }>
                {#snippet children(cell)}
                  <td>
                    <FlexRender cell={cell} />
                  </td>
                {/snippet}
              </table.AppCell>
            {/each
            }
          </tr>
        {/each}
      </tbody>
      <tfoot>
        {#each table.getFooterGroups() as footerGroup (footerGroup.id)}
          <tr>
            {#each footerGroup.headers as f (f.id)}
              <table.AppFooter header={f
              }>
                {#snippet children(footer)}
                  <td colSpan={footer.colSpan}>
                    {#if !footer.isPlaceholder}
                      {#if footer.column.id === 'age' || footer.column.id === 'visits' || footer.column.id === 'progress'}
                        <footer.FooterSum />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> (filtered)</span>
                        {/if}
                      {:else if footer.column.id === 'actions'}
                        <!-- no footer for actions -->
                      {:else}
                        <footer.FooterColumnId />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> ✓</span>
                        {/if}
                      {/if}
                    {/if}
                  </td>
                {/snippet}
              </table.AppFooter>
            {/each
            }
          </tr>
        {/each}
      </tfoot>
    </table>
    </div>

    <!-- Pagination using pre-bound component -->
    <table.PaginationControls />

    <!-- Row count using pre-bound component -->
    <table.RowCount />
  </div>
</table.AppTable>

// examples/vue/composable-tables/src/components/UsersTable.vue
<script setup lang="ts">
import { useTanStackTableDevtools } from '@tanstack/vue-table-devtools'
import { computed, ref } from 'vue'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeData } from '../makeData'
import type { Person } from '../makeData'

const columnHelper = createAppColumnHelper<Person>()

const data = ref(makeData(1_000))

const columns = columnHelper.columns([
  columnHelper.display({
    id: 'select',
    header: ({ header }) => header.SelectAllHeader,
    cell: ({ cell }) => cell.SelectCell,
  }),
  columnHelper.accessor('firstName', {
    header: 'First Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('lastName', {
    header: 'Last Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('age', {
    header: 'Age',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('visits', {
    header: 'Visits',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('status', {
    header: 'Status',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.StatusCell,
  }),
  columnHelper.accessor('progress', {
    header: 'Progress',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell,
  }),
  columnHelper.display({
    id: 'actions',
    header: 'Actions',
    cell: ({ cell }) => cell.RowActionsCell,
  }),
])

function refreshData() {
  data.value = makeData(1_000)
}

function stressTest() {
  data.value = makeData(200_000)
}

const table = useAppTable({
  key: 'users-table', // needed for devtools
  debugTable: true,
  enableRowSelection: true,
  columns,
  data,
  initialState: {
    pagination: {
      pageIndex: 0,
      pageSize: 10,
    },
  },
})

useTanStackTableDevtools(table)

const sorting = computed(() => table.atoms.sorting.get())
</script>

<template>
  <component :is="table.AppTable">
    <section class="table-container">
      <component
        :is="table.TableToolbar"
        title="Users Table"
        :onRefresh="refreshData"
        :onStressTest="stressTest"
      />

      <div class="table-scroll">
        <table>
          <thead>
            <tr
              v-for="headerGroup in table.getHeaderGroups()"
              :key="headerGroup.id"
            >
              <component
                :is="table.AppHeader"
                v-for="header in headerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appHeader }"
              >
                <th
                  :colspan="appHeader.colSpan"
                  :class="{ 'sortable-header': appHeader.column.getCanSort() }"
                  @click="appHeader.column.getToggleSortingHandler()?.($event)"
                >
                  <template v-if="!appHeader.isPlaceholder">
                    <component :is="appHeader.FlexRender" />
                    <component :is="appHeader.SortIndicator" />
                    <component :is="appHeader.ColumnFilter" />
                    <span v-if="sorting.length > 1" class="sort-indicator">
                      {{
                        sorting.findIndex(
                          (sort: { id: string }) =>
                            sort.id === appHeader.column.id,
                        ) + 1 || ''
                      }}
                    </span>
                  </template>
                </th>
              </component>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="row in table.getRowModel().rows"
              :key="row.id + JSON.stringify(row.original)"
            >
              <component
                :is="table.AppCell"
                v-for="cell in row.getAllCells()"
                :key="cell.id"
                :cell="cell"
                v-slot="{ cell: appCell }"
              >
                <td>
                  <component :is="appCell.FlexRender" />
                </td>
              </component>
            </tr>
          </tbody>
          <tfoot>
            <tr
              v-for="footerGroup in table.getFooterGroups()"
              :key="footerGroup.id"
            >
              <component
                :is="table.AppFooter"
                v-for="header in footerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appFooter }"
              >
                <td :colspan="appFooter.colSpan">
                  <template v-if="!appFooter.isPlaceholder">
                    <component
                      :is="
                        ['age', 'visits', 'progress'].includes(
                          appFooter.column.id,
                        )
                          ? appFooter.FooterSum
                          : appFooter.FooterColumnId
                      "
                    />
                  </template>
                </td>
              </component>
            </tr>
          </tfoot>
        </table>
      </div>

      <component :is="table.PaginationControls" />
      <component :is="table.RowCount" />
    </section>
  </component>
</template>
