// examples/vue/kitchen-sink-shadcn/src/components/ui/faceted/Faceted.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { Popover } from '@/components/ui/popover'
import { provideFacetedContext } from '.'

const props = defineProps<{
  modelValue?: string | Array<string>
  multiple?: boolean
}>()

const emits = defineEmits<{
  'update:modelValue': [value: string | Array<string> | undefined]
}>()

const open = ref(false)

function onItemSelect(selectedValue: string) {
  if (props.multiple) {
    const currentValue = Array.isArray(props.modelValue) ? props.modelValue : []
    const newValue = currentValue.includes(selectedValue)
      ? currentValue.filter((v) => v !== selectedValue)
      : [...currentValue, selectedValue]
    emits('update:modelValue', newValue)
  } else {
    if (props.modelValue === selectedValue) {
      emits('update:modelValue', undefined)
    } else {
      emits('update:modelValue', selectedValue)
    }

    requestAnimationFrame(() => {
      open.value = false
    })
  }
}

provideFacetedContext({
  value: computed(() => props.modelValue),
  multiple: computed(() => props.multiple ?? false),
  onItemSelect,
})
</script>

<template>
  <Popover v-model:open="open">
    <slot />
  </Popover>
</template>

// examples/svelte/kitchen-sink-shadcn/src/lib/components/ui/faceted/faceted.svelte
<!-- Root of the faceted filter combobox — a popover + command palette that
  supports single or multiple selection. Port of the react example's faceted.tsx. -->
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { Popover } from '@/lib/components/ui/popover'
  import { setFacetedContext } from './faceted-context'

  let {
    value,
    onValueChange,
    multiple = false,
    children,
  }: {
    value?: string | Array<string>
    onValueChange?: (value: string | Array<string> | undefined) => void
    multiple?: boolean
    children?: Snippet
  } = $props()

  let open = $state(false)

  function onItemSelect(selectedValue: string) {
    if (!onValueChange) return

    if (multiple) {
      const currentValue = Array.isArray(value) ? value : []
      const newValue = currentValue.includes(selectedValue)
        ? currentValue.filter((v) => v !== selectedValue)
        : [...currentValue, selectedValue]
      onValueChange(newValue)
    } else {
      onValueChange(value === selectedValue ? undefined : selectedValue)

      requestAnimationFrame(() => {
        open = false
      })
    }
  }

  setFacetedContext({
    get value() {
      return value
    },
    get multiple() {
      return multiple
    },
    onItemSelect,
  })
</script>

<Popover bind:open>
  {@render children?.()}
</Popover>
