// examples/vue/kitchen-sink-shadcn/src/components/ui/faceted/FacetedContent.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { PopoverContent } from '@/components/ui/popover'
import { Command } from '@/components/ui/command'
import { cn } from '@/lib/utils'

const props = defineProps<{
  id?: string
  class?: HTMLAttributes['class']
}>()
</script>

<template>
  <PopoverContent
    :id="props.id"
    data-slot="faceted-content"
    align="start"
    :class="
      cn(
        'w-[200px] origin-(--reka-popover-content-transform-origin) p-0',
        props.class,
      )
    "
  >
    <Command>
      <slot />
    </Command>
  </PopoverContent>
</template>

// examples/svelte/kitchen-sink-shadcn/src/lib/components/ui/faceted/faceted-content.svelte
<script lang="ts">
  import type { ComponentProps } from 'svelte'
  import { PopoverContent } from '@/lib/components/ui/popover'
  import { Command } from '@/lib/components/ui/command'
  import { cn } from '@/lib/utils'
  import { useFacetedContext } from './faceted-context'

  let {
    class: className,
    children,
    ...restProps
  }: ComponentProps<typeof PopoverContent> = $props()

  // Assert the context so misuse fails loudly, like the react version.
  useFacetedContext('FacetedContent')
</script>

<PopoverContent
  data-slot="faceted-content"
  align="start"
  class={cn('w-[200px] origin-(--transform-origin) p-0', className)}
  {...restProps}
>
  <Command>
    {@render children?.()}
  </Command>
</PopoverContent>
