// packages/solid-table-devtools/src/index.ts
import { isDev } from 'solid-js/web'
import * as plugin from './plugin'
import * as Devtools from './TableDevtools'

export const TableDevtoolsPanel = !isDev
  ? Devtools.TableDevtoolsPanelNoOp
  : Devtools.TableDevtoolsPanel

export const tableDevtoolsPlugin = !isDev
  ? plugin.tableDevtoolsNoOpPlugin
  : plugin.tableDevtoolsPlugin

export type { TableDevtoolsSolidInit } from './TableDevtools'
export type { TableDevtoolsPluginOptions } from './plugin'

// packages/angular-table-devtools/src/index.ts
import { isDevMode } from '@angular/core'
import * as plugin from './plugin'
import * as Devtools from './TableDevtools'
import * as inject from './injectTanStackTableDevtools'

export const TableDevtoolsPanel = isDevMode()
  ? Devtools.TableDevtoolsPanel
  : Devtools.TableDevtoolsPanelNoOp

export const tableDevtoolsPlugin = isDevMode()
  ? plugin.tableDevtoolsPlugin
  : plugin.tableDevtoolsNoOpPlugin

export type { TableDevtoolsAngularInit } from './TableDevtools'

export type { InjectTanStackTableDevtoolsOptions } from './injectTanStackTableDevtools'

export const injectTanStackTableDevtools = isDevMode()
  ? inject.injectTanStackTableDevtools
  : inject.injectTanStackTableDevtoolsNoOp
