// packages/angular-table/src/index.ts
import { computed, signal } from '@angular/core'
import {
  RowData,
  TableOptions,
  TableOptionsResolved,
  TableState,
  createTable,
  type Table,
} from '@tanstack/table-core'
import { lazyInit } from './lazy-signal-initializer'
import { proxifyTable } from './proxy'

export * from '@tanstack/table-core'

export { FlexRenderDirective } from './flex-render'

export function createAngularTable<TData extends RowData>(
  options: () => TableOptions<TData>
): Table<TData> {
  return lazyInit(() => {
    const resolvedOptions = {
      state: {},
      onStateChange: () => {},
      renderFallbackValue: null,
      ...options(),
    }

    const table = createTable(resolvedOptions)

    // By default, manage table state here using the table's initial state
    const state = signal<TableState>(table.initialState)

    // Compose table options using computed.
    // This is to allow `tableSignal` to listen and set table option
    const updatedOptions = computed<TableOptionsResolved<TData>>(() => {
      // listen to table state changed
      const tableState = state()
      // listen to input options changed
      const tableOptions = options()
      return {
        ...table.options,
        ...resolvedOptions,
        ...tableOptions,
        state: { ...tableState, ...tableOptions.state },
        onStateChange: updater => {
          const value =
            updater instanceof Function ? updater(tableState) : updater
          state.set(value)
          resolvedOptions.onStateChange?.(updater)
        },
      }
    })

    // convert table instance to signal for proxify to listen to any table state and options changes
    const tableSignal = computed(
      () => {
        table.setOptions(updatedOptions())
        return table
      },
      {
        equal: () => false,
      }
    )

    // proxify Table instance to provide ability for consumer to listen to any table state changes
    return proxifyTable(tableSignal)
  })
}

// packages/qwik-table/src/index.tsx
import * as Qwik from '@builder.io/qwik'
export * from '@tanstack/table-core'

import {
  TableOptions,
  TableOptionsResolved,
  RowData,
  createTable,
  type Table,
} from '@tanstack/table-core'

export const flexRender = (comp: any, attrs: any) => {
  // TODO: this might not handle all cases I'm not sure? Probably needs to be tested
  if (typeof comp === 'function') {
    return comp(attrs)
  }

  return comp
}

export function useQwikTable<TData extends RowData>(
  options: TableOptions<TData>
) {
  // Compose in the generic options to the user options
  const resolvedOptions: TableOptionsResolved<TData> = {
    state: {},
    onStateChange: () => {},
    renderFallbackValue: null,
    ...options,
  }

  const table = Qwik.useStore<{
    instance: Qwik.NoSerialize<Table<TData>>
  }>({
    instance: Qwik.noSerialize(createTable(resolvedOptions)),
  })

  // By default, manage table state here using the table's initial state
  let state = Qwik.useStore(table.instance!.initialState)

  // Compose the default state above with any user state. This will allow the user
  // to only control a subset of the state if desired.
  table.instance!.setOptions(prev => ({
    ...prev,
    ...options,
    state: {
      ...state,
      ...options.state,
    },
    onStateChange: updater => {
      state = updater instanceof Function ? updater(state) : updater
      options.onStateChange?.(updater)
    },
  }))

  return table.instance!
}
