// examples/solid/with-tanstack-router/src/components/debouncedInput.tsx
import { createEffect, createSignal, onCleanup } from 'solid-js'

type DebouncedInputProps = {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
  class?: string
  type?: string
  placeholder?: string
}

export function DebouncedInput(props: DebouncedInputProps) {
  const [value, setValue] = createSignal<string | number>(props.value)

  createEffect(() => {
    setValue(() => props.value)
  })

  createEffect(() => {
    const currentValue = value()
    const timeout = setTimeout(() => {
      props.onChange(currentValue)
    }, props.debounce ?? 200)
    onCleanup(() => clearTimeout(timeout))
  })

  return (
    <input
      type={props.type ?? 'text'}
      value={value()}
      onInput={(e) => {
        if (e.currentTarget.value === '') {
          setValue('')
        } else if (props.type === 'number') {
          setValue(e.currentTarget.valueAsNumber)
        } else {
          setValue(e.currentTarget.value)
        }
      }}
      placeholder={props.placeholder}
      class={props.class}
    />
  )
}

// examples/react/query-router-search-params/src/components/debouncedInput.tsx
import { useEffect, useState } from 'react'
import type { InputHTMLAttributes } from 'react'

export function DebouncedInput({
  value: initialValue,
  onChange,
  debounce = 200,
  ...props
}: {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'>) {
  const [value, setValue] = useState<string | number>(initialValue)

  useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  useEffect(() => {
    const timeout = setTimeout(() => {
      onChange(value)
    }, debounce)

    return () => clearTimeout(timeout)
  }, [value])

  return (
    <input
      {...props}
      value={value ?? ''}
      onChange={(e) => {
        if (e.target.value === '') return setValue('')
        if (props.type === 'number') {
          setValue(e.target.valueAsNumber)
        } else {
          setValue(e.target.value)
        }
      }}
    />
  )
}
