// examples/solid/basic-app-table/src/index.tsx
import { render } from 'solid-js/web'
import { TanStackDevtools } from '@tanstack/solid-devtools'
import { tableDevtoolsPlugin } from '@tanstack/solid-table-devtools'
import './index.css'
import { App } from './App'

render(
  () => (
    <>
      <App />
      <TanStackDevtools plugins={[tableDevtoolsPlugin()]} />
    </>
  ),
  document.getElementById('root') as HTMLElement,
)

// examples/solid/with-tanstack-query/src/index.tsx
import { render } from '@solidjs/web'
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query'
import './index.css'
import App from './App'

const queryClient = new QueryClient()

render(
  () => (
    <QueryClientProvider client={queryClient}>
      <App />
    </QueryClientProvider>
  ),
  document.getElementById('root') as HTMLElement,
)
