// examples/svelte/realtime-trading/src/shell/AppHeader.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useMarketFeedController } from './trading-shell-context'
  const { sidebarOpen, onSidebarToggle }: { sidebarOpen: boolean; onSidebarToggle: () => void } = $props()
  const state = useSelector(useMarketFeedController().store, ({ workerReady, running }) => ({ workerReady, running }))
</script>

<header class="app-bar">
  <div class="brand"><strong>MARKET MONITOR</strong></div>
  <div class="header-actions">
    <span class:is-running={state.current.workerReady && state.current.running} class="feed-status" data-testid="feed-status"><span class="status-dot" aria-hidden="true"></span>{!state.current.workerReady ? 'FEED CONNECTING' : state.current.running ? 'FEED LIVE' : 'FEED PAUSED'}</span>
    <button class="sidebar-toggle" type="button" aria-expanded={sidebarOpen} aria-controls="benchmark-configurator" aria-label={sidebarOpen ? 'Close configurator' : 'Open configurator'} onclick={onSidebarToggle}>
      <svg viewBox="0 0 20 20" aria-hidden="true"><rect x="2.5" y="3" width="15" height="14" rx="1.5"></rect><path d="M12.5 3v14"></path></svg>
    </button>
  </div>
</header>

// examples/lit/realtime-trading/src/shell/AppHeader.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { ControllerElement } from './controller-element'
import type { MarketFeedController } from '../feed/market-feed-controller'

@customElement('trading-app-header')
export class AppHeader extends ControllerElement {
  @property({ attribute: false }) feed!: MarketFeedController
  @property({ type: Boolean }) sidebarOpen = true
  @property({ attribute: false }) toggleSidebar: () => void = () => undefined
  protected firstUpdated() {
    this.observe(this.feed.store)
  }
  protected render() {
    const state = this.feed.store.get()
    return html`<header class="app-bar">
      <div class="brand"><strong>MARKET MONITOR</strong></div>
      <div class="header-actions">
        <span
          class="feed-status ${state.workerReady && state.running ? 'is-running' : ''}"
          data-testid="feed-status"
          ><span class="status-dot" aria-hidden="true"></span
          >${!state.workerReady ? 'FEED CONNECTING' : state.running ? 'FEED LIVE' : 'FEED PAUSED'}</span
        ><button
          class="sidebar-toggle"
          type="button"
          aria-expanded=${this.sidebarOpen}
          aria-controls="benchmark-configurator"
          aria-label=${this.sidebarOpen ? 'Close configurator' : 'Open configurator'}
          @click=${this.toggleSidebar}
        >
          <svg viewBox="0 0 20 20" aria-hidden="true">
            <rect x="2.5" y="3" width="15" height="14" rx="1.5"></rect>
            <path d="M12.5 3v14"></path>
          </svg>
        </button>
      </div>
    </header>`
  }
}
