// examples/svelte/realtime-trading/src/shell/MetricsStrip.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useTradingShellController } from './trading-shell-context'
  const state = useSelector(useTradingShellController().store, ({ metrics, longAnimationFramesSupported }) => ({ metrics, longAnimationFramesSupported }))
  const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
  const formatMs = (value: number) => `${value.toFixed(2)} ms`
  const metrics = $derived(state.current.metrics)
  const items = $derived([
    { label: 'WORKER SAMPLES', value: rate.format(metrics.actualTicksPerSecond), detail: 'generated samples/s', testId: 'actual-rate' },
    { label: 'ROW UPDATES', value: rate.format(metrics.rowUpdatesPerSecond), detail: 'unique rows applied/s', testId: 'row-update-rate' },
    { label: 'MESSAGES', value: metrics.workerMessagesPerSecond.toFixed(1), detail: 'worker messages/s', testId: 'message-rate' },
    { label: 'STATE APPLIES', value: metrics.stateApplicationsPerSecond.toFixed(1), detail: 'quote snapshots/s', testId: 'state-apply-rate' },
    { label: 'TABLE COMMITS', value: metrics.tableRendersPerSecond.toFixed(1), detail: 'completed renders/s', testId: 'table-render-rate' },
    { label: 'AVG RENDER', value: formatMs(metrics.averageRenderMs), detail: 'mutation → render' },
    { label: 'P95 RENDER', value: formatMs(metrics.p95RenderMs), detail: `max ${formatMs(metrics.maxRenderMs)}` },
    { label: 'LONG FRAMES', value: state.current.longAnimationFramesSupported ? String(metrics.longAnimationFrames) : 'N/A', detail: state.current.longAnimationFramesSupported ? `worst ${formatMs(metrics.worstLongAnimationFrameMs)}` : 'unsupported', testId: 'long-frame-count' },
  ])
</script>

<section class="metrics-strip" aria-label="Live performance metrics">
  {#each items as item (item.label)}<article><span>{item.label}</span><strong data-testid={item.testId}>{item.value}</strong><small>{item.detail}</small></article>{/each}
</section>

// examples/lit/realtime-trading/src/shell/MetricsStrip.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { repeat } from 'lit/directives/repeat.js'
import { ControllerElement } from './controller-element'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

const rate = new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 })
const ms = (value: number) => `${value.toFixed(2)} ms`
@customElement('trading-metrics-strip')
export class MetricsStrip extends ControllerElement {
  @property({ attribute: false }) controller!: TradingBenchmarkController
  protected firstUpdated() { this.observe(this.controller.store) }
  protected render() {
    const state = this.controller.store.get(); const metrics = state.metrics
    const items = [
      ['WORKER SAMPLES', rate.format(metrics.actualTicksPerSecond), 'generated samples/s', 'actual-rate'],
      ['ROW UPDATES', rate.format(metrics.rowUpdatesPerSecond), 'unique rows applied/s', 'row-update-rate'],
      ['MESSAGES', metrics.workerMessagesPerSecond.toFixed(1), 'worker messages/s', 'message-rate'],
      ['STATE APPLIES', metrics.stateApplicationsPerSecond.toFixed(1), 'quote snapshots/s', 'state-apply-rate'],
      ['TABLE COMMITS', metrics.tableRendersPerSecond.toFixed(1), 'completed renders/s', 'table-render-rate'],
      ['AVG RENDER', ms(metrics.averageRenderMs), 'mutation → render', ''],
      ['P95 RENDER', ms(metrics.p95RenderMs), `max ${ms(metrics.maxRenderMs)}`, ''],
      ['LONG FRAMES', state.longAnimationFramesSupported ? String(metrics.longAnimationFrames) : 'N/A', state.longAnimationFramesSupported ? `worst ${ms(metrics.worstLongAnimationFrameMs)}` : 'unsupported', 'long-frame-count'],
    ] as const
    return html`<section class="metrics-strip" aria-label="Live performance metrics">${repeat(items, (item) => item[0], (item) => html`<article><span>${item[0]}</span><strong data-testid=${item[3] || undefined}>${item[1]}</strong><small>${item[2]}</small></article>`)}</section>`
  }
}
