// examples/svelte/realtime-trading/src/shell/SelectedInstrument.svelte
<script lang="ts">
  import { useSelector } from '@tanstack/svelte-store'
  import { useMarketFeedController, useTradingShellController } from './trading-shell-context'
  const feed = useMarketFeedController()
  const selectedSymbol = useSelector(useTradingShellController().renderAtoms.selectedSymbol)
  const quotes = useSelector(feed.quotes)
  const selectedQuote = $derived(feed.getQuoteBySymbol(quotes.current, selectedSymbol.current))
</script>

<section class="config-section selected-instrument" data-testid="selected-instrument">
  <h2>SELECTED INSTRUMENT</h2>
  {#if selectedQuote}
    <div class="selection"><div><strong>{selectedQuote.symbol}</strong><span>{selectedQuote.company}</span></div><small>{selectedQuote.venue}</small></div>
    <dl><div><dt>Last</dt><dd>{selectedQuote.price.toFixed(2)}</dd></div><div><dt>Bid / ask</dt><dd>{selectedQuote.bid.toFixed(2)} / {selectedQuote.ask.toFixed(2)}</dd></div></dl>
  {:else}<p>Click or begin a cell selection in any row to inspect its instrument.</p>{/if}
</section>

// examples/lit/realtime-trading/src/shell/SelectedInstrument.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { ControllerElement } from './controller-element'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

@customElement('trading-selected-instrument')
export class SelectedInstrument extends ControllerElement {
  @property({ attribute: false }) controller!: TradingBenchmarkController
  @property({ attribute: false }) feed!: MarketFeedController
  protected firstUpdated() { this.observe(this.controller.renderAtoms.selectedSymbol); this.observe(this.feed.store) }
  protected render() {
    const quote = this.feed.getQuoteBySymbol(this.feed.store.get().quotes, this.controller.renderAtoms.selectedSymbol.get())
    return html`<section class="config-section selected-instrument" data-testid="selected-instrument"><h2>SELECTED INSTRUMENT</h2>${quote ? html`<div class="selection"><div><strong>${quote.symbol}</strong><span>${quote.company}</span></div><small>${quote.venue}</small></div><dl><div><dt>Last</dt><dd>${quote.price.toFixed(2)}</dd></div><div><dt>Bid / ask</dt><dd>${quote.bid.toFixed(2)} / ${quote.ask.toFixed(2)}</dd></div></dl>` : html`<p>Click or begin a cell selection in any row to inspect its instrument.</p>`}</section>`
  }
}
