// examples/vue/composable-tables/src/components/ProductsTable.vue
<script setup lang="ts">
import { useTanStackTableDevtools } from '@tanstack/vue-table-devtools'
import { ref } from 'vue'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeProductData } from '../makeData'
import type { Product } from '../makeData'

const columnHelper = createAppColumnHelper<Product>()

const data = ref(makeProductData(1_000))

const columns = columnHelper.columns([
  columnHelper.display({
    id: 'select',
    header: ({ header }) => header.SelectAllHeader,
    cell: ({ cell }) => cell.SelectCell,
  }),
  columnHelper.accessor('name', {
    header: 'Product',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell,
  }),
  columnHelper.accessor('category', {
    header: 'Category',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.CategoryCell,
  }),
  columnHelper.accessor('price', {
    header: 'Price',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.PriceCell,
  }),
  columnHelper.accessor('stock', {
    header: 'In Stock',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell,
  }),
  columnHelper.accessor('rating', {
    header: 'Rating',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell,
  }),
])

function refreshData() {
  data.value = makeProductData(1_000)
}

function stressTest() {
  data.value = makeProductData(200_000)
}

const table = useAppTable({
  key: 'products-table', // needed for devtools
  debugTable: true,
  enableRowSelection: true,
  columns,
  data,
  initialState: {
    pagination: {
      pageIndex: 0,
      pageSize: 8,
    },
  },
})

useTanStackTableDevtools(table)
</script>

<template>
  <component :is="table.AppTable">
    <section class="table-container">
      <component
        :is="table.TableToolbar"
        title="Products Table"
        :onRefresh="refreshData"
        :onStressTest="stressTest"
      />

      <div class="table-scroll">
        <table>
          <thead>
            <tr
              v-for="headerGroup in table.getHeaderGroups()"
              :key="headerGroup.id"
            >
              <component
                :is="table.AppHeader"
                v-for="header in headerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appHeader }"
              >
                <th
                  :colspan="appHeader.colSpan"
                  :class="{ 'sortable-header': appHeader.column.getCanSort() }"
                  @click="appHeader.column.getToggleSortingHandler()?.($event)"
                >
                  <template v-if="!appHeader.isPlaceholder">
                    <component :is="appHeader.FlexRender" />
                    <component :is="appHeader.SortIndicator" />
                    <component :is="appHeader.ColumnFilter" />
                  </template>
                </th>
              </component>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="row in table.getRowModel().rows"
              :key="row.id + JSON.stringify(row.original)"
            >
              <component
                :is="table.AppCell"
                v-for="cell in row.getAllCells()"
                :key="cell.id"
                :cell="cell"
                v-slot="{ cell: appCell }"
              >
                <td>
                  <component :is="appCell.FlexRender" />
                </td>
              </component>
            </tr>
          </tbody>
          <tfoot>
            <tr
              v-for="footerGroup in table.getFooterGroups()"
              :key="footerGroup.id"
            >
              <component
                :is="table.AppFooter"
                v-for="header in footerGroup.headers"
                :key="header.id"
                :header="header"
                v-slot="{ header: appFooter }"
              >
                <td :colspan="appFooter.colSpan">
                  <template v-if="!appFooter.isPlaceholder">
                    <component
                      :is="
                        ['price', 'stock', 'rating'].includes(
                          appFooter.column.id,
                        )
                          ? appFooter.FooterSum
                          : appFooter.FooterColumnId
                      "
                    />
                  </template>
                </td>
              </component>
            </tr>
          </tfoot>
        </table>
      </div>

      <component :is="table.PaginationControls" />
      <component :is="table.RowCount" />
    </section>
  </component>
</template>

// examples/svelte/composable-tables/src/components/ProductsTable.svelte
<!--
  Products Table Component - uses the same createAppTable hook and components as UsersTable,
  but with different data types and column configurations.
-->
<script lang="ts">
  import { FlexRender, renderComponent } from '@tanstack/svelte-table'
  import { createAppColumnHelper, createAppTable } from '../hooks/table'
  import { makeProductData } from '../makeData'
  import type { Product } from '../makeData'

  // Create column helper with TFeatures already bound - only need TData!
  const productColumnHelper = createAppColumnHelper<Product>()

  // Data state
  let data = $state(makeProductData(1_000))

  // Refresh data callback
  function refreshData() {
    data = makeProductData(1_000)
  }
  function stressTest() {
    data = makeProductData(1_000_000)
  }

  // Define columns using the column helper - different structure than Users table
  const columns = productColumnHelper.columns([
    productColumnHelper.display({
      id: 'select',
      header: ({ header }) => renderComponent(header.SelectHeader),
      cell: ({ cell }) => renderComponent(cell.SelectCell),
    }),
    productColumnHelper.accessor('name', {
      header: 'Product Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell, {}),
    }),
    productColumnHelper.accessor('category', {
      header: 'Category',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.CategoryCell, {}),
    }),
    productColumnHelper.accessor('price', {
      header: 'Price',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.PriceCell, {}),
    }),
    productColumnHelper.accessor('stock', {
      header: 'In Stock',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell, {}),
    }),
    productColumnHelper.accessor('rating', {
      header: 'Rating',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.ProgressCell, {}),
    }),
  ])

  // Create the table using the same createAppTable hook
  const table = createAppTable({
    debugTable: true,
    columns,
    get data() {
      return data
    },
    getRowId: (row) => row.id,
    enableRowSelection: true,
  })

  const sorting = $derived(table.atoms.sorting.get())
  const columnFilters = $derived(table.atoms.columnFilters.get())
  const rows = $derived(table.getRowModel().rows)
</script>

<table.AppTable>
  <div class="table-container">
    <!-- Table toolbar using the same pre-bound component -->
    <table.TableToolbar
      title="Products Table"
      onRefresh={refreshData}
      onStressTest={stressTest}
    />

    <!-- Table element -->
    <div class="table-scroll">
    <table>
      <thead>
        {#each table.getHeaderGroups() as headerGroup (headerGroup.id)
        }
          <tr>
            {#each headerGroup.headers as h (h.id)}
              <table.AppHeader header={h
              }>
                {#snippet children(header)}
                  <th
                    colSpan={header.colSpan}
                    class={header.column.getCanSort() ? 'sortable-header' : ''}
                    onclick={header.column.getToggleSortingHandler()}
                  >
                    {#if !header.isPlaceholder}
                      <header.FlexRender
                        header={header}
                      />
                      <header.SortIndicator />
                      <header.ColumnFilter />
                      <!-- Show sort order number when multiple columns sorted -->
                      {#if sorting.length > 1 && sorting.findIndex((s) => s.id === header.column.id) > -1}
                        <span class="sort-order">
                          {sorting.findIndex((s) => s.id === header.column.id) + 1}
                        </span>
                      {/if}
                    {/if}
                  </th>
                {/snippet}
              </table.AppHeader>
            {/each
            }
          </tr>
        {/each}
      </thead>
      <tbody>
        {#each rows as row (row.id + JSON.stringify(row.original))}
          <tr>
            {#each row.getAllCells() as c (c.id)}
              <table.AppCell cell={c
              }>
                {#snippet children(cell)}
                  <td>
                    <FlexRender cell={cell} />
                  </td>
                {/snippet}
              </table.AppCell>
            {/each
            }
          </tr>
        {/each}
      </tbody>
      <tfoot>
        {#each table.getFooterGroups() as footerGroup (footerGroup.id)}
          <tr>
            {#each footerGroup.headers as f (f.id)}
              <table.AppFooter header={f
              }>
                {#snippet children(footer)}
                  <td colSpan={footer.colSpan}>
                    {#if !footer.isPlaceholder}
                      {#if footer.column.id === 'price' || footer.column.id === 'stock' || footer.column.id === 'rating'}
                        <footer.FooterSum />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> (filtered)</span>
                        {/if}
                      {:else}
                        <footer.FooterColumnId />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> ✓</span>
                        {/if}
                      {/if}
                    {/if}
                  </td>
                {/snippet}
              </table.AppFooter>
            {/each
            }
          </tr>
        {/each}
      </tfoot>
    </table>
    </div>

    <!-- Pagination using the same pre-bound component -->
    <table.PaginationControls />

    <!-- Row count using the same pre-bound component -->
    <table.RowCount />
  </div>
</table.AppTable>
