// examples/lit/composable-tables/src/components/users-table.ts
import { LitElement, html, nothing } from 'lit'
import { customElement, state } from 'lit/decorators.js'
import { createAppColumnHelper, useAppTable } from '../hooks/table'
import { makeData } from '../makeData'
import type { Person } from '../makeData'
// Import table-level custom elements so they are registered
import './table-components'

// Create the column helper pre-bound with features — only need the data type!
const personColumnHelper = createAppColumnHelper<Person>()

// Define columns using the column helper.
// NOTE: Use createAppColumnHelper (not createColumnHelper) to get pre-bound
// component types on cell/header objects (e.g., cell.TextCell, header.SortIndicator).
const columns = personColumnHelper.columns([
  personColumnHelper.accessor('firstName', {
    header: 'First Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell(),
  }),
  personColumnHelper.accessor('lastName', {
    header: 'Last Name',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.TextCell(),
  }),
  personColumnHelper.accessor('age', {
    header: 'Age',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell(),
  }),
  personColumnHelper.accessor('visits', {
    header: 'Visits',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.NumberCell(),
  }),
  personColumnHelper.accessor('status', {
    header: 'Status',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.StatusCell(),
  }),
  personColumnHelper.accessor('progress', {
    header: 'Progress',
    footer: (props) => props.column.id,
    cell: ({ cell }) => cell.ProgressCell(),
  }),
  personColumnHelper.display({
    id: 'actions',
    header: 'Actions',
    cell: ({ cell }) => cell.RowActionsCell(),
  }),
])

@customElement('users-table')
export class UsersTable extends LitElement {
  @state()
  private data = makeData(1000)

  // Create the table — features and rowModels are already configured!
  // NOTE: We capture `this` (the LitElement) as `host` because inside the
  // object literal's getter, `this` would refer to the options object itself
  // (causing infinite recursion if we wrote `get data() { return this.data }`).
  private appTable = (() => {
    const host = this
    return useAppTable(
      this,
      {
        columns,
        get data() {
          return host.data
        },
        debugTable: true,
      },
      (state) => ({
        pagination: state.pagination,
        sorting: state.sorting,
        columnFilters: state.columnFilters,
      }),
    )
  })()

  private refreshData = () => {
    this.data = makeData(1000)
  }

  createRenderRoot() {
    return this
  }

  protected render() {
    const table = this.appTable.table()
    const { sorting, columnFilters } = table.state

    return html`
      <div class="table-container">
        <!-- Table toolbar using context-based custom element -->
        <table-toolbar
          .title=${'Users Table'}
          .onRefresh=${this.refreshData}
          .onStressTest=${() => {
            this.data = makeData(200_000)
          }}
        ></table-toolbar>

        <!-- Table element -->
        <table>
          <thead>
            ${table.getHeaderGroups().map(
              (headerGroup) => html`
                <tr>
                  ${headerGroup.headers.map((h) =>
                    table.AppHeader(
                      h,
                      (header) => html`
                        <th
                          colspan=${header.colSpan}
                          class=${header.column.getCanSort()
                            ? 'sortable-header'
                            : ''}
                          @click=${header.column.getToggleSortingHandler()}
                        >
                          ${header.isPlaceholder
                            ? nothing
                            : html`
                                ${header.FlexRender()} ${header.SortIndicator()}
                                ${header.ColumnFilter()}
                                ${sorting.length > 1 &&
                                sorting.findIndex(
                                  (s) => s.id === header.column.id,
                                ) > -1
                                  ? html`<span class="sort-order"
                                      >${sorting.findIndex(
                                        (s) => s.id === header.column.id,
                                      ) + 1}</span
                                    >`
                                  : nothing}
                              `}
                        </th>
                      `,
                    ),
                  )}
                </tr>
              `,
            )}
          </thead>
          <tbody>
            ${table.getRowModel().rows.map(
              (row) => html`
                <tr>
                  ${row
                    .getAllCells()
                    .map((c) =>
                      table.AppCell(
                        c,
                        (cell) => html` <td>${cell.FlexRender()}</td> `,
                      ),
                    )}
                </tr>
              `,
            )}
          </tbody>
          <tfoot>
            ${table.getFooterGroups().map(
              (footerGroup) => html`
                <tr>
                  ${footerGroup.headers.map((f) =>
                    table.AppFooter(f, (footer) => {
                      const columnId = footer.column.id
                      const hasFilter = columnFilters.some(
                        (cf) => cf.id === columnId,
                      )
                      return html`
                        <td colspan=${footer.colSpan}>
                          ${footer.isPlaceholder
                            ? nothing
                            : columnId === 'age' ||
                                columnId === 'visits' ||
                                columnId === 'progress'
                              ? html`
                                  ${footer.FooterSum()}
                                  ${hasFilter
                                    ? html`<span class="filtered-indicator">
                                        (filtered)</span
                                      >`
                                    : nothing}
                                `
                              : columnId === 'actions'
                                ? nothing
                                : html`
                                    ${footer.FooterColumnId()}
                                    ${hasFilter
                                      ? html`<span class="filtered-indicator">
                                          ✓</span
                                        >`
                                      : nothing}
                                  `}
                        </td>
                      `
                    }),
                  )}
                </tr>
              `,
            )}
          </tfoot>
        </table>

        <!-- Pagination and row count using context-based custom elements -->
        <pagination-controls></pagination-controls>
        <row-count></row-count>
      </div>
    `
  }
}

// examples/svelte/composable-tables/src/components/UsersTable.svelte
<!--
  Users Table Component - uses createAppTable and composable components.
-->
<script lang="ts">
  import { FlexRender, renderComponent } from '@tanstack/svelte-table'
  import { createAppColumnHelper, createAppTable } from '../hooks/table'
  import { makeData } from '../makeData'
  import type { Person } from '../makeData'

  // Create column helper with TFeatures already bound - only need TData!
  const personColumnHelper = createAppColumnHelper<Person>()

  // Data state
  let data = $state(makeData(1_000))

  // Refresh data callback
  function refreshData() {
    data = makeData(1_000)
  }
  function stressTest() {
    data = makeData(200_000)
  }

  // Define columns using the column helper
  // NOTE: You must use `createAppColumnHelper` instead of `createColumnHelper`
  // when using pre-bound components like cell.TextCell
  const columns = personColumnHelper.columns([
    personColumnHelper.display({
      id: 'select',
      header: ({ header }) => renderComponent(header.SelectHeader),
      cell: ({ cell }) => renderComponent(cell.SelectCell),
    }),
    personColumnHelper.accessor('firstName', {
      header: 'First Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('lastName', {
      header: 'Last Name',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.TextCell),
    }),
    personColumnHelper.accessor('age', {
      header: 'Age',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('visits', {
      header: 'Visits',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.NumberCell),
    }),
    personColumnHelper.accessor('status', {
      header: 'Status',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.StatusCell),
    }),
    personColumnHelper.accessor('progress', {
      header: 'Progress',
      footer: (props) => props.column.id,
      cell: ({ cell }) => renderComponent(cell.ProgressCell),
    }),
    personColumnHelper.display({
      id: 'actions',
      header: 'Actions',
      cell: ({ cell }) => renderComponent(cell.RowActionsCell),
    }),
  ])

  // Create the table - features and rowModels are already configured!
  const table = createAppTable({
    columns,
    get data() {
      return data
    },
    enableRowSelection: true,
    debugTable: true,
  })

  // Reactive derived values from table state.
  // Reading table.state creates a $state dependency (via the notifier)
  // that triggers re-renders when any table state changes.
  let sorting = $derived(table.state.sorting)
  let columnFilters = $derived(table.state.columnFilters)

  // IMPORTANT: Derive rows from table state so Svelte tracks the dependency.
  // We must read a $state value that changes on every table update.
  // JSON.stringify forces a deep read, ensuring Svelte sees the dependency.
  const rows = $derived.by(() => {
    JSON.stringify(table.state)
    return table.getRowModel().rows
  })
</script>

<table.AppTable>
  <div class="table-container">
    <!-- Table toolbar using pre-bound component -->
    <table.TableToolbar
      title="Users Table"
      onRefresh={refreshData}
      onStressTest={stressTest}
    />

    <!-- Table element -->
    <div class="table-scroll">
    <table>
      <thead>
        {#each table.getHeaderGroups() as headerGroup (headerGroup.id)
        }
          <tr>
            {#each headerGroup.headers as h (h.id)}
              <table.AppHeader header={h
              }>
                {#snippet children(header)}
                  <th
                    colSpan={header.colSpan}
                    class={header.column.getCanSort() ? 'sortable-header' : ''}
                    onclick={header.column.getToggleSortingHandler()}
                  >
                    {#if !header.isPlaceholder}
                      <header.FlexRender
                        header={header}
                      />
                      <header.SortIndicator />
                      <header.ColumnFilter />
                      <!-- Show sort order number when multiple columns sorted -->
                      {#if sorting.length > 1 && sorting.findIndex((s) => s.id === header.column.id) > -1}
                        <span class="sort-order">
                          {sorting.findIndex((s) => s.id === header.column.id) + 1}
                        </span>
                      {/if}
                    {/if}
                  </th>
                {/snippet}
              </table.AppHeader>
            {/each
            }
          </tr>
        {/each}
      </thead>
      <tbody>
        {#each rows as row (row.id)}
          <tr>
            {#each row.getAllCells() as c (c.id)}
              <table.AppCell cell={c
              }>
                {#snippet children(cell)}
                  <td>
                    <FlexRender cell={cell} />
                  </td>
                {/snippet}
              </table.AppCell>
            {/each
            }
          </tr>
        {/each}
      </tbody>
      <tfoot>
        {#each table.getFooterGroups() as footerGroup (footerGroup.id)}
          <tr>
            {#each footerGroup.headers as f (f.id)}
              <table.AppFooter header={f
              }>
                {#snippet children(footer)}
                  <td colSpan={footer.colSpan}>
                    {#if !footer.isPlaceholder}
                      {#if footer.column.id === 'age' || footer.column.id === 'visits' || footer.column.id === 'progress'}
                        <footer.FooterSum />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> (filtered)</span>
                        {/if}
                      {:else if footer.column.id === 'actions'}
                        <!-- no footer for actions -->
                      {:else}
                        <footer.FooterColumnId />
                        {#if columnFilters.some((cf) => cf.id === footer.column.id)}
                          <span class="filtered-indicator"> ✓</span>
                        {/if}
                      {/if}
                    {/if}
                  </td>
                {/snippet}
              </table.AppFooter>
            {/each
            }
          </tr>
        {/each}
      </tfoot>
    </table>
    </div>

    <!-- Pagination using pre-bound component -->
    <table.PaginationControls />

    <!-- Row count using pre-bound component -->
    <table.RowCount />
  </div>
</table.AppTable>
