// examples/svelte/lib-shadcn/src/lib/components/ui/select/select-separator.svelte
<script lang="ts">
	import { Separator } from "../separator/index.js";
	import { cn } from "@/lib/utils";
	import type { Separator as SeparatorPrimitive } from "bits-ui";

	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: SeparatorPrimitive.RootProps = $props();
</script>

<Separator
	bind:ref
	data-slot="select-separator"
	class={cn("-mx-1 my-1 h-px bg-border pointer-events-none", className)}
	{...restProps}
/>

// examples/vue/lib-shadcn/src/components/ui/select/SelectSeparator.vue
<script setup lang="ts">
import { reactiveOmit } from '@vueuse/core'
import { SelectSeparator } from 'reka-ui'
import type { SelectSeparatorProps } from 'reka-ui'
import type { HTMLAttributes } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<
  SelectSeparatorProps & { class?: HTMLAttributes['class'] }
>()

const delegatedProps = reactiveOmit(props, 'class')
</script>

<template>
  <SelectSeparator
    data-slot="select-separator"
    v-bind="delegatedProps"
    :class="cn('bg-border pointer-events-none -mx-1 my-1 h-px', props.class)"
  />
</template>
