// examples/svelte/realtime-trading/src/table/TradingTable.svelte
<script lang="ts">
  import { get } from 'svelte/store'
  import { onMount, tick } from 'svelte'
  import { useSelector } from '@tanstack/svelte-store'
  import { FlexRender, createFilteredRowModel, createSortedRowModel, createTable, filterFn_includesString, sortFn_basic, stockFeatures, tableFeatures } from '@tanstack/svelte-table'
  import { createVirtualizer } from '@tanstack/svelte-virtual'
  import { startTableBenchmark } from '../benchmark/table-benchmark'
  import { useMarketFeedController, useTradingShellController } from '../shell/trading-shell-context'
  import { TRADING_COLUMN_COUNT, readMeasuredRows, rowModelDiagnostics, tradingColumns } from './table-config/trading-columns'
  import { TradingGridPointerController, handleCellNavigation, reorderColumnIds, sortAriaValue, sortIndicator } from './table-interactions'
  import { TRADING_ROW_HEIGHT, TRADING_ROW_OVERSCAN, resolveVirtualScrollMode } from './trading-row-virtualizer'
  import type { MarketQuote } from '../feed/market-data'
  import type { VirtualItem } from '@tanstack/svelte-virtual'

  export { TRADING_COLUMN_COUNT, rowModelDiagnostics }

  const features = tableFeatures({
    ...stockFeatures,
    filteredRowModel: createFilteredRowModel(),
    sortedRowModel: createSortedRowModel(),
    filterFns: { includesString: filterFn_includesString },
    sortFns: { basic: sortFn_basic },
  })
  const controller = useTradingShellController()
  const feed = useMarketFeedController()
  const quotes = useSelector(feed.quotes)
  const instrumentCount = useSelector(feed.instrumentCount)
  const benchmarkState = useSelector(controller.store)
  const selectedSymbol = useSelector(controller.renderAtoms.selectedSymbol)
  const table = createTable({
    key: 'svelte-realtime-trading',
    features,
    columns: tradingColumns,
    get data() { return quotes.current },
    getRowId: (row: MarketQuote) => row.id,
    columnResizeMode: 'onChange',
    defaultColumn: { minSize: 56, maxSize: 800 },
    autoResetCellSelection: false,
  })
  const tableState = useSelector(table.store, (state) => ({
    sorting: state.sorting,
    columnFilters: state.columnFilters,
    columnOrder: state.columnOrder,
    rowSelection: state.rowSelection,
    cellSelection: state.cellSelection,
  }))
  const virtualScrollMode = $derived(resolveVirtualScrollMode(benchmarkState.current.requestedVirtualScrollMode, instrumentCount.current))
  const rows = $derived.by(() => {
    void quotes.current
    void tableState.current
    return readMeasuredRows(() => table.getRowModel().rows)
  })
  const refs = $state<{ scroll: HTMLDivElement | null; table: HTMLTableElement | null }>({ scroll: null, table: null })
  const rowVirtualizer = createVirtualizer({
    count: 0,
    estimateSize: () => TRADING_ROW_HEIGHT,
    getScrollElement: () => refs.scroll,
    getItemKey: (index) => rows[index]?.id ?? index,
    overscan: TRADING_ROW_OVERSCAN,
    enabled: false,
  })
  const virtualRows = $derived($rowVirtualizer.getVirtualItems())
  const visibleRange = $derived.by(() => {
    const range = $rowVirtualizer.range
    if (virtualScrollMode !== 'tanstack' || rows.length === 0 || range === null) return null
    const lastIndex = rows.length - 1
    const start = Math.min(range.startIndex, lastIndex)
    return { start, end: Math.min(Math.max(start, range.endIndex), lastIndex) }
  })
  const pointerInteractions = new TradingGridPointerController()
  const drag = { columnId: null as string | null, sourceElement: null as HTMLTableCellElement | null, targetElement: null as HTMLTableCellElement | null }
  const layout = { manuallyResized: false }

  $effect(() => {
    get(rowVirtualizer).setOptions({
      count: rows.length,
      estimateSize: () => TRADING_ROW_HEIGHT,
      getScrollElement: () => refs.scroll,
      getItemKey: (index) => rows[index]?.id ?? index,
      overscan: TRADING_ROW_OVERSCAN,
      enabled: virtualScrollMode === 'tanstack',
    })
  })
  $effect(() => { controller.actions.setRenderedRowCount(virtualScrollMode === 'tanstack' ? virtualRows.length : rows.length) })
  $effect(() => { void quotes.current; tick().then(() => feed.completeRender()) })

  const writeColumnSizes = (): void => {
    if (!refs.table) return
    for (const header of table.getFlatHeaders()) {
      refs.table.style.setProperty(`--header-${header.id}-size`, String(header.getSize()))
      refs.table.style.setProperty(`--col-${header.column.id}-size`, String(header.column.getSize()))
    }
    refs.table.style.width = `${table.getTotalSize()}px`
  }
  const fitAvailableWidth = (): void => {
    if (!refs.scroll || layout.manuallyResized) return
    const width = table.getTotalSize()
    if (refs.scroll.clientWidth <= width + 1 || width <= 0) return
    const ratio = refs.scroll.clientWidth / width
    table.setColumnSizing(Object.fromEntries(table.getVisibleLeafColumns().map((column) => [column.id, column.getSize() * ratio])))
  }
  const clearColumnDrag = (): void => {
    drag.sourceElement?.classList.remove('is-column-dragging')
    drag.targetElement?.classList.remove('is-column-drop-target')
    drag.columnId = null; drag.sourceElement = null; drag.targetElement = null
  }
  const showColumnDropTarget = (columnId: string, element: HTMLTableCellElement | null): void => {
    drag.targetElement?.classList.remove('is-column-drop-target')
    drag.targetElement = null
    if (drag.columnId === columnId || !element) return
    element.classList.add('is-column-drop-target')
    drag.targetElement = element
  }
  const isTextColumn = (columnId: string): boolean => columnId === 'market' || columnId === 'name' || columnId === 'symbol'

  onMount(() => {
    const resizeObserver = new ResizeObserver(fitAvailableWidth)
    const sizing = table.atoms.columnSizing.subscribe(writeColumnSizes)
    const order = table.atoms.columnOrder.subscribe(writeColumnSizes)
    const resizing = table.atoms.columnResizing.subscribe((state) => { if (state.isResizingColumn !== false) layout.manuallyResized = true })
    tick().then(() => { writeColumnSizes(); fitAvailableWidth(); if (refs.scroll) resizeObserver.observe(refs.scroll) })
    const stopBenchmark = startTableBenchmark(controller)
    feed.completeRender()
    return () => { sizing.unsubscribe(); order.unsubscribe(); resizing.unsubscribe(); resizeObserver.disconnect(); stopBenchmark() }
  })
</script>

{#snippet renderRow(row: (typeof rows)[number], virtualRow?: VirtualItem)}
  <tr class:virtual-table-row={Boolean(virtualRow)} style:transform={virtualRow ? `translateY(${virtualRow.start}px)` : undefined} data-virtual-index={virtualRow?.index} data-symbol={row.original.symbol} data-row-id={row.original.id} data-symbol-selected={selectedSymbol.current === row.original.symbol ? 'true' : undefined} title={row.original.company} aria-selected={row.getIsSelected()}>
    {#each row.getVisibleCells() as cell (cell.id)}{@const edges = cell.getSelectionEdges()}<td style:width={`calc(var(--col-${cell.column.id}-size) * 1px)`} data-column-id={cell.column.id} data-cell-focused={cell.getIsFocused() || undefined} data-selection-top={edges.top || undefined} data-selection-right={edges.right || undefined} data-selection-bottom={edges.bottom || undefined} data-selection-left={edges.left || undefined} aria-selected={cell.getIsSelected()} tabindex={cell.getTabIndex()}><FlexRender {cell} /></td>{/each}
  </tr>
{/snippet}

<div bind:this={refs.scroll} class:is-virtualized={virtualScrollMode === 'tanstack'} class="table-scroll" data-trading-table>
  <table bind:this={refs.table} class:virtual-table={virtualScrollMode === 'tanstack'} class="trading-data-grid" data-testid="trading-table" role="grid" aria-multiselectable="true" tabindex="0" onkeydown={(event) => handleCellNavigation(table, event)}>
    <thead>
      {#each table.getHeaderGroups() as headerGroup (headerGroup.id)}<tr>
        {#each headerGroup.headers as header (header.id)}
          {@const isLeaf = header.subHeaders.length === 0}{@const sorted = header.column.getIsSorted()}
          <th colspan={header.colSpan} style:width={`calc(var(--header-${header.id}-size) * 1px)`} aria-sort={isLeaf ? sortAriaValue(sorted) : undefined} class:column-group-header={!isLeaf} class:numeric-header={isLeaf && !isTextColumn(header.column.id)}>
            {#if !header.isPlaceholder}
              {#if isLeaf}
                <div role="group" class="leaf-header-content" ondragover={(event) => { event.preventDefault(); showColumnDropTarget(header.column.id, (event.currentTarget as HTMLElement).closest('th')) }} ondrop={(event) => { event.preventDefault(); const sourceId = event.dataTransfer?.getData('text/plain') || drag.columnId; if (sourceId) table.setColumnOrder(reorderColumnIds(table.getVisibleLeafColumns().map((column) => column.id), sourceId, header.column.id)); clearColumnDrag() }}>
                  <button type="button" class="column-drag-handle" draggable="true" aria-label={`Move ${header.column.id} column`} ondragstart={(event) => { drag.columnId = header.column.id; drag.sourceElement = (event.currentTarget as HTMLElement).closest('th'); drag.sourceElement?.classList.add('is-column-dragging'); if (event.dataTransfer) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', header.column.id) } }} ondragend={clearColumnDrag}>⋮⋮</button>
                  <button type="button" class:is-sortable={header.column.getCanSort()} class="sort-header-button" disabled={!header.column.getCanSort()} onclick={header.column.getToggleSortingHandler()}><span class="header-label"><FlexRender {header} /></span>{#if header.column.getCanSort()}<span class:is-active={Boolean(sorted)} class="sort-indicator" aria-hidden="true">{sortIndicator(sorted)}</span>{/if}</button>
                </div>
                {#if header.column.getCanResize()}<!-- svelte-ignore a11y_no_noninteractive_element_interactions --><div class:is-resizing={header.column.getIsResizing()} class="column-resize-handle" role="separator" aria-orientation="vertical" tabindex="-1" ondblclick={() => header.column.resetSize()} onmousedown={header.getResizeHandler()} ontouchstart={header.getResizeHandler()}></div>{/if}
              {:else}<FlexRender {header} />{/if}
            {/if}
          </th>
        {/each}
      </tr>{/each}
    </thead>
    <!-- Delegated table-grid pointer handling intentionally lives on one tbody. -->
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <tbody class:virtual-table-body={virtualScrollMode === 'tanstack'} style:height={virtualScrollMode === 'tanstack' ? `${rows.length * TRADING_ROW_HEIGHT}px` : undefined} data-source-row-count={quotes.current.length} onmousedown={(event) => pointerInteractions.handleMouseDown(table, event, controller.actions.selectSymbol)} onpointerover={(event) => pointerInteractions.handlePointerOver(table, event)} onmouseleave={() => pointerInteractions.resetPointerCell()} onclick={(event) => pointerInteractions.handleClick(table, event)}>
      {#if virtualScrollMode === 'tanstack'}
        {#each virtualRows as virtualRow (virtualRow.key)}{@render renderRow(rows[virtualRow.index], virtualRow)}{/each}
      {:else}
        {#each rows as row (row.id)}{@render renderRow(row)}{/each}
      {/if}
    </tbody>
  </table>
</div>
{#if virtualScrollMode === 'tanstack'}<footer class="virtual-scroll-footer" data-testid="virtual-scroll-footer"><span>TanStack · Total · {rows.length} rows · {table.getVisibleLeafColumns().length} columns</span><span data-testid="visible-row-range">{visibleRange ? `Current · rows ${visibleRange.start}..${visibleRange.end}` : 'Current · rows —'}</span></footer>{/if}

// examples/lit/realtime-trading/src/table/TradingTable.ts
import { html } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import { repeat } from 'lit/directives/repeat.js'
import { createRef, ref } from 'lit/directives/ref.js'
import { VirtualizerController } from '@tanstack/lit-virtual'
import { FlexRender, TableController, createFilteredRowModel, createSortedRowModel, filterFn_includesString, sortFn_basic, stockFeatures, tableFeatures } from '@tanstack/lit-table'
import { startTableBenchmark } from '../benchmark/table-benchmark'
import { ControllerElement } from '../shell/controller-element'
import { createTradingColumns, readMeasuredRows } from './table-config/trading-columns'
import { TradingGridPointerController, handleCellNavigation, reorderColumnIds, sortAriaValue, sortIndicator } from './table-interactions'
import { TRADING_ROW_HEIGHT, TRADING_ROW_OVERSCAN, resolveVirtualScrollMode } from './trading-row-virtualizer'
import './table-config/quote-cells'
import type { Ref } from 'lit/directives/ref.js'
import type { LitTable } from '@tanstack/lit-table'
import type { MarketQuote } from '../feed/market-data'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

const features = tableFeatures({
  ...stockFeatures,
  filteredRowModel: createFilteredRowModel(), sortedRowModel: createSortedRowModel(),
  filterFns: { includesString: filterFn_includesString }, sortFns: { basic: sortFn_basic },
})
interface SelectedTableState {
  sorting: unknown
  columnFilters: unknown
  columnOrder: unknown
  rowSelection: unknown
  cellSelection: unknown
}
type TradingTableInstance = LitTable<typeof features, MarketQuote, SelectedTableState>

@customElement('trading-data-table')
export class TradingTable extends ControllerElement {
  @property({ attribute: false }) controller!: TradingBenchmarkController
  @property({ attribute: false }) feed!: MarketFeedController
  readonly #tableController = new TableController<typeof features, MarketQuote>(this)
  readonly #scrollRef: Ref<HTMLDivElement> = createRef()
  readonly #tableRef: Ref<HTMLTableElement> = createRef()
  readonly #virtualizer = new VirtualizerController<HTMLDivElement, HTMLTableRowElement>(this, {
    count: 0, getScrollElement: () => this.#scrollRef.value ?? null,
    estimateSize: () => TRADING_ROW_HEIGHT, overscan: TRADING_ROW_OVERSCAN,
  })
  readonly #pointer = new TradingGridPointerController()
  readonly #drag = { columnId: null as string | null, source: null as HTMLTableCellElement | null, target: null as HTMLTableCellElement | null }
  readonly #layout = { manuallyResized: false }
  #table?: TradingTableInstance
  #columns?: ReturnType<typeof createTradingColumns<typeof features>>
  #cleanup: Array<() => void> = []

  protected firstUpdated() {
    this.observe(this.feed.store); this.observe(this.controller.store); this.observe(this.controller.renderAtoms.rendererMode); this.observe(this.controller.renderAtoms.selectedSymbol)
    const table = this.#table
    if (!table) return
    const sizing = table.atoms.columnSizing.subscribe(() => this.#writeColumnSizes())
    const order = table.atoms.columnOrder.subscribe(() => this.#writeColumnSizes())
    const resizing = table.atoms.columnResizing.subscribe((state) => { if (state.isResizingColumn !== false) this.#layout.manuallyResized = true })
    const resizeObserver = new ResizeObserver(() => this.#fitAvailableWidth())
    if (this.#scrollRef.value) resizeObserver.observe(this.#scrollRef.value)
    this.#cleanup.push(() => sizing.unsubscribe(), () => order.unsubscribe(), () => resizing.unsubscribe(), () => resizeObserver.disconnect(), startTableBenchmark(this.controller))
    this.#writeColumnSizes(); this.#fitAvailableWidth(); this.feed.completeRender()
  }
  protected updated() { this.#writeColumnSizes(); this.feed.completeRender() }
  disconnectedCallback() { for (const cleanup of this.#cleanup) cleanup(); this.#cleanup.length = 0; super.disconnectedCallback() }

  #writeColumnSizes() {
    const element = this.#tableRef.value; const table = this.#table
    if (!element || !table) return
    for (const header of table.getFlatHeaders()) { element.style.setProperty(`--header-${header.id}-size`, String(header.getSize())); element.style.setProperty(`--col-${header.column.id}-size`, String(header.column.getSize())) }
    element.style.width = `${table.getTotalSize()}px`
  }
  #fitAvailableWidth() {
    const container = this.#scrollRef.value; const table = this.#table
    if (!container || !table || this.#layout.manuallyResized) return
    const width = table.getTotalSize(); if (container.clientWidth <= width + 1 || width <= 0) return
    const ratio = container.clientWidth / width
    table.setColumnSizing(Object.fromEntries(table.getVisibleLeafColumns().map((column) => [column.id, column.getSize() * ratio])))
  }
  #clearDrag = () => { this.#drag.source?.classList.remove('is-column-dragging'); this.#drag.target?.classList.remove('is-column-drop-target'); this.#drag.columnId = null; this.#drag.source = null; this.#drag.target = null }
  #showDrop(columnId: string, element: HTMLTableCellElement | null) { this.#drag.target?.classList.remove('is-column-drop-target'); this.#drag.target = null; if (this.#drag.columnId === columnId || !element) return; element.classList.add('is-column-drop-target'); this.#drag.target = element }

  protected render() {
    this.#columns ??= createTradingColumns<typeof features>(this.controller)
    const table = this.#tableController.table({
      key: 'lit-realtime-trading', features, columns: this.#columns,
      data: this.feed.store.get().quotes, getRowId: (row) => row.id,
      columnResizeMode: 'onChange',
      defaultColumn: { minSize: 56, maxSize: 800 }, autoResetCellSelection: false,
    }, (state) => ({ sorting: state.sorting, columnFilters: state.columnFilters, columnOrder: state.columnOrder, rowSelection: state.rowSelection, cellSelection: state.cellSelection }))
    this.#table = table
    const rows = readMeasuredRows(() => table.getRowModel().rows)
    const benchmark = this.controller.store.get()
    const virtualMode = resolveVirtualScrollMode(benchmark.requestedVirtualScrollMode, this.feed.store.get().instrumentCount)
    const virtualizer = this.#virtualizer.getVirtualizer()
    virtualizer.setOptions({ ...virtualizer.options, count: rows.length, enabled: virtualMode === 'tanstack', getItemKey: (index) => rows[index]?.id ?? index })
    const virtualRows = virtualizer.getVirtualItems()
    this.controller.actions.setRenderedRowCount(virtualMode === 'tanstack' ? virtualRows.length : rows.length)
    const range = virtualizer.range
    const visibleRange = virtualMode === 'tanstack' && range && rows.length ? { start: Math.min(range.startIndex, rows.length - 1), end: Math.min(range.endIndex, rows.length - 1) } : null
    const renderRow = (row: (typeof rows)[number], virtualRow?: (typeof virtualRows)[number]) => html`<tr class=${virtualRow ? 'virtual-table-row' : ''} style=${virtualRow ? `transform:translateY(${virtualRow.start}px)` : ''} data-virtual-index=${virtualRow?.index ?? undefined} data-symbol=${row.original.symbol} data-row-id=${row.original.id} data-symbol-selected=${this.controller.renderAtoms.selectedSymbol.get() === row.original.symbol ? 'true' : undefined} title=${row.original.company} aria-selected=${row.getIsSelected()}>
      ${repeat(row.getVisibleCells(), (cell) => cell.id, (cell) => { const edges = cell.getSelectionEdges(); return html`<td style="width:calc(var(--col-${cell.column.id}-size) * 1px)" data-column-id=${cell.column.id} data-cell-focused=${cell.getIsFocused() ? 'true' : undefined} data-selection-top=${edges.top ? 'true' : undefined} data-selection-right=${edges.right ? 'true' : undefined} data-selection-bottom=${edges.bottom ? 'true' : undefined} data-selection-left=${edges.left ? 'true' : undefined} aria-selected=${cell.getIsSelected()} tabindex=${cell.getTabIndex()}>${FlexRender({ cell })}</td>` })}</tr>`
    return html`<div ${ref(this.#scrollRef)} class="table-scroll ${virtualMode === 'tanstack' ? 'is-virtualized' : ''}" data-trading-table>
      <table ${ref(this.#tableRef)} class="trading-data-grid ${virtualMode === 'tanstack' ? 'virtual-table' : ''}" data-testid="trading-table" role="grid" aria-multiselectable="true" tabindex="0" @keydown=${(event: KeyboardEvent) => handleCellNavigation(table, event)}>
        <thead>${repeat(table.getHeaderGroups(), (group) => group.id, (group) => html`<tr>${repeat(group.headers, (header) => header.id, (header) => { const leaf = header.subHeaders.length === 0; const sorted = header.column.getIsSorted(); return html`<th colspan=${header.colSpan} style="width:calc(var(--header-${header.id}-size) * 1px)" aria-sort=${leaf ? sortAriaValue(sorted) : undefined} class="${!leaf ? 'column-group-header' : ''} ${leaf && !['market','name','symbol'].includes(header.column.id) ? 'numeric-header' : ''}">${!header.isPlaceholder ? leaf ? html`<div class="leaf-header-content" @dragover=${(event: DragEvent) => { event.preventDefault(); this.#showDrop(header.column.id, (event.currentTarget as HTMLElement).closest('th')) }} @drop=${(event: DragEvent) => { event.preventDefault(); const source = event.dataTransfer?.getData('text/plain') || this.#drag.columnId; if (source) table.setColumnOrder(reorderColumnIds(table.getVisibleLeafColumns().map((column) => column.id), source, header.column.id)); this.#clearDrag() }}><button type="button" class="column-drag-handle" draggable="true" aria-label="Move ${header.column.id} column" @dragstart=${(event: DragEvent) => { this.#drag.columnId = header.column.id; this.#drag.source = (event.currentTarget as HTMLElement).closest('th'); this.#drag.source?.classList.add('is-column-dragging'); if (event.dataTransfer) { event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', header.column.id) } }} @dragend=${this.#clearDrag}>⋮⋮</button><button type="button" class="sort-header-button ${header.column.getCanSort() ? 'is-sortable' : ''}" ?disabled=${!header.column.getCanSort()} @click=${header.column.getToggleSortingHandler()}><span class="header-label">${FlexRender({ header })}</span>${header.column.getCanSort() ? html`<span class="sort-indicator ${sorted ? 'is-active' : ''}" aria-hidden="true">${sortIndicator(sorted)}</span>` : null}</button></div>${header.column.getCanResize() ? html`<div class="column-resize-handle ${header.column.getIsResizing() ? 'is-resizing' : ''}" role="separator" aria-orientation="vertical" @dblclick=${() => header.column.resetSize()} @mousedown=${header.getResizeHandler()} @touchstart=${header.getResizeHandler()}></div>` : null}` : FlexRender({ header }) : null}</th>` })}</tr>`)}</thead>
        <tbody class=${virtualMode === 'tanstack' ? 'virtual-table-body' : ''} style=${virtualMode === 'tanstack' ? `height:${virtualizer.getTotalSize()}px` : ''} data-source-row-count=${this.feed.store.get().quotes.length} @mousedown=${(event: MouseEvent) => this.#pointer.handleMouseDown(table, event, this.controller.actions.selectSymbol)} @pointerover=${(event: MouseEvent) => this.#pointer.handlePointerOver(table, event)} @mouseleave=${() => this.#pointer.resetPointerCell()} @click=${(event: MouseEvent) => this.#pointer.handleClick(table, event)}>${virtualMode === 'tanstack' ? repeat(virtualRows, (item) => item.key, (item) => renderRow(rows[item.index], item)) : repeat(rows, (row) => row.id, (row) => renderRow(row))}</tbody>
      </table></div>
      ${virtualMode === 'tanstack' ? html`<footer class="virtual-scroll-footer" data-testid="virtual-scroll-footer"><span>TanStack · Total · ${rows.length} rows · ${table.getVisibleLeafColumns().length} columns</span><span data-testid="visible-row-range">${visibleRange ? `Current · rows ${visibleRange.start}..${visibleRange.end}` : 'Current · rows —'}</span></footer>` : null}`
  }
}
