// packages/angular-table/src/signals.ts
import { computed, signal, untracked } from '@angular/core'
import { toObservable } from '@angular/core/rxjs-interop'
import { batch } from '@tanstack/angular-store'
import type { Atom, Observer, ReadonlyAtom } from '@tanstack/angular-store'
import type {
  TableAtomOptions,
  TableReactivityBindings,
} from '@tanstack/table-core'
import type { Injector, Signal, WritableSignal } from '@angular/core'

function signalToReadonlyAtom<T>(
  signal: Signal<T>,
  injector: Injector,
): ReadonlyAtom<T> {
  return Object.assign(signal, {
    get: () => signal(),
    subscribe: (observer: Observer<T>) => {
      return toObservable(computed(signal), { injector: injector }).subscribe(
        observer,
      )
    },
  })
}

function signalToWritableAtom<T>(
  signal: WritableSignal<T>,
  injector: Injector,
): Atom<T> {
  return Object.assign(signal.asReadonly(), {
    set: (updater: T | ((prevVal: T) => T)) => {
      typeof updater === 'function'
        ? signal.update(updater as (val: T) => T)
        : signal.set(updater)
    },
    get: () => signal(),
    subscribe: (observer: Observer<T>) => {
      return toObservable(computed(signal), { injector: injector }).subscribe(
        observer,
      )
    },
  })
}

export function angularReactivity(injector: Injector): TableReactivityBindings {
  return {
    createReadonlyAtom: <T>(fn: () => T, options?: TableAtomOptions<T>) => {
      const signal = computed(() => fn(), {
        equal: options?.compare,
        debugName: options?.debugName,
      })
      return signalToReadonlyAtom(signal, injector)
    },
    createWritableAtom: <T>(
      value: T,
      options?: TableAtomOptions<T>,
    ): Atom<T> => {
      const writableSignal = signal(value, {
        equal: options?.compare,
        debugName: options?.debugName,
      })
      return signalToWritableAtom(writableSignal, injector)
    },
    untrack: untracked,
    batch: (fn) => fn(),
  }
}

// packages/solid-table/src/signals.ts
import {
  batch,
  createMemo,
  createSignal,
  observable,
  runWithOwner,
  untrack,
} from 'solid-js'
import type { Accessor, Owner, Setter } from 'solid-js'
import type {
  TableAtomOptions,
  TableReactivityBindings,
} from '@tanstack/table-core'
import type { Atom, Observer, ReadonlyAtom } from '@tanstack/solid-store'

function signalToReadonlyAtom<T>(
  signal: Accessor<T>,
  owner: Owner,
): ReadonlyAtom<T> {
  return Object.assign(signal, {
    get: () => signal(),
    subscribe: (observer: Observer<T>) => {
      return runWithOwner(owner, () => observable(signal))!.subscribe(observer)
    },
  })
}

function signalToWritableAtom<T>(
  signalTuple: [Accessor<T>, Setter<T>],
  owner: Owner,
): Atom<T> {
  const [signal, setSignal] = signalTuple
  return Object.assign(signal, {
    set: (updater: T | ((prevVal: T) => T)) => {
      typeof updater === 'function'
        ? setSignal(updater as unknown as (prev: T) => T)
        : setSignal(updater as Exclude<T, Function>)
    },
    get: () => signal(),
    subscribe: (observer: Observer<T>) => {
      return runWithOwner(owner, () => observable(signal))!.subscribe(observer)
    },
  })
}

export function solidReactivity(owner: Owner): TableReactivityBindings {
  return {
    createReadonlyAtom: <T>(fn: () => T, options?: TableAtomOptions<T>) => {
      const signal = createMemo(() => fn(), {
        equals: options?.compare,
        name: options?.debugName,
      })
      return signalToReadonlyAtom(signal, owner)
    },
    createWritableAtom: <T>(
      value: T,
      options?: TableAtomOptions<T>,
    ): Atom<T> => {
      const writableSignal = createSignal(value, {
        equals: options?.compare,
        name: options?.debugName,
      })
      return signalToWritableAtom(writableSignal, owner)
    },
    untrack: untrack,
    batch: batch,
  }
}
