// examples/solid/realtime-trading/src/shell/trading-shell-context.tsx
import { createContext, useContext } from 'solid-js'
import type { JSX } from 'solid-js'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { TradingBenchmarkController } from '../benchmark/trading-benchmark-controller'

const TradingShellContext = createContext<TradingBenchmarkController>()
const MarketFeedContext = createContext<MarketFeedController>()

export function MarketFeedProvider(props: {
  controller: MarketFeedController
  children: JSX.Element
}) {
  return (
    <MarketFeedContext.Provider value={props.controller}>
      {props.children}
    </MarketFeedContext.Provider>
  )
}

export function TradingShellProvider(props: {
  controller: TradingBenchmarkController
  children: JSX.Element
}) {
  return (
    <MarketFeedProvider controller={props.controller.feed}>
      <TradingShellContext.Provider value={props.controller}>
        {props.children}
      </TradingShellContext.Provider>
    </MarketFeedProvider>
  )
}

export function useMarketFeedController(): MarketFeedController {
  const controller = useContext(MarketFeedContext)
  if (!controller) {
    throw new Error('Market data consumers must be rendered inside MarketFeedProvider')
  }
  return controller
}

export function useTradingShellController(): TradingBenchmarkController {
  const controller = useContext(TradingShellContext)
  if (!controller) {
    throw new Error(
      'Trading shell components must be rendered inside TradingShellProvider',
    )
  }
  return controller
}

// examples/react/realtime-trading/src/shell/trading-shell-context.tsx
import { createStoreContext, useSelector } from '@tanstack/react-store'
import type { ReactNode } from 'react'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { TradingBenchmarkController } from '../benchmark/use-trading-benchmark-controller'
import type { TradingBenchmarkState } from '../benchmark/trading-benchmark-controller'
import type { UseSelectorOptions } from '@tanstack/react-store'

const {
  StoreProvider: TradingStoreProvider,
  useStoreContext: useTradingShellController,
} = createStoreContext<TradingBenchmarkController>()

const {
  StoreProvider: MarketFeedStoreProvider,
  useStoreContext: useMarketFeedController,
} = createStoreContext<MarketFeedController>()

export function MarketFeedProvider(props: {
  controller: MarketFeedController
  children: ReactNode
}) {
  return (
    <MarketFeedStoreProvider value={props.controller}>
      {props.children}
    </MarketFeedStoreProvider>
  )
}

export function TradingShellProvider(props: {
  controller: TradingBenchmarkController
  children: ReactNode
}) {
  return (
    <MarketFeedProvider controller={props.controller.feed}>
      <TradingStoreProvider value={props.controller}>
        {props.children}
      </TradingStoreProvider>
    </MarketFeedProvider>
  )
}

export { useMarketFeedController, useTradingShellController }

export function useTradingShellState<TSelected>(
  selector: (state: TradingBenchmarkState) => TSelected,
  options?: UseSelectorOptions<TSelected>,
): TSelected {
  const controller = useTradingShellController()
  return useSelector(controller.store, selector, options)
}
