// examples/svelte/kitchen-sink-shadcn/src/components/data-table/DataTableSortList.svelte
<!-- Sort builder popover: add/remove/reorder multi-sort entries. Rows are
  drag-sortable via @dnd-kit-svelte. -->
<script lang="ts">
  import ArrowDownUp from '@lucide/svelte/icons/arrow-down-up'
  import Check from '@lucide/svelte/icons/check'
  import ChevronsUpDown from '@lucide/svelte/icons/chevrons-up-down'
  import GripVertical from '@lucide/svelte/icons/grip-vertical'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import { DragDropProvider } from '@dnd-kit-svelte/svelte'
  import { useSortable } from '@dnd-kit-svelte/svelte/sortable'
  import { RestrictToVerticalAxis } from '@dnd-kit/abstract/modifiers'
  import { move } from '@dnd-kit/helpers'
  import type { ColumnSort } from '@tanstack/svelte-table'
  import { useTableContext } from '@/hooks/table.svelte'
  import { Badge } from '@/lib/components/ui/badge'
  import { Button } from '@/lib/components/ui/button'
  import * as Command from '@/lib/components/ui/command'
  import * as Popover from '@/lib/components/ui/popover'
  import * as Select from '@/lib/components/ui/select'
  import { cn } from '@/lib/utils'

  const table = useTableContext()
  const sorting = $derived(table.atoms.sorting.get())

  const uid = $props.id()
  const labelId = `${uid}-label`
  const descriptionId = `${uid}-description`
  const listId = `${uid}-list`
  let open = $state(false)

  const sortableColumns = $derived(
    table.getAllColumns().filter((column) => column.getCanSort()),
  )

  function onColumnSelect(currentSortId: string, newColumnId: string) {
    table.setSorting(
      sorting.map((s) =>
        s.id === currentSortId ? { ...s, id: newColumnId } : s,
      ),
    )
  }

  function onSortAdd() {
    const firstAvailableColumn = sortableColumns.find(
      (col) => !sorting.some((s) => s.id === col.id),
    )
    if (firstAvailableColumn) {
      table.setSorting([
        ...sorting,
        { id: firstAvailableColumn.id, desc: false },
      ])
    }
  }

  function onSortUpdate(sortId: string, updates: Partial<Omit<ColumnSort, 'id'>>) {
    table.setSorting(
      sorting.map((s) => (s.id === sortId ? { ...s, ...updates } : s)),
    )
  }

  function onSortRemove(sortId: string) {
    table.setSorting(sorting.filter((s) => s.id !== sortId))
  }
</script>

<DragDropProvider
  modifiers={[RestrictToVerticalAxis]}
  onDragEnd={(e) => table.setSorting(move([...sorting], e))}
>
  <Popover.Root bind:open>
    <Popover.Trigger>
      {#snippet child({ props })}
        <Button {...props} variant="outline" size="sm" class="[&_svg]:size-3">
          <ArrowDownUp />
          Sort
          {#if sorting.length > 0}
            <Badge
              variant="secondary"
              class="h-[1.14rem] rounded-[0.2rem] px-[0.32rem] font-mono font-normal text-[0.65rem]"
            >
              {sorting.length}
            </Badge>
          {/if}
        </Button>
      {/snippet}
    </Popover.Trigger>
    <Popover.Content
      aria-labelledby={labelId}
      aria-describedby={descriptionId}
      align="start"
      collisionPadding={16}
      class="w-[calc(100vw-theme(spacing.20))] origin-(--transform-origin) flex flex-col gap-3 min-w-72 max-w-[25rem] p-4 sm:w-[25rem]"
    >
      <div class="flex flex-col gap-1">
        <h4 id={labelId} class="font-medium leading-none">
          {sorting.length > 0 ? 'Sort by' : 'No sorting applied'}
        </h4>
        <p
          id={descriptionId}
          class={cn(
            'text-muted-foreground text-sm',
            sorting.length > 0 && 'sr-only',
          )}
        >
          {sorting.length > 0
            ? 'Modify sorting to organize your results.'
            : 'Add sorting to organize your results.'}
        </p>
      </div>
      {#if sorting.length > 0}
        <div
          role="list"
          id={listId}
          aria-labelledby={labelId}
          aria-describedby={descriptionId}
          class="flex max-h-[300px] flex-col gap-2 overflow-y-auto p-0.5"
        >
          {#each sorting as sort, index (sort.id)}
            {@render SortRow({ sort, index })}
          {/each}
        </div>
      {/if}
      <div class="flex items-center gap-2">
        <Button
          aria-label="Add new sort"
          size="sm"
          onclick={onSortAdd}
          disabled={sorting.length >= sortableColumns.length}
        >
          Add sort
        </Button>
        {#if sorting.length > 0}
          <Button
            aria-label="Reset all sorting"
            size="sm"
            variant="outline"
            onclick={() => table.resetSorting()}
          >
            Reset
          </Button>
        {/if}
      </div>
    </Popover.Content>
  </Popover.Root>
</DragDropProvider>

{#snippet SortRow({ sort, index }: { sort: ColumnSort; index: number })}
  {@const columnTitle =
    sortableColumns.find((col) => col.id === sort.id)?.columnDef.meta?.label ??
    sort.id}
  {@const sortItemId = `${listId}-item-${sort.id}`}
  {@const fieldListboxId = `${sortItemId}-field-listbox`}
  {@const operatorListboxId = `${sortItemId}-operator-listbox`}
  {@const sortable = useSortable({ id: sort.id, index: () => index })}

  <div
    role="listitem"
    id={sortItemId}
    tabindex="-1"
    data-dragging={sortable.isDragging.current}
    class="relative z-0 grid items-center grid-cols-[175px_100px_32px_32px] gap-2 data-[dragging=true]:z-10 data-[dragging=true]:opacity-80"
    {@attach sortable.ref}
  >
    <Popover.Root>
      <Popover.Trigger>
        {#snippet child({ props })}
          <Button
            {...props}
            role="combobox"
            aria-controls={fieldListboxId}
            aria-label={`Select column to sort by. Current: ${columnTitle}`}
            variant="outline"
            size="sm"
            class="h-8 font-normal justify-between gap-2 focus:outline-none focus:ring-1 focus:ring-ring"
          >
            <span class="truncate">{columnTitle}</span>
            <ChevronsUpDown class="opacity-50" />
          </Button>
        {/snippet}
      </Popover.Trigger>
      <Popover.Content id={fieldListboxId} class="w-[175px] p-0">
        <Command.Root>
          <Command.Input
            placeholder="Search columns..."
            aria-label="Search sortable columns"
          />
          <Command.List>
            <Command.Empty>No column found.</Command.Empty>
            <Command.Group>
              {#each sortableColumns.filter((column) => !sorting.some((s) => s.id === column.id && s.id !== sort.id)) as column (column.id)}
                <Command.Item
                  value={column.id}
                  onSelect={() => onColumnSelect(sort.id, column.id)}
                >
                  <span class="truncate">
                    {column.columnDef.meta?.label ?? column.id}
                  </span>
                  <Check
                    class={cn(
                      'ml-auto size-4',
                      column.id === sort.id ? 'opacity-100' : 'opacity-0',
                    )}
                    aria-hidden="true"
                  />
                </Command.Item>
              {/each}
            </Command.Group>
          </Command.List>
        </Command.Root>
      </Popover.Content>
    </Popover.Root>
    <Select.Root
      type="single"
      value={sort.desc ? 'desc' : 'asc'}
      onValueChange={(value) => onSortUpdate(sort.id, { desc: value === 'desc' })}
    >
      <Select.Trigger
        aria-controls={operatorListboxId}
        aria-label={`Sort direction for ${columnTitle}`}
        class="h-8"
      >
        {sort.desc ? 'Desc' : 'Asc'}
      </Select.Trigger>
      <Select.Content id={operatorListboxId}>
        <Select.Item value="asc" label="Asc" />
        <Select.Item value="desc" label="Desc" />
      </Select.Content>
    </Select.Root>
    <Button
      aria-label={`Remove sort for ${columnTitle}`}
      variant="outline"
      size="icon"
      class="size-8 [&_svg]:size-3.5 shrink-0"
      onclick={() => onSortRemove(sort.id)}
    >
      <Trash2 />
    </Button>
    <Button
      {@attach sortable.handleRef}
      aria-label={`Drag to reorder ${columnTitle} sort`}
      variant="outline"
      size="icon"
      class="size-8 [&_svg]:size-3.5 shrink-0"
    >
      <GripVertical />
    </Button>
  </div>
{/snippet}

// examples/react/shadcn-kitchen-sink/src/components/data-table/data-table-sort-list.tsx
'use client'

import * as React from 'react'
import {
  ArrowDownUp,
  Check,
  ChevronsUpDown,
  GripVertical,
  Trash2,
} from 'lucide-react'
import type {
  ColumnSort,
  RowData,
  SortDirection,
  SortingState,
  Table,
  TableFeatures,
} from '@tanstack/react-table'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Sortable,
  SortableContent,
  SortableItem,
  SortableItemHandle,
  SortableOverlay,
} from '@/components/ui/sortable'
import { cn } from '@/lib/utils'

interface DataTableSortListProps<
  TFeatures extends TableFeatures,
  TData extends RowData,
> {
  table: Table<Pick<TFeatures, 'rowSortingFeature'>, TData>
  sorting: SortingState
  onSortingChange: (sorting: SortingState) => void
}

export function DataTableSortList<
  TFeatures extends TableFeatures,
  TData extends RowData,
>({
  table,
  sorting,
  onSortingChange,
}: DataTableSortListProps<TFeatures, TData>) {
  const labelId = React.useId()
  const descriptionId = React.useId()
  const listId = React.useId()
  const [open, setOpen] = React.useState(false)

  const sortableColumns = React.useMemo(
    () => table.getAllColumns().filter((column) => column.getCanSort()),
    [table],
  )

  const onColumnSelect = React.useCallback(
    (currentSortId: string, newColumnId: string) => {
      const newSorting = sorting.map((s) =>
        s.id === currentSortId ? { ...s, id: newColumnId } : s,
      )
      table.setSorting(newSorting)
    },
    [sorting, table],
  )

  const onSortAdd = React.useCallback(() => {
    const firstAvailableColumn = sortableColumns.find(
      (col) => !sorting.some((s) => s.id === col.id),
    )
    if (firstAvailableColumn) {
      table.setSorting([
        ...sorting,
        { id: firstAvailableColumn.id, desc: false },
      ])
    }
  }, [sorting, sortableColumns, table])

  const onSortUpdate = React.useCallback(
    (sortId: string, updates: Partial<Omit<ColumnSort, 'id'>>) => {
      const newSorting = sorting.map((s) =>
        s.id === sortId ? { ...s, ...updates } : s,
      )
      table.setSorting(newSorting)
    },
    [sorting, table],
  )

  const onSortRemove = React.useCallback(
    (sortId: string) => {
      const newSorting = sorting.filter((s) => s.id !== sortId)
      table.setSorting(newSorting)
    },
    [sorting, table],
  )

  return (
    <Sortable
      value={sorting}
      onValueChange={onSortingChange}
      getItemValue={(item) => item.id}
    >
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            className="[&_svg]:size-3"
            onClick={(event) => event.currentTarget.focus()}
            onPointerDown={(event) => {
              const target = event.target
              if (!(target instanceof HTMLElement)) return
              if (target.hasPointerCapture(event.pointerId)) {
                target.releasePointerCapture(event.pointerId)
              }

              if (
                event.button === 0 &&
                event.ctrlKey === false &&
                event.pointerType === 'mouse'
              ) {
                event.preventDefault()
              }
            }}
          >
            <ArrowDownUp />
            Sort
            {sorting.length > 0 && (
              <Badge
                variant="secondary"
                className="h-[1.14rem] rounded-[0.2rem] px-[0.32rem] font-mono font-normal text-[0.65rem]"
              >
                {sorting.length}
              </Badge>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent
          aria-labelledby={labelId}
          aria-describedby={descriptionId}
          align="start"
          collisionPadding={16}
          className="w-[calc(100vw-theme(spacing.20))] origin-[var(--radix-popover-content-transform-origin)] flex flex-col gap-3 min-w-72 max-w-[25rem] p-4 sm:w-[25rem]"
        >
          <div className="flex flex-col gap-1">
            <h4 id={labelId} className="font-medium leading-none">
              {sorting.length > 0 ? 'Sort by' : 'No sorting applied'}
            </h4>
            <p
              id={descriptionId}
              className={cn(
                'text-muted-foreground text-sm',
                sorting.length > 0 && 'sr-only',
              )}
            >
              {sorting.length > 0
                ? 'Modify sorting to organize your results.'
                : 'Add sorting to organize your results.'}
            </p>
          </div>
          {sorting.length > 0 ? (
            <SortableContent asChild>
              <div
                role="list"
                id={listId}
                aria-labelledby={labelId}
                aria-describedby={descriptionId}
                className="flex max-h-[300px] flex-col gap-2 overflow-y-auto p-0.5"
              >
                {sorting.map((sort, index) => {
                  const columnTitle =
                    sortableColumns.find((col) => col.id === sort.id)?.columnDef
                      .meta?.label ?? sort.id
                  const sortItemId = `${listId}-item-${sort.id}`
                  const triggerId = `${listId}-${index}-trigger`
                  const fieldListboxId = `${sortItemId}-field-listbox`
                  const operatorListboxId = `${sortItemId}-operator-listbox`

                  return (
                    <SortableItem key={sort.id} value={sort.id} asChild>
                      <div
                        role="listitem"
                        id={sortItemId}
                        tabIndex={-1}
                        className="flex items-center gap-2"
                      >
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              role="combobox"
                              id={triggerId}
                              aria-controls={fieldListboxId}
                              aria-label={`Select column to sort by. Current: ${columnTitle}`}
                              variant="outline"
                              size="sm"
                              className="h-8 w-44 justify-between gap-2 rounded focus:outline-none focus:ring-1 focus:ring-ring"
                              onPointerDown={(event) => {
                                const target = event.target
                                if (!(target instanceof HTMLElement)) return
                                if (target.hasPointerCapture(event.pointerId)) {
                                  target.releasePointerCapture(event.pointerId)
                                }

                                if (
                                  event.button === 0 &&
                                  event.ctrlKey === false &&
                                  event.pointerType === 'mouse'
                                ) {
                                  event.preventDefault()
                                }
                              }}
                            >
                              <span className="truncate">{columnTitle}</span>
                              <ChevronsUpDown className="opacity-50" />
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent
                            id={fieldListboxId}
                            className="w-[var(--radix-popover-trigger-width)] p-0"
                            onCloseAutoFocus={() =>
                              document
                                .getElementById(triggerId)
                                ?.focus({ preventScroll: true })
                            }
                          >
                            <Command>
                              <CommandInput
                                placeholder="Search columns..."
                                aria-label="Search sortable columns"
                              />
                              <CommandList>
                                <CommandEmpty>No column found.</CommandEmpty>
                                <CommandGroup>
                                  {sortableColumns
                                    .filter(
                                      (column) =>
                                        !sorting.some(
                                          (s) =>
                                            s.id === column.id &&
                                            s.id !== sort.id,
                                        ),
                                    )
                                    .map((column) => (
                                      <CommandItem
                                        key={column.id}
                                        value={column.id}
                                        onSelect={() =>
                                          onColumnSelect(sort.id, column.id)
                                        }
                                      >
                                        <span className="mr-2 truncate">
                                          {column.columnDef.meta?.label ??
                                            column.id}
                                        </span>
                                        <Check
                                          className={cn(
                                            'ml-auto size-4',
                                            column.id === sort.id
                                              ? 'opacity-100'
                                              : 'opacity-0',
                                          )}
                                          aria-hidden="true"
                                        />
                                      </CommandItem>
                                    ))}
                                </CommandGroup>
                              </CommandList>
                            </Command>
                          </PopoverContent>
                        </Popover>
                        <Select
                          value={sort.desc ? 'desc' : 'asc'}
                          onValueChange={(value: SortDirection) =>
                            onSortUpdate(sort.id, { desc: value === 'desc' })
                          }
                        >
                          <SelectTrigger
                            aria-controls={operatorListboxId}
                            aria-label={`Sort direction for ${columnTitle}`}
                            className="h-8 w-24"
                          >
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent
                            id={operatorListboxId}
                            className="min-w-[var(--radix-select-trigger-width)]"
                          >
                            <SelectItem value="asc">Asc</SelectItem>
                            <SelectItem value="desc">Desc</SelectItem>
                          </SelectContent>
                        </Select>
                        <Button
                          aria-label={`Remove sort for ${columnTitle}`}
                          variant="outline"
                          size="icon"
                          className="size-8 [&_svg]:size-3.5 shrink-0"
                          onClick={() => onSortRemove(sort.id)}
                        >
                          <Trash2 />
                        </Button>
                        <SortableItemHandle asChild>
                          <Button
                            aria-label={`Drag to reorder ${columnTitle} sort`}
                            variant="outline"
                            size="icon"
                            className="size-8 [&_svg]:size-3.5 shrink-0"
                          >
                            <GripVertical />
                          </Button>
                        </SortableItemHandle>
                      </div>
                    </SortableItem>
                  )
                })}
              </div>
            </SortableContent>
          ) : null}
          <div className="flex items-center gap-2">
            <Button
              aria-label="Add new sort"
              size="sm"
              onClick={onSortAdd}
              disabled={sorting.length >= sortableColumns.length}
            >
              Add sort
            </Button>
            {sorting.length > 0 && (
              <Button
                aria-label="Reset all sorting"
                size="sm"
                variant="outline"
                onClick={() => table.resetSorting()}
              >
                Reset
              </Button>
            )}
          </div>
        </PopoverContent>
      </Popover>
      <SortableOverlay>
        <div className="flex items-center gap-2">
          <div className="h-8 w-[11.25rem] rounded-md bg-primary/10" />
          <div className="h-8 w-24 rounded-md bg-primary/10" />
          <div className="size-8 shrink-0 rounded-md bg-primary/10" />
          <div className="size-8 shrink-0 rounded-md bg-primary/10" />
        </div>
      </SortableOverlay>
    </Sortable>
  )
}
