// examples/solid/with-tanstack-form/src/table.tsx
import {
  columnFilteringFeature,
  createFilteredRowModel,
  createPaginatedRowModel,
  createSortedRowModel,
  createTableHook,
  filterFn_inNumberRange,
  filterFn_includesString,
  rowPaginationFeature,
  rowSortingFeature,
  sortFn_alphanumeric,
  sortFn_text,
  tableFeatures,
} from '@tanstack/solid-table'
import { For, Show, createMemo, createSignal } from 'solid-js'
import type { JSX } from 'solid-js'

function SortIndicator() {
  const header = useHeaderContext()
  const sorted = () => header.column.getIsSorted()

  return (
    <Show when={sorted()}>
      {(sorted) => <>{sorted() === 'asc' ? ' 🔼' : ' 🔽'}</>}
    </Show>
  )
}

function ColumnFilter() {
  const header = useHeaderContext()
  const table = useTableContext()

  const firstValue = () =>
    table.getPreFilteredRowModel().flatRows[0]?.getValue(header.column.id)

  const columnFilterValue = () => header.column.getFilterValue()

  return (
    <Show when={header.column.getCanFilter()}>
      <div onClick={(e) => e.stopPropagation()}>
        <Show
          when={typeof firstValue() === 'number'}
          fallback={
            <DebouncedInput
              type="text"
              value={(columnFilterValue() ?? '') as string}
              onChange={(value) => header.column.setFilterValue(value)}
              placeholder="Search..."
              class="filter-select"
            />
          }
        >
          <div class="filter-row">
            <DebouncedInput
              type="number"
              value={
                (columnFilterValue() as [number, number] | undefined)?.[0] ?? ''
              }
              onChange={(value) =>
                header.column.setFilterValue(
                  (old: [number, number] | undefined) => [value, old?.[1]],
                )
              }
              placeholder="Min"
              class="filter-input"
            />
            <DebouncedInput
              type="number"
              value={
                (columnFilterValue() as [number, number] | undefined)?.[1] ?? ''
              }
              onChange={(value) =>
                header.column.setFilterValue(
                  (old: [number, number] | undefined) => [old?.[0], value],
                )
              }
              placeholder="Max"
              class="filter-input"
            />
          </div>
        </Show>
      </div>
    </Show>
  )
}

function PaginationControls() {
  const table = useTableContext()
  const pagination = createMemo(() => table.atoms.pagination.get())

  return (
    <>
      <div class="spacer-sm" />
      <div class="controls">
        <button
          type="button"
          class="demo-button demo-button-sm"
          onClick={() => table.firstPage()}
          disabled={!table.getCanPreviousPage()}
        >
          {'<<'}
        </button>
        <button
          type="button"
          class="demo-button demo-button-sm"
          onClick={() => table.previousPage()}
          disabled={!table.getCanPreviousPage()}
        >
          {'<'}
        </button>
        <button
          type="button"
          class="demo-button demo-button-sm"
          onClick={() => table.nextPage()}
          disabled={!table.getCanNextPage()}
        >
          {'>'}
        </button>
        <button
          type="button"
          class="demo-button demo-button-sm"
          onClick={() => table.lastPage()}
          disabled={!table.getCanLastPage()}
        >
          {'>>'}
        </button>
        <span class="inline-controls">
          <div>Page</div>
          <strong>
            {(pagination().pageIndex + 1).toLocaleString()} of{' '}
            {table.getPageCount().toLocaleString()}
          </strong>
        </span>
        <span class="inline-controls">
          | Go to page:
          <input
            type="number"
            min="1"
            max={table.getPageCount()}
            value={pagination().pageIndex + 1}
            onChange={(e) => {
              const page = e.currentTarget.value
                ? Number(e.currentTarget.value) - 1
                : 0
              table.setPageIndex(page)
            }}
            class="page-size-input"
          />
        </span>
        <select
          value={pagination().pageSize}
          onChange={(e) => {
            table.setPageSize(Number(e.currentTarget.value))
          }}
        >
          <For each={[10, 20, 30, 40, 50]}>
            {(pageSize) => <option value={pageSize}>Show {pageSize}</option>}
          </For>
        </select>
      </div>
    </>
  )
}

function RowCount() {
  const table = useTableContext()

  return (
    <div>
      Showing {table.getRowModel().rows.length.toLocaleString()} of{' '}
      {table.getRowCount().toLocaleString()} Rows
    </div>
  )
}

function DebouncedInput({
  value: initialValue,
  onChange,
  debounce = 500,
  ...props
}: {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'onChange'>) {
  const [value, setValue] = createSignal(initialValue)
  let timeout: ReturnType<typeof setTimeout> | undefined

  return (
    <input
      {...props}
      value={value()}
      onInput={(e) => {
        const nextValue = e.currentTarget.value
        setValue(nextValue)
        if (timeout) clearTimeout(timeout)
        timeout = setTimeout(() => onChange(nextValue), debounce)
      }}
    />
  )
}

export const {
  appFeatures,
  createAppColumnHelper,
  createAppTable,
  useHeaderContext,
  useTableContext,
} = createTableHook({
  features: tableFeatures({
    rowPaginationFeature,
    columnFilteringFeature,
    rowSortingFeature,
    filteredRowModel: createFilteredRowModel(),
    paginatedRowModel: createPaginatedRowModel(),
    sortedRowModel: createSortedRowModel(),
    filterFns: {
      includesString: filterFn_includesString,
      inNumberRange: filterFn_inNumberRange,
    },
    sortFns: {
      alphanumeric: sortFn_alphanumeric,
      text: sortFn_text,
    },
  }),
  tableComponents: {
    PaginationControls,
    RowCount,
  },
  headerComponents: {
    SortIndicator,
    ColumnFilter,
  },
  cellComponents: {},
})

// examples/preact/with-tanstack-form/src/table.tsx
import { useEffect, useState } from 'preact/hooks'
import {
  columnFilteringFeature,
  createFilteredRowModel,
  createPaginatedRowModel,
  createSortedRowModel,
  createTableHook,
  filterFn_inNumberRange,
  filterFn_includesString,
  rowPaginationFeature,
  rowSortingFeature,
  sortFn_alphanumeric,
  sortFn_text,
  tableFeatures,
} from '@tanstack/preact-table'
import { useDebouncedCallback } from '@tanstack/preact-pacer/debouncer'
import type { JSX } from 'preact'
import type { Column, PreactTable } from '@tanstack/preact-table'

function SortIndicator() {
  const header = useHeaderContext()
  const sorted = header.column.getIsSorted()

  if (!sorted) return null

  return <>{sorted === 'asc' ? ' 🔼' : ' 🔽'}</>
}

function ColumnFilter() {
  const header = useHeaderContext()
  const table = useTableContext<any>()

  if (!header.column.getCanFilter()) return null

  return (
    <div onClick={(e) => e.stopPropagation()}>
      <Filter column={header.column} table={table} />
    </div>
  )
}

function PaginationControls() {
  const table = useTableContext()

  return (
    <>
      <div className="spacer-sm" />
      <div className="controls">
        <button
          type="button"
          className="demo-button demo-button-sm"
          onClick={() => table.firstPage()}
          disabled={!table.getCanPreviousPage()}
        >
          {'<<'}
        </button>
        <button
          type="button"
          className="demo-button demo-button-sm"
          onClick={() => table.previousPage()}
          disabled={!table.getCanPreviousPage()}
        >
          {'<'}
        </button>
        <button
          type="button"
          className="demo-button demo-button-sm"
          onClick={() => table.nextPage()}
          disabled={!table.getCanNextPage()}
        >
          {'>'}
        </button>
        <button
          type="button"
          className="demo-button demo-button-sm"
          onClick={() => table.lastPage()}
          disabled={!table.getCanLastPage()}
        >
          {'>>'}
        </button>
        <span className="inline-controls">
          <div>Page</div>
          <strong>
            {(table.state.pagination.pageIndex + 1).toLocaleString()} of{' '}
            {table.getPageCount().toLocaleString()}
          </strong>
        </span>
        <span className="inline-controls">
          | Go to page:
          <input
            type="number"
            min="1"
            max={table.getPageCount()}
            value={table.state.pagination.pageIndex + 1}
            onInput={(e) => {
              const page = e.currentTarget.value
                ? Number(e.currentTarget.value) - 1
                : 0
              table.setPageIndex(page)
            }}
            className="page-size-input"
          />
        </span>
        <select
          value={table.state.pagination.pageSize}
          onChange={(e) => {
            table.setPageSize(Number(e.currentTarget.value))
          }}
        >
          {[10, 20, 30, 40, 50].map((pageSize) => (
            <option key={pageSize} value={pageSize}>
              Show {pageSize}
            </option>
          ))}
        </select>
      </div>
    </>
  )
}

function RowCount() {
  const table = useTableContext()

  return (
    <div>
      Showing {table.getRowModel().rows.length.toLocaleString()} of{' '}
      {table.getRowCount().toLocaleString()} Rows
    </div>
  )
}

function Filter({
  column,
  table,
}: {
  column: Column<typeof appFeatures, any>
  table: PreactTable<typeof appFeatures, any>
}) {
  const firstValue = table
    .getPreFilteredRowModel()
    .flatRows[0]?.getValue(column.id)

  const columnFilterValue = column.getFilterValue()

  return typeof firstValue === 'number' ? (
    <div className="filter-row">
      <DebouncedInput
        type="number"
        value={(columnFilterValue as [number, number] | undefined)?.[0] ?? ''}
        onChange={(value) =>
          column.setFilterValue((old: [number, number] | undefined) => [
            value,
            old?.[1],
          ])
        }
        placeholder={`Min`}
        className="filter-input"
      />
      <DebouncedInput
        type="number"
        value={(columnFilterValue as [number, number] | undefined)?.[1] ?? ''}
        onChange={(value) =>
          column.setFilterValue((old: [number, number] | undefined) => [
            old?.[0],
            value,
          ])
        }
        placeholder={`Max`}
        className="filter-input"
      />
    </div>
  ) : (
    <DebouncedInput
      type="text"
      value={(columnFilterValue ?? '') as string}
      onChange={(value) => column.setFilterValue(value)}
      placeholder={`Search...`}
      className="filter-select"
    />
  )
}

function DebouncedInput({
  value: initialValue,
  onChange,
  debounce = 500,
  ...props
}: {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
} & Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'onChange'>) {
  const [value, setValue] = useState(initialValue)

  useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  const debouncedOnChange = useDebouncedCallback(onChange, { wait: debounce })

  return (
    <input
      {...props}
      value={value}
      onChange={(e) => {
        setValue(e.currentTarget.value)
        debouncedOnChange(e.currentTarget.value)
      }}
    />
  )
}

export const {
  appFeatures,
  createAppColumnHelper,
  useAppTable,
  useHeaderContext,
  useTableContext,
} = createTableHook({
  features: tableFeatures({
    rowPaginationFeature,
    columnFilteringFeature,
    rowSortingFeature,
    filteredRowModel: createFilteredRowModel(),
    paginatedRowModel: createPaginatedRowModel(),
    sortedRowModel: createSortedRowModel(),
    filterFns: {
      includesString: filterFn_includesString,
      inNumberRange: filterFn_inNumberRange,
    },
    sortFns: {
      alphanumeric: sortFn_alphanumeric,
      text: sortFn_text,
    },
  }),
  tableComponents: {
    PaginationControls,
    RowCount,
  },
  headerComponents: {
    SortIndicator,
    ColumnFilter,
  },
  cellComponents: {},
})
