// examples/solid/realtime-trading/src/benchmark/trading-benchmark-controller.ts
import {
  createMemo,
  createSignal,
  onCleanup,
  onMount,
} from 'solid-js'
import { TRADING_COLUMN_COUNT } from '../table/trading-table'
import {
  FORCED_VIRTUALIZATION_ROW_COUNT,
  resolveVirtualScrollMode,
} from '../table/trading-row-virtualizer'
import {
  BenchmarkMonitor,
  initialMetrics,
  longAnimationFramesSupported,
} from './benchmark-monitor'
import type { MarketFeedController } from '../feed/market-feed-controller'
import type { RendererMode } from '../table/trading-table'
import type { VirtualScrollPreference } from '../table/trading-row-virtualizer'

export function createTradingBenchmarkController(feed: MarketFeedController) {
  const [rendererMode, setRendererMode] = createSignal<RendererMode>('stable')
  const [requestedVirtualScrollMode, setRequestedVirtualScrollMode] =
    createSignal<VirtualScrollPreference>('auto')
  const [renderedRowCount, setRenderedRowCount] = createSignal(0)
  const [selectedSymbol, setSelectedSymbol] = createSignal<string | null>(null)
  const [metrics, setMetrics] = createSignal(initialMetrics)
  const monitor = new BenchmarkMonitor()
  const runtime = {
    animationFrameId: 0,
    longAnimationFrameObserver: null as PerformanceObserver | null,
    mutationObserver: null as MutationObserver | null,
  }

  const stopObservingFeed = feed.observe({
    messageReceived: () => monitor.recordWorkerMessage(),
    mutationStarted: () => monitor.markRenderPending(),
    batchApplied: ({ tickCount, updateCount, supersededUpdateCount }) =>
      monitor.recordBatch(tickCount, updateCount, supersededUpdateCount),
    renderCommitted: () => monitor.recordCompletedRender(),
  })

  const observeTableMutations = (): void => {
    const tableBody = document.querySelector(
      '.market-panel [data-trading-table] tbody',
    )
    if (!tableBody) return

    monitor.resetDomMutations()
    runtime.mutationObserver = new MutationObserver((records) => {
      monitor.recordDomMutations(records.length)
    })
    runtime.mutationObserver.observe(tableBody, {
      attributes: true,
      characterData: true,
      childList: true,
      subtree: true,
    })
  }

  const benchmarkFrame = (now: number): void => {
    monitor.recordAnimationFrame()
    if (monitor.shouldPublish(now)) {
      setMetrics(monitor.publish(now))
    }
    runtime.animationFrameId = requestAnimationFrame(benchmarkFrame)
  }

  onMount(() => {
    observeTableMutations()
    if (longAnimationFramesSupported) {
      runtime.longAnimationFrameObserver = new PerformanceObserver(
        (entries) => {
          for (const entry of entries.getEntries()) {
            monitor.recordLongAnimationFrame(entry.duration)
          }
        },
      )
      runtime.longAnimationFrameObserver.observe({
        type: 'long-animation-frame',
        buffered: true,
      })
    }
    runtime.animationFrameId = requestAnimationFrame(benchmarkFrame)
  })

  onCleanup(() => {
    stopObservingFeed()
    cancelAnimationFrame(runtime.animationFrameId)
    runtime.longAnimationFrameObserver?.disconnect()
    runtime.mutationObserver?.disconnect()
  })

  const resetViewState = (): void => {
    setSelectedSymbol(null)
  }

  const actions = {
    resetViewState,
    setRendererMode,
    setVirtualScrollEnabled(enabled: boolean): void {
      if (feed.state.instrumentCount() >= FORCED_VIRTUALIZATION_ROW_COUNT)
        return
      setRequestedVirtualScrollMode(enabled ? 'tanstack' : 'none')
    },
    setRenderedRowCount,
    selectSymbol: setSelectedSymbol,
    resetMarket(): void {
      monitor.reset()
      resetViewState()
      setMetrics({ ...initialMetrics })
      feed.actions.reset()
    },
  }

  const virtualScrollForced = createMemo(
    () => feed.state.instrumentCount() >= FORCED_VIRTUALIZATION_ROW_COUNT,
  )
  const virtualScrollMode = createMemo(() =>
    resolveVirtualScrollMode(
      requestedVirtualScrollMode(),
      feed.state.instrumentCount(),
    ),
  )
  const mountedCells = createMemo(
    () => renderedRowCount() * TRADING_COLUMN_COUNT,
  )
  const liveComponents = createMemo(
    () => metrics().componentsCreated - metrics().componentsDestroyed,
  )

  return {
    feed,
    state: {
      rendererMode,
      requestedVirtualScrollMode,
      virtualScrollForced,
      virtualScrollMode,
      renderedRowCount,
      selectedSymbol,
      metrics,
      mountedCells,
      liveComponents,
    },
    actions,
    monitor,
  }
}

export type TradingBenchmarkController = ReturnType<
  typeof createTradingBenchmarkController
>

// examples/angular/realtime-trading/src/app/benchmark/trading-benchmark.controller.ts
import {
  DestroyRef,
  Injectable,
  computed,
  inject,
  isDevMode,
  signal,
} from '@angular/core'
import { TRADING_COLUMN_COUNT } from '../table/table-config/trading-column-types'
import { MarketFeedService } from '../feed/market-feed.service'
import {
  FORCED_VIRTUALIZATION_ROW_COUNT,
  resolveVirtualScrollMode,
} from '../table/trading-row-virtualizer'
import { BenchmarkMonitor, initialMetrics } from './benchmark-monitor'
import type {
  VirtualScrollMode,
  VirtualScrollPreference,
} from '../table/trading-row-virtualizer'
import type { FeedMetrics } from './benchmark-monitor'
import type { RendererMode } from '../table/table-config/trading-column-types'

@Injectable({ providedIn: 'root' })
export class TradingBenchmarkController {
  readonly #destroyRef = inject(DestroyRef)
  readonly #monitor = new BenchmarkMonitor()
  readonly #feed = inject(MarketFeedService)
  readonly #longAnimationFrameObserver: PerformanceObserver | null

  readonly devMode = isDevMode()
  readonly longAnimationFramesSupported =
    PerformanceObserver.supportedEntryTypes.includes('long-animation-frame')
  readonly tableWorkerEnabled = signal(false)
  readonly renderedRowCount = signal(0)
  readonly rendererMode = signal<RendererMode>('stable')
  readonly requestedVirtualScrollMode = signal<VirtualScrollPreference>('auto')
  readonly selectedSymbol = signal<string | null>(null)
  readonly metrics = signal<FeedMetrics>(initialMetrics)
  readonly displayQuotes = this.#feed.quotes
  readonly selectedQuote = computed(() => {
    const symbol = this.selectedSymbol()
    return symbol
      ? (this.displayQuotes().find((quote) => quote.symbol === symbol) ?? null)
      : null
  })
  readonly virtualScrollForced = computed(
    () => this.#feed.instrumentCount() >= FORCED_VIRTUALIZATION_ROW_COUNT,
  )
  readonly virtualScrollMode = computed<VirtualScrollMode>(() =>
    resolveVirtualScrollMode(
      this.requestedVirtualScrollMode(),
      this.#feed.instrumentCount(),
    ),
  )
  readonly mountedCells = computed(
    () => this.renderedRowCount() * TRADING_COLUMN_COUNT,
  )
  readonly liveComponents = computed(() => {
    const metrics = this.metrics()
    return metrics.componentsCreated - metrics.componentsDestroyed
  })

  #animationFrameId: number | null = null

  constructor() {
    const stopObservingFeed = this.#feed.observe({
      messageReceived: () => this.#monitor.recordWorkerMessage(),
      mutationStarted: () => this.#monitor.markRenderPending(),
      batchApplied: ({ tickCount, updateCount, supersededUpdateCount }) =>
        this.#monitor.recordBatch(
          tickCount,
          updateCount,
          supersededUpdateCount,
        ),
      renderCommitted: () => this.#monitor.recordCompletedRender(),
    })
    this.#longAnimationFrameObserver = this.longAnimationFramesSupported
      ? new PerformanceObserver(this.#recordLongAnimationFrames)
      : null
    this.#longAnimationFrameObserver?.observe({
      type: 'long-animation-frame',
    })
    this.#animationFrameId = requestAnimationFrame(this.#benchmarkFrame)
    this.#destroyRef.onDestroy(() => {
      stopObservingFeed()
      if (this.#animationFrameId !== null) {
        cancelAnimationFrame(this.#animationFrameId)
      }
      this.#longAnimationFrameObserver?.disconnect()
    })
  }

  setRendererMode(shouldSwap: boolean): void {
    this.rendererMode.set(shouldSwap ? 'swap' : 'stable')
  }

  setTableWorkerEnabled(enabled: boolean): void {
    this.tableWorkerEnabled.set(enabled)
  }

  setVirtualScrollEnabled(enabled: boolean): void {
    if (this.virtualScrollForced()) return
    this.requestedVirtualScrollMode.set(enabled ? 'tanstack' : 'none')
  }

  setRenderedRowCount(count: number): void {
    this.renderedRowCount.set(count)
  }

  recordDomMutations(count: number): void {
    this.#monitor.recordDomMutations(count)
  }

  resetDomMutations(): void {
    this.#monitor.resetDomMutations()
  }

  resetViewState(): void {
    this.selectedSymbol.set(null)
    this.requestedVirtualScrollMode.set('auto')
  }

  resetMarket(): void {
    this.#monitor.reset()
    this.resetViewState()
    this.metrics.set(initialMetrics)
    this.#feed.reset()
  }

  readonly #benchmarkFrame = (now: number): void => {
    this.#monitor.recordAnimationFrame(now)
    if (this.#monitor.shouldPublish(now)) {
      this.metrics.set(this.#monitor.publish(now))
    }
    this.#animationFrameId = requestAnimationFrame(this.#benchmarkFrame)
  }

  readonly #recordLongAnimationFrames = (
    entries: PerformanceObserverEntryList,
  ): void => {
    for (const entry of entries.getEntries()) {
      this.#monitor.recordLongAnimationFrame(entry.duration, entry.startTime)
    }
  }
}
