// examples/solid/with-tanstack-router/src/components/debouncedInput.tsx
import { createDebouncer } from '@tanstack/solid-pacer/debouncer'
import { createEffect, createSignal } from 'solid-js'

type DebouncedInputProps = {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
  devtoolsKey: string
  class?: string
  type?: string
  placeholder?: string
}

export function DebouncedInput(props: DebouncedInputProps) {
  const [value, setValue] = createSignal<string | number>(props.value)

  createEffect(() => {
    setValue(() => props.value)
  })

  const onChangeDebouncer = createDebouncer(
    (nextValue: string | number) => props.onChange(nextValue),
    {
      key: props.devtoolsKey,
      wait: () => props.debounce ?? 200,
    },
  )

  createEffect(() => {
    onChangeDebouncer.maybeExecute(value())
  })

  return (
    <input
      type={props.type ?? 'text'}
      value={value()}
      onInput={(e) => {
        if (e.currentTarget.value === '') {
          setValue('')
        } else if (props.type === 'number') {
          setValue(e.currentTarget.valueAsNumber)
        } else {
          setValue(e.currentTarget.value)
        }
      }}
      placeholder={props.placeholder}
      class={props.class}
    />
  )
}

// examples/react/with-tanstack-router/src/components/debouncedInput.tsx
import { useDebouncedCallback } from '@tanstack/react-pacer/debouncer'
import { useEffect, useState } from 'react'
import type { InputHTMLAttributes } from 'react'

export function DebouncedInput({
  value: initialValue,
  onChange,
  debounce = 200,
  devtoolsKey,
  ...props
}: {
  value: string | number
  onChange: (value: string | number) => void
  debounce?: number
  devtoolsKey: string
} & Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'>) {
  const [value, setValue] = useState<string | number>(initialValue)

  useEffect(() => {
    setValue(initialValue)
  }, [initialValue])

  const debouncedOnChange = useDebouncedCallback(onChange, {
    key: devtoolsKey,
    wait: debounce,
  })

  return (
    <input
      {...props}
      value={value}
      onChange={(e) => {
        const nextValue =
          e.target.value === ''
            ? ''
            : props.type === 'number'
              ? e.target.valueAsNumber
              : e.target.value

        setValue(nextValue)
        debouncedOnChange(nextValue)
      }}
    />
  )
}
