// examples/svelte/with-tanstack-form/src/FormStateIndicator.svelte
<script lang="ts">
  import { useFormContext } from './form-context.js'

  const form = useFormContext()
</script>

<form.Subscribe
  selector={(state) => ({
    isDirty: state.isDirty,
    isValid: state.isValid,
  })}
>
  {#snippet children({ isDirty, isValid })}
    <div class="form-status">
      <span class={isDirty ? 'warning-text' : 'muted-text'}>
        {isDirty ? '● Modified' : '○ Pristine'}
      </span>
      <span class={isValid ? 'success-text' : 'error-text'}>
        {isValid ? '✓ Valid' : '✗ Invalid'}
      </span>
    </div>
  {/snippet}
</form.Subscribe>

// examples/vue/with-tanstack-form/src/FormStateIndicator.vue
<script setup lang="ts">
defineProps<{
  form: any
}>()

const selector = (state: { isDirty: boolean; isValid: boolean }) => ({
  isDirty: state.isDirty,
  isValid: state.isValid,
})
</script>

<template>
  <component :is="form.Subscribe" :selector="selector" v-slot="state">
    <div class="form-status">
      <span :class="state.isDirty ? 'warning-text' : 'muted-text'">
        {{ state.isDirty ? 'Modified' : 'Pristine' }}
      </span>
      <span :class="state.isValid ? 'success-text' : 'error-text'">
        {{ state.isValid ? 'Valid' : 'Invalid' }}
      </span>
    </div>
  </component>
</template>
