// examples/svelte/with-tanstack-form/src/SelectField.svelte
<script lang="ts">
  import { useFieldContext } from './form-context.js'

  const field = useFieldContext<string>()

  const statusOptions = ['relationship', 'complicated', 'single'] as const
</script>

<div>
  <select
    class="compact-input"
    value={field.state.value}
    onchange={(e: Event) =>
      field.handleChange((e.target as HTMLSelectElement).value)}
    onblur={() => field.handleBlur()}
  >
    {#each statusOptions as status}
      <option value={status}>{status}</option>
    {/each}
  </select>
  {#if field.state.meta.errors.length > 0}
    <div class="error-text">{field.state.meta.errors.join(', ')}</div>
  {/if}
</div>

// examples/vue/with-tanstack-form/src/SelectField.vue
<script setup lang="ts">
import { getErrorMessage, shouldShowErrors } from './field-utils'

defineProps<{
  form: any
  name: string
}>()

const statusOptions = ['relationship', 'complicated', 'single'] as const
</script>

<template>
  <component :is="form.Field" :name="name" v-slot="{ field, state }">
    <div>
      <select
        class="compact-input"
        :value="state.value"
        @change="field.handleChange(($event.target as HTMLSelectElement).value)"
        @blur="field.handleBlur()"
      >
        <option v-for="status in statusOptions" :key="status" :value="status">
          {{ status }}
        </option>
      </select>
      <div v-if="shouldShowErrors(state.meta)" class="error-text">
        {{ state.meta.errors.map(getErrorMessage).join(', ') }}
      </div>
    </div>
  </component>
</template>
