// examples/svelte/with-tanstack-form/src/SubmitButton.svelte
<script lang="ts">
  import { useFormContext } from './form-context.js'

  const form = useFormContext()

  const { label }: { label: string } = $props()
</script>

<form.Subscribe
  selector={(state) => ({
    isSubmitting: state.isSubmitting,
    canSubmit: state.canSubmit,
  })}
>
  {#snippet children({ isSubmitting, canSubmit })}
    <button
      type="submit"
      disabled={!canSubmit || isSubmitting}
      class="demo-button primary-action submit-button"
    >
      {isSubmitting ? 'Submitting...' : label}
    </button>
  {/snippet}
</form.Subscribe>

// examples/vue/with-tanstack-form/src/SubmitButton.vue
<script setup lang="ts">
defineProps<{
  form: any
  label: string
}>()

const selector = (state: { canSubmit: boolean; isSubmitting: boolean }) => ({
  canSubmit: state.canSubmit,
  isSubmitting: state.isSubmitting,
})
</script>

<template>
  <component :is="form.Subscribe" :selector="selector" v-slot="state">
    <button
      type="submit"
      :disabled="!state.canSubmit || state.isSubmitting"
      class="demo-button primary-action submit-button"
    >
      {{ state.isSubmitting ? 'Submitting...' : label }}
    </button>
  </component>
</template>
