// packages/react-table/src/createTableHelper.ts
'use client'
import { constructTableHelper } from '@tanstack/table-core'
import { useTable } from './useTable'
import type { ReactTable } from './useTable'
import type {
  RowData,
  TableFeatures,
  TableHelperOptions,
  TableHelper_Core,
  TableOptions,
  TableState,
} from '@tanstack/table-core'

export type ReactTableHelper<TFeatures extends TableFeatures> = Omit<
  TableHelper_Core<TFeatures>,
  'tableCreator'
> & {
  useTable: <TData extends RowData, TSelected = {}>(
    tableOptions: Omit<
      TableOptions<TFeatures, TData>,
      '_features' | '_rowModels'
    >,
    selector?: (state: TableState<TFeatures>) => TSelected,
  ) => ReactTable<TFeatures, TData, TSelected>
}

export function createTableHelper<TFeatures extends TableFeatures>(
  tableHelperOptions: TableHelperOptions<TFeatures>,
): ReactTableHelper<TFeatures> {
  const tableHelper = constructTableHelper(useTable as any, tableHelperOptions)
  return {
    ...tableHelper,
    useTable: <TData extends RowData, TSelected = {}>(
      tableOptions: Omit<
        TableOptions<TFeatures, TData>,
        '_features' | '_rowModels'
      >,
      selector?: (state: TableState<TFeatures>) => TSelected,
    ) => {
      return useTable<TFeatures, TData, TSelected>(
        { ...tableHelper.options, ...tableOptions } as TableOptions<
          TFeatures,
          TData
        >,
        selector,
      )
    },
  }
}

// packages/angular-table/src/createTableHelper.ts
import { constructTableHelper } from './constructTableHelper'
import { injectTable, AngularTable } from './injectTable'
import type { TableHelperOptions } from './constructTableHelper'
import type { Signal } from '@angular/core'
import type {
  RowData,
  Table,
  TableFeatures,
  TableHelper_Core,
  TableOptions,
  TableState,
} from '@tanstack/table-core'

export type TableHelper<
  TFeatures extends TableFeatures,
  TData extends RowData = any,
> = Omit<TableHelper_Core<TFeatures, TData>, 'tableCreator'> & {
  injectTable: <TInferData extends TData, TSelected = {}>(
    tableOptions: () => Omit<
      TableOptions<TFeatures, TInferData>,
      '_features' | '_rowModels'
    >,
    selector?: (state: TableState<TFeatures>) => TSelected,
  ) => AngularTable<TFeatures, TInferData, TSelected>
}

export function createTableHelper<
  TFeatures extends TableFeatures,
  TData extends RowData = any,
>(
  tableHelperOptions: TableHelperOptions<TFeatures, TData>,
): TableHelper<TFeatures, TData> {
  const tableHelper = constructTableHelper(
    injectTable as unknown as (
      tableOptions: () => TableOptions<TFeatures, TData>,
      selector?: (state: TableState<TFeatures>) => any,
    ) => AngularTable<TFeatures, TData, any>,
    tableHelperOptions,
  )
  return {
    ...tableHelper,
    injectTable: <TInferData extends TData, TSelected = {}>(
      tableOptions: () => Omit<
        TableOptions<TFeatures, TInferData>,
        '_features' | '_rowModels'
      >,
      selector?: (state: TableState<TFeatures>) => TSelected,
    ) => {
      return injectTable<TFeatures, TInferData, TSelected>(
        () =>
          ({
            ...tableHelper.options,
            ...tableOptions(),
          }) as TableOptions<TFeatures, TInferData>,
        selector,
      )
    },
  } as TableHelper<TFeatures, TData>
}

// test

// type Person = {
//   firstName: string
//   lastName: string
//   age: number
// }

// const tableHelper = createTableHelper({
//   _features: { rowSelectionFeature: {} },
//   TData: {} as Person,
// })

// const columns = [
//   tableHelper.columnHelper.accessor('firstName', { header: 'First Name' }),
//   tableHelper.columnHelper.accessor('lastName', { header: 'Last Name' }),
//   tableHelper.columnHelper.accessor('age', { header: 'Age' }),
//   tableHelper.columnHelper.display({ header: 'Actions', id: 'actions' }),
// ] as Array<ColumnDef<typeof tableHelper.features, Person, unknown>>

// const data: Array<Person> = []

// tableHelper.createTable({
//   columns,
//   data,
// })
